### ISSUE TITLE
why i could get only video,no audio using WhammyRecorder or MediaStreamRecorder

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RecordRTC#100]
hi,nice muaz-khan,i have save video from mywebrtc's stream under your support.
but i get only video,no audio when i set recordtype = MediaStreamRecorder 
and if i set recordtype = StereoAudioRecorder ,i could get only audio ,no video.
how can i get both video and audio in one file ?
i use chrome v49 on win7.
one thing should be noted.when i finish record and playback in browse video element, i could hear audio and see video simultaneously.but when i save to file,and then play the saved file,i could not hear audio.why?
hope for you light.thank you very much.

**Comment by Jackie2016** [comment]
ok,i know,if i use chrome to open,i could hear audio.thank muaz-khan.

**Comment by muaz-khan** [comment]
`{recorderType: MediaStreamRecorder}` is the only available option to record both audio/video tracks in a single WebM container.

**Comment by andyliangshan** [comment]
@muaz-khan  when set {recorderType: MediaStreamRecorder}   In win10 system, some Google browsers have some video recording sound, some video has no sound, please reply as soon as possible

**Comment by andyliangshan** [comment]
@Jackie2016 @zevarito @jmlacroix @jonklein  when set {recorderType: MediaStreamRecorder} In win10 system, some Google browsers have some video recording sound, some video has no sound, please reply as soon as possible
