### ISSUE TITLE
Recording multiple videos from the same stream broken in Chrome?

### ISSUE THREAD

**Issue by ruiramos** [muaz-khan/RecordRTC#101]
I used to be able to record multiple videos from the same stream (that is, to call `startRecording` and `stopRecording` multiple times on the same getUserMedia stream) in order to save sequential videos. This still works in Firefox however in Chrome (v. 48 here) I now get a `Something went wrong. Maybe WebP format is not supported in the current browser.` for all captures after the first one. Any ideas?
Thanks!

**Comment by ruiramos** [comment]
Think I fixed it here https://github.com/ruiramos/recordrtc
Had to do with WhammyRecorder's `resume` method not resetting `isStopDrawing` and not calling `this.record` again. Let me know if you want a PR.

**Comment by robinnorth** [comment]
@ruiramos It seems that it's actually `CanvasRecorder`'s `resume` method not calling `this.record` again that's the issue here.

```js
/**
 * This method resumes the recording process.
 * @method
 * @memberof CanvasRecorder
 * @example
 * recorder.resume();
 */
this.resume = function() {
    isPausedRecording = false;
    this.record();
};
```

...seems to do the trick 🎉
