### ISSUE TITLE
Uncaught TypeError: mediaStream.getVideoTracks is not a function

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RecordRTC#102]
hi,nice experts

i can record my localstream.but today i test record remote stream,i meet error like this:
Successfully connected  RecordRTC.js:563 
started recording video stream RecordRTC.js:47 
**Uncaught TypeError: mediaStream.getVideoTracks is not a function   RecordRTC.js:753**
It seems that "startRecording" is not invoked for video recorder.

i trace ,it show errors here in RecordRTC.js,
    // html2canvas recording!
    if (config.type === 'canvas') {
        recorder = CanvasRecorder;
    }
    // todo: enable below block when MediaRecorder in Chrome gets out of flags; and it 
also supports audio recording.
    if (isMediaRecorderCompatible() && isChrome && recorder !== CanvasRecorder && recorder 
!== GifRecorder && typeof MediaRecorder !== 'undefined' && 'requestData' in 
MediaRecorder.prototype) {
        if (**mediaStream.getVideoTracks()**.length) {
            recorder = MediaStreamRecorder;
        }
    }

later,i remove  if (**mediaStream.getVideoTracks()**.length) {
then,i get Uncaught TypeError: Failed to construct 'MediaRecorder': parameter 1 is not of type 'MediaStream' in RecordRTC.js 1515
it is  mediaRecorder = new MediaRecorder(mediaStream, recorderHints);

i use chrome v49 and run chrome with --unsafely-treat-insecure-origin-as-secure flags
i can record localstream successfully,no such error.
what's wrong with me?any light or answer will be appreciated
thanks

**Comment by muaz-khan** [comment]
Please check this: https://github.com/muaz-khan/RecordRTC/issues/130#issuecomment-228487648
