### ISSUE TITLE
How to Record in MONO not Stereo

### ISSUE THREAD

**Issue by itpacspro** [muaz-khan/RecordRTC#103]
I am using this recorder to record audio then play it back in another applet.  The other applet only allow the play back of Mono WAV files.  Is there a setting for the player to record in MONO instead of Stereo.

If not is there a script that can be used to convert the file prior to upload back to the server. 

my environment is php, apache, google chrome

**Comment by muaz-khan** [comment]
MediaRecorder API does NOT provides any API to force Mono. It will always be stereo audio.

`{recorderType:StereoAudioRecorder}` can support [`mono` audio](https://github.com/muaz-khan/RecordRTC#numberofaudiochannels), though.

**Comment by itpacspro** [comment]
Can you explain how to use this please I have been waiting months for a response on this..

I would really appreciate it

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
