### ISSUE TITLE
RecordRTC Source Code

### ISSUE THREAD

**Issue by thebaud2u** [muaz-khan/RecordRTC#106]
Hi, can you please post somewhere the source code of the demo you show on this page : 
https://www.webrtc-experiment.com/RecordRTC/

I've tried copying the javascript code with the console to use it myself. 
Unfortunately, the start recording button never switch to stop recording, but it does correctly on your demo page.

Here are the script files I use : 
`<script src="https://cdn.webrtc-experiment.com/RecordRTC.js"></script>
<script src="https://cdn.webrtc-experiment.com/gumadapter.js"></script>`

Basicly I arrive at this point : 
`
var commonConfig = {
                    onMediaCaptured: function(stream) {
                        button.stream = stream;
                        if(button.mediaCapturedCallback) {
                            button.mediaCapturedCallback();
                        }
                        button.innerHTML = 'Stop Recording';
                        button.disabled = false;
                    },
                    onMediaStopped: function() {
                        button.innerHTML = 'Start Recording';
                        
                        if(!button.disableStateWaiting) {
                            button.disabled = false;
                        }
                    },
                    onMediaCapturingFailed: function(error) {
                        if(error.name === 'PermissionDeniedError' && !!navigator.mozGetUserMedia) {
                            intallFirefoxScreenCapturingExtension();
                        }
                        
                        commonConfig.onMediaStopped();
                    }
                };`

And it's not enterring the onMediaCaptured function, so it can't change button.innerHTML to Stop recording.

**Comment by muaz-khan** [comment]
Here is the source-code:

* https://github.com/muaz-khan/RecordRTC/blob/master/index.html

You MUST run it either on localhost or HTTPs.

**Comment by thebaud2u** [comment]
Thank you very much.
