### ISSUE TITLE
how to deploy recordrtc?

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RecordRTC#107]
hi,muaz,
thanks for your answer in all my questions.I am sorry i can't understand everything you said.I use your 2016-3-17 updated recordRTC.js.i also have getvideotrack() is not function error.i check my deployment of recordrtc in my nodes system.i find i only put recordRTC.js and gumadapter.js in my js dir of application.i remove all of other dir such as dev and libs from original recordRTC.however i also could get localstream and save them into a webm files only by recordrtc.js.it is same with using `<script src="https://cdn.webrtc-experiment.com/RecordRTC.js"> .`
no matter by only recordRTC.js or  `<script src="https://cdn.webrtc-experiment.com/RecordRTC.js">`,even by recordRTC.js+dev dir+libs dir,i met same error: getvideotrack() is not function.i don't know if i am wrong with deployment of recordrtc.could you lead me?
you are appreciated.thank you for every support and light .

**Comment by muaz-khan** [comment]
Please open this page:

* https://www.webrtc-experiment.com/DetectRTC/

Then click `Print & Save as Image` and share/attach that image here in your comment.

**Comment by Jackie2016** [comment]
i try many times to attach DetectRTC.jpg,but i can't success.so i copy html text here.and later i try upload jpg again.


DetectRTC!
Operating System	Windows version: 7
Browser	Chrome version: 49.0.2623.87
Private browsing? Nope
Display resolutions	1024 x 768
System has Speakers?	Yep
Found speaker devices: 3
默认
通讯
扬声器 (Realtek High Definition Audio)
System has Microphone?	Yep
Found microphone devices: 3
默认
通讯
麦克风 (Realtek High Definition Audio)
System has Webcam?	Yep
Found webcam devices: 2
HP Truevision HD (04f2:b34f)
screen-capture-recorder
Website has webcam permissions?	Yep
Website has mcirophone permissions?	Yep
Browser allows getUserMedia on this page?	Yep
Can you change output audio devices?	Yep
Can you change camera resolutions without making new getUserMedia request?	Nope
Browser Supports WebRTC (Either 1.0 or 1.1)?	Yep
Browser Supports ORTC (WebRTC 1.1)?	Nope
Can you replace tracks without renegotiating peers?	Nope
Can your browser record remote audio or process remote audio stream in WebAudio API?	Nope
Browser Supports WebSockets API?	Yep
Your system blocked WebSockets protocol or WebSockets server is not accessible?	Nope
Browser Supports WebAudio API?	Yep
Browser Supports SCTP Data Channels?	Yep
Browser Supports RTP Data Channels?	Yep
This page Supports Screen Capturing API?	Yep
Is this browser supports multi-monitor selection & capturing screen of any monitor?	Nope
Is it a mobile device?	Nope
Browser Supports WebSockets?	Yep
Is Browser Supports Stream Capturing from Canvas?	Nope
Is Browser Supports Stream Capturing from Video?	Nope
Is Browser Supports Promises?	Yep
MediaStream.prototype:
id, active, onactive, oninactive, onended, onaddtrack, onremovetrack, getAudioTracks, getVideoTracks, getTracks, addTrack, removeTrack, getTrackById, clone	Yep
MediaStreamTrack.prototype:
kind, id, label, enabled, muted, remote, readyState, onmute, onunmute, onended, stop, clone	Yep
RTCPeerConnection.prototype:
localDescription, remoteDescription, signalingState, iceGatheringState, iceConnectionState, onnegotiationneeded, onicecandidate, onsignalingstatechange, oniceconnectionstatechange, ondatachannel, onaddstream, onremovestream, close, createOffer, setLocalDescription, createAnswer, setRemoteDescription, addIceCandidate, getStats, createDataChannel, updateIce, getLocalStreams, getRemoteStreams, getStreamById, addStream, removeStream, createDTMFSender	Yep

**Comment by Jackie2016** [comment]
This is peer device's result of detectrtc as below
Operating System	Android version: Unknown OS Version
Browser	Chrome version: 42.0.2311.107
Private browsing? Nope
Display resolutions	320 x 570
System has Speakers?	Nope
System has Microphone?	Yep
Found microphone devices: 3
Default
Speakerphone
Headset earpiece
System has Webcam?	Yep
Found webcam devices: 2
camera 1, facing front
camera 0, facing back
Website has webcam permissions?	Yep
Website has mcirophone permissions?	Yep
Browser allows getUserMedia on this page?	Yep
Can you change output audio devices?	Nope
Can you change camera resolutions without making new getUserMedia request?	Nope
Browser Supports WebRTC (Either 1.0 or 1.1)?	Yep
Browser Supports ORTC (WebRTC 1.1)?	Nope
Can you replace tracks without renegotiating peers?	Nope
Can your browser record remote audio or process remote audio stream in WebAudio API?	Nope
Browser Supports WebSockets API?	Yep
Your system blocked WebSockets protocol or WebSockets server is not accessible?	Nope
Browser Supports WebAudio API?	Yep
Browser Supports SCTP Data Channels?	Yep
Browser Supports RTP Data Channels?	Yep
This page Supports Screen Capturing API?	Yep
Is this browser supports multi-monitor selection & capturing screen of any monitor?	Nope
Is it a mobile device?	Yep
Browser Supports WebSockets?	Yep
Is Browser Supports Stream Capturing from Canvas?	Nope
Is Browser Supports Stream Capturing from Video?	Nope
Is Browser Supports Promises?	Yep
MediaStream.prototype:
getAudioTracks, getVideoTracks, getTracks, addTrack, removeTrack, getTrackById, clone, stop	Yep
MediaStreamTrack.prototype:
stop, clone	Yep
RTCPeerConnection.prototype:
createOffer, createAnswer, setLocalDescription, setRemoteDescription, updateIce, addIceCandidate, getLocalStreams, getRemoteStreams, getStreamById, addStream, removeStream, getStats, createDataChannel, createDTMFSender, close	Yep

**Comment by Jackie2016** [comment]
Is it because my peer device is Android system to generate my error:getvideotracks is not a function?

**Comment by Jackie2016** [comment]
I have make experiment which  two partner of chat all are on windows7 and chrome v49.and the result is same.we get uncaught typeerror mediastream.getvideotracks is not a function  recordrtc.js 735

**Comment by muaz-khan** [comment]
Please check this: https://github.com/muaz-khan/RecordRTC/issues/130#issuecomment-228487648
