### ISSUE TITLE
RecordRTC playback on Firefox

### ISSUE THREAD

**Issue by chrisghardwick** [muaz-khan/RecordRTC#108]
Using the latest version the playback feature seems to be broken in Firefox. The record/save function works normally, but the playback does not work.

I also checked it against the demo (https://www.webrtc-experiment.com/RecordRTC/), and it has the same problem.

To reproduce it:
1. Open Firefox
2. https://www.webrtc-experiment.com/RecordRTC/
3. Select "Audio+Video"
4. Click "Start Recording"
 -Record Function appears to work normally.
5. Click "Stop Recording"
6. Playback after video ends does not appear, and the screen looks blank:  http://screencast.com/t/ZwqyjDQa

My Firefox Version Info:
Firefox 44.0.2 on x64 Windows 8

Working with RecordRTC.js latest version (from https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js). Last time updated: 2016-03-17 12:41:43 PM UTC

**Comment by alexschomb** [comment]
Can confirm this on Firefox 44.0.2 on Mac OS X 10.11.3. Google Chrome works fine.

**Comment by chrisghardwick** [comment]
@muaz-khan - Can you help with this issue?

**Comment by muaz-khan** [comment]
A dirty ([very old](https://github.com/muaz-khan/RecordRTC/blob/master/AudioVideo-on-Firefox.html#L130-L135)) hack:

```javascript
videoElement.onend = function() {
    videoElement.pause();

    // dirty workaround for: "firefox seems unable to playback"
    videoElement.src = URL.createObjectURL(audioVideoRecorder.getBlob());
};
```

Demo: https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html
