### ISSUE TITLE
Recording audio at 22050 Hz produces weird file

### ISSUE THREAD

**Issue by sk-** [muaz-khan/RecordRTC#115]
When you record audio in Chrome 48 at 22050 Hz the recorded file seems to be playing at a much lower speed.

Attached is an audio file, that is supposed to say "this is a test".
[test.wav.zip](https://github.com/muaz-khan/RecordRTC/files/197668/test.wav.zip)

**Comment by muaz-khan** [comment]
Please check [bufferSize](https://github.com/muaz-khan/RecordRTC#buffersize) and [sampleRate](https://github.com/muaz-khan/RecordRTC#samplerate)

`sampleRate` can be customized only on Mac. Otherwise we have to use system's default sample-rates.
