### ISSUE TITLE
MRecordRTC not accessible with require('recordrtc')

### ISSUE THREAD

**Issue by maxpaj** [muaz-khan/RecordRTC#116]
Today I tried using browserify with RecordRTC. I found that MRecordRTC and other components are not exposed this way. In my case I cannot load any scripts through the DOM, so all scripts are loaded through require(), which only allowed me to use the RecordRTC module. 

I changed the assignment of module.exports as follows which exposed MRecordRTC aswell:
```
if (typeof module !== 'undefined' /* && !!module.exports*/ ) {
    
    module.exports = { 
        RecordRTC: RecordRTC,
        MRecordRTC: MRecordRTC
    }
}
```

**Comment by thijstriemstra** [comment]
@maxpaj Can you make a pull request for this? you'll need to edit the one in `dev/`

**Comment by Perezmarc** [comment]
Hi. 
I'm trying to integrate it with angular aswell, and I have the same problem, I can only use RecortRTC module using require. I want to use Whammy, and tried the following, but still it says that WhammyRecorder is not a constructor. 
if (typeof module !== 'undefined' /* && !!module.exports*/ ) {
    module.exports = {
        RecordRTC: RecordRTC,
        MRecordRTC: MRecordRTC,
        WhammyRecorder: WhammyRecorder
    }
}
