### ISSUE TITLE
Chrome Crashes

### ISSUE THREAD

**Issue by sarvanhsr** [muaz-khan/RecordRTC#117]
Chrome crashes when we invoke 
// to sync audio/video playbacks in browser!
                            videoRecorder.initRecorder(function() {
                                audioRecorder.initRecorder(function() {
                                    audioRecorder.startRecording();
                                    videoRecorder.startRecording();
                                });
                            });

Please help.

**Comment by thijstriemstra** [comment]
@muaz-khan I'm seeing the same crash on Firefox as well, this is probably related to one of the latest commits?

**Comment by thijstriemstra** [comment]
For example, in MRecordRTC

```javascript
self.videoRecorder.initRecorder(function() {
    self.audioRecorder.initRecorder(function() {
        // Both recorders are ready to record things accurately
        self.videoRecorder.startRecording();
        self.audioRecorder.startRecording();
    });
});
```
will call the` initCallback` twice, because of this in `MediaStreamRecorder`:

```javascript
if (config.initCallback) {
    config.initCallback();
}
```
which drives it into an infinite loop, eventually throwing an `OutOfMemory` exception.
