### ISSUE TITLE
RecordRTC doesn't removes chrome "red dot"

### ISSUE THREAD

**Issue by ktabori** [muaz-khan/RecordRTC#119]
![screenshot 2016-04-14 12 40 30](https://cloud.githubusercontent.com/assets/2427061/14525513/1ba44b68-023e-11e6-975c-fa87d2765d8d.png)

If I start recording with recorder.startRecording(); the red dot gets visible on chrome tab. It is fine, but when I stop recording with recorder.stopRecording(); the red dot is still visible.

I found a workaround!, if I use mediaStream.stop(); then the red dot got removed but I got also an error from the browser:

![screenshot 2016-04-14 12 44 30](https://cloud.githubusercontent.com/assets/2427061/14525630/a881e18a-023e-11e6-996b-148f0f43a5ec.png)

Do you have any idea about what is wrong?

**Comment by muaz-khan** [comment]
You can [easily skip it](https://github.com/muaz-khan/RecordRTC#disablelogs).

```javascript
var recorder = RecordRTC(mediaStream, {
  disableLogs: true
});
```

PS. It should be `warning` **notification** rather than an `error`. It will be fixed in next commit.

**Comment by ktabori** [comment]
Thank you for the fast answer! Can we close this issue?

**Comment by buzinas** [comment]
Shouldn't the Recorder automatically stop the stream on `stopRecording`?

Related https://github.com/zzarcon/microm/issues/24

**Comment by zzarcon** [comment]
@buzinas I think you are right, ```stopRecording``` should do that if possible.

Will be happy to merge that if you open PR. Thanks! 🚀

**Comment by Shahzaibmalik55** [comment]
@muaz-khan i am using this library but after adding `disableLogs: true` the red dot doesn't disappear

**Comment by Aman1324** [comment]
is there any solution of removing red dot with recordRTC. ??

**Comment by muaz-khan** [comment]
@Aman1324 You've to stop (i.e. release) the MediaStream object:

```javascript
stream.getTracks().forEach(function(track) {
    track..stop();
});
```

**Comment by Aman1324** [comment]
thanks @muaz-khan for your answer. One more question i want to ask that what is the ios version and safri browser compatibility of recordRTC.
