### ISSUE TITLE
Can't open audio+video recording downloaded from Chrome (Linux)

### ISSUE THREAD

**Issue by AndersSchmidtHansen** [muaz-khan/RecordRTC#120]
Hi Muaz,

First off, huge thanks to you and all the contributors for some amazing work. Really grateful for it.

On Linux I noticed that if I record a webcam recording (with audio) in Chrome, download it and try to view it in VLC, Audience or any other video player, I get a "Install audio/x-unknown decoder" issue.

But only if downloaded through Chrome. It works without any problems if downloaded through Firefox.

I also noticed that this problem occurs in the official example from the Google Dev team: https://webrtc.github.io/samples/src/content/getusermedia/record/

Chrome versions tested are 49 (Stable), 50 (Dev) and 51 (Dev).

Am I missing something? After a lot of searching, it seems impossible to find whatever decoder is needed. Maybe it's just a Linux issue? If it is, I apologize for bringing it up here.

**Comment by muaz-khan** [comment]
Hi, create new (fresh) blob-uri, open in a new tab, right-click "save as..." option and it will (may) work.

**Comment by AndersSchmidtHansen** [comment]
Thanks for the quick reply. :)

I tried doing just that in your example here: https://www.webrtc-experiment.com/RecordRTC/ and the official webrtc example (create the blob, open in new tab, save as..), but the file itself won't open due to something that happens with the audio codec when downloading the file through Chrome.

One thing I discovered is that if you convert the .webm file to .mp4 or .mkv afterwards, it works perfectly. Strange.

I'll try on Windows when I can get my hands on one. I guess it must be a Linux / Chrome thing.

Thanks Muaz.

**Comment by AndersSchmidtHansen** [comment]
We've tested it out now and it has to be a Linux-only problem. The .webm file seems to work perfectly (when opened in VLC or similar) on Windows when downloaded from the latest, stable version of Chrome.

So I'll close this issue and look more into why this happens in Linux Chrome. Thanks for the help! :)
