### ISSUE TITLE
Make gifencoder a dependency in package.json

### ISSUE THREAD

**Issue by geloescht** [muaz-khan/RecordRTC#121]
This would help greatly for offline-usage, where including a file from a CDN is not an option. Also many people who use webpack/browserify don't want to include another file if they can have everything in one javascript bundle. Alternatively create a new npm package gif-recorder and make it a (optional?) dependency.

**Comment by geloescht** [comment]
Found out that a npm package exists for GIFEncoder, named gifencoder.

**Comment by geloescht** [comment]
Unfortunately, the newest version of GIFEncoder found on npm seems to be incompatible with RecordRTC.

**Comment by muaz-khan** [comment]
[`gif-recorder.js`](https://github.com/muaz-khan/RecordRTC/blob/master/libs/gif-recorder.js) is now included in the [`recordrtc@5.3.4`](https://www.npmjs.com/package/recordrtc) NPM package.

More info here: https://www.npmjs.com/package/recordrtc#npm-package

**Comment by muaz-khan** [comment]
I cannot include `gif-recorder.js` inside `RecordRTC.js` because it requires extra work (and fixes).

I can't even make it a standalone NPM package.

Following will always fail until `gif-recorder.js` is modified to handle AMD codes.

```javascript
var GifEncoder = require('recordrtc').GifEncoder.

var GifEncoder = require('gif-recorder');
```

The only option (currently) is:

```javascript
<script src="node_modules/recordrtc/gif-recorder.js"></script>
```

**Comment by geloescht** [comment]
It works at least with webpack's require. That's enough for me, thanks so much for the fast response :)

**Comment by muaz-khan** [comment]
Seems **WontFix** in https://www.npmjs.com/package/recordrtc.
