### ISSUE TITLE
How to record screen and video!!

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RecordRTC#124]
hi @muaz-khan !!
My case: I want record screen and video when opening broadcast... So how can i fix it??

thanks!

**Comment by muaz-khan** [comment]
I donno if multiple MediaRecorder instances are allowed.

You have to initiate two unique RecordRTC instances.

1. First instance should pass `{recorderType: MediaStreamRecorder}`.
2. Second instance should pass `{recorderType: WhammyRecorder}`.

Each instance will work separately. Each requires its own startRecording/stopRecording.

1. First instance can record video-stream
2. Second instance can record screen-stream

**Comment by NguyenTungs** [comment]
I use Record a Webpage. But really it is a good solution ???
