### ISSUE TITLE
Should we check for FF version before using MediaRecorder?

### ISSUE THREAD

**Issue by stoneman1** [muaz-khan/RecordRTC#126]
There is a problem with Firefox MediaRecorder on some versions so should we check for those versions and warn or something like that? Related link below.

https://bugzilla.mozilla.org/show_bug.cgi?id=1250984

**Comment by muaz-khan** [comment]
We can warn users if you're facing same issues in the **latest Firefox standard release**?

**Comment by muaz-khan** [comment]
Maybe you should make a pull-request for exact versions? E.g.

```
Firefox on Android (version: xyz) seems NOT supporting video-tracks recording.
......
......
etc.
```

**Comment by stoneman1** [comment]
Will look at this next week. Don't have any time this week. If someone has time and is willing to do this before me, let me know, so we don't do the same thing same time :)

**Comment by curiosity26** [comment]
For me, recording using the MediaStreamRecorder on Firefox 45.0.1 on Mac is REALLY choppy. Video continuously flickers in and out on playback. Is this similar to your issue or is it new?
