### ISSUE TITLE
`CanvasRecorder` sets the document title instead of logging to console

### ISSUE THREAD

**Issue by robinnorth** [muaz-khan/RecordRTC#129]
Unlike the other recorder classes, `CanvasRecorder` uses `document.title` to provide user feedback when recording and compiling its output instead of logging to console, which is an issue when using in a production web app.

See [`CanvasRecorder.js#L125`,](https://github.com/muaz-khan/RecordRTC/blob/56a7afb5f2b4be33f08fddc76c0dab9f0ea28ec1/dev/CanvasRecorder.js#L125) [`CanvasRecorder.js#L135`](https://github.com/muaz-khan/RecordRTC/blob/56a7afb5f2b4be33f08fddc76c0dab9f0ea28ec1/dev/CanvasRecorder.js#L135) and [`CanvasRecorder.js#L178`](https://github.com/muaz-khan/RecordRTC/blob/56a7afb5f2b4be33f08fddc76c0dab9f0ea28ec1/dev/CanvasRecorder.js#L178) in the latest development version.

**Comment by thijstriemstra** [comment]
@robinnorth can you make a pull request that changes it to console logging?
