### ISSUE TITLE
Problem converting ogg to mp3

### ISSUE THREAD

**Issue by majitimir** [muaz-khan/RecordRTC#13]
Hi , i used RecordRTC and implemented with angular js, audio recording is working fine in mozila and recorded blob type is ogg, so i saving file in server in ogg format. but i need it inmp3 format as we have to support in different phone os. So i further converting using ffmpeg (exec('/usr/bin/ffmpeg -i /var/www/dtswork/bluejaypt/us/bjaypt/uploads/index.ogg -acodec libmp3lame  /var/www/dtswork/bluejaypt/us/bjaypt/uploads/index.mp3 2>&1')) using above command but its giving  "/var/www/dtswork/bluejaypt/us/bjaypt/uploads/index.ogg: End of file" 

Please help its urgent

**Comment by muaz-khan** [comment]
There is a similar demo which can be reversed to convert wav-into-mp3:

* https://github.com/muaz-khan/Ffmpeg.js/blob/master/wav-to-ogg.html

Or wav-into-AAC:

* https://github.com/muaz-khan/Ffmpeg.js/blob/master/wav-to-aac.html
