### ISSUE TITLE
What's the difference between MRecordRTC and MultiStreamRecorder(MediaStreamRecorder)?

### ISSUE THREAD

**Issue by typec4st** [muaz-khan/RecordRTC#134]
Hello,

RecordRTC's MRecordRTC demo and MediaStreamRecorder's MultiStreamRecorder demo seem to achieve the same things, yet they use different libraries.

What am I missing here? To upload audio/video blobs real time to server, which lib should be used? Does RecordRTC provide more features (such as auto sync of audio and video blobs) or browser capabilities? 

Thanks

**Comment by muaz-khan** [comment]
### streamproc/MediaStreamRecorder

There is a separate repo named as "MediaStreamRecorder.js"

* https://github.com/streamproc/MediaStreamRecorder

> "Cross browser...........It follows latest MediaRecorder API standards and provides similar APIs."

That lib has its own demos:

* https://www.webrtc-experiment.com/msr/

The lib's primary goal is to provide "intervals-based-blobs".

### muaz-khan/RecordRTC

RecordRTC supposed to work differently. It does NOT follows any standards or any API-guidelines.

RecordRTC returns a COMPLETE_Blob as soon as recording is stopped.

RecordRTC has a sub-module named as [dev/MediaStreamRecorder.js](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js).

RecordRTC's submodule `dev/MediaStreamRecorder.js` is completely different comparing [streamproc/MediaStreamRecorder](https://github.com/streamproc/MediaStreamRecorder).

----

# (Above) Both projects are considered UNIQUE. Their files does NOT matches.

----

### MRecordRTC

[MRecordRTC.js](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MRecordRTC.js) is a standalone JavaScript file that runs top over RecordRTC.

i.e. MRecordRtC uses RecordRTC. It uses everything provided by RecordRTC.

There is no connection or relationship between MRecordRTC and `streamproc/MediaStreamRecorder`.

### MultiStreamRecorder

`streamproc/MediaStreamRecorder` has its own equivalent of MRecordRTC which is named as [MultiStreamRecorder.js](https://github.com/streamproc/MediaStreamRecorder/blob/master/common/MultiStreamRecorder.js).

**Comment by typec4st** [comment]
Thank you very much for the detailed explanation. At first I didn't get it since they looked similar, but I used both, and yes they are very different. I'm using MultiStreamRecorder for interval based blob recording.

**Comment by muaz-khan** [comment]
Yep, `streamproc/MediaStreamRecorder` is preferred for intervals-based uploading.

You can try this on Firefox:

* https://github.com/streamproc/Record-Entire-Meeting
