### ISSUE TITLE
Firefox - NotSupportedError: Operation is not supported .record()

### ISSUE THREAD

**Issue by andreapaiola** [muaz-khan/RecordRTC#135]
Debugging latest release in Firefox 47.0 on Android 6.0.1

![schermata del 2016-06-11 11 00 39](https://cloud.githubusercontent.com/assets/16450997/15984238/8c8d07ee-2fc4-11e6-80b1-a368548c892f.png)

in Chrome no problems...

**Comment by Rahul-Jagga** [comment]
i think you have update your browser and try it

**Comment by andreapaiola** [comment]
I don't understand: the current version of Firefox on Android is still 47.0

**Comment by DataPartners** [comment]
Firefox 47 desktop also reports similar problem NotSupportedError: Operation is not supported, however Firefox 46 no such error is reported. Firefox 47 detects the error at line 1679 in script RecordRTC.js last updated @ 2016-06-17 9:27:11 AM UTC. 

The code at that location reads;-  
mediaRecorder = new MediaRecorder(mediaStream, recorderHints);

MediaRecorder takes only one parameter being the mediaStream, so if you remove the recorderHints all works fine.

**Comment by dnish** [comment]
@muaz-khan @DataPartners Is it possible that FireFox removed some function? They've deprecated some prefixes.

**Comment by muaz-khan** [comment]
Firefox (Android) seems supporting only audio. You should select "audio" option from RecordRTC-demo dropdown; and it will work.

**Comment by andreapaiola** [comment]
https://simpl.info/mediarecorder/ doesn't work...

**Comment by OndreVo** [comment]
Hi, any progress with this issue? Does it mean that video recording on android won't work?

**Comment by muaz-khan** [comment]
Nope, `video-recording` seems still **NOT** available on Firefox-Android.
