### ISSUE TITLE
Web page crash on post recorded data to server.

### ISSUE THREAD

**Issue by bushev** [muaz-khan/RecordRTC#14]
I use this example to post audio and video data: https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-Nodejs/static/index.html

Everything is OK with 1 - 2 min video&audio.

But when I try to post a ~5 min video&audio with 1280x720 resolution my Chrome page crashes..

Most likely root cause is a very-very long string in post request object? `contents: audio.dataURL`

```
started recording video stream.
canvas resolutions 1280 * 720
video width/height 1280 * 720
started recording audio stream.
sample-rate 44100
buffer-size 16384
Stopped recording video stream.
stopRecording... blob:http%3A//185.22.62.47%3A8080/8471dd12-0013-4881-902b-f7fb9aa2faf7
Stopped recording audio stream.
stopRecording A... blob:http%3A//185.22.62.47%3A8080/4db81dba-b17d-462e-9d8a-e0f922edef58
audio/wav -> 52.9 MB
video/webm -> 104 MB
```

**Comment by unmanner89** [comment]
The same with socket.io

**Comment by muaz-khan** [comment]
Should be fixed now.
