### ISSUE TITLE
Not able to record more than 1 hour

### ISSUE THREAD

**Issue by bonigarcia** [muaz-khan/RecordRTC#144]
Hi there,

I am using RecordRTC as follows:

```
    // 1. To start recording
    var options = {
        type : "video",
        mimeType : isChrome ? null : mimeType,
        disableLogs : false,
        getNativeBlob : true
    }
    var recordRTC = RecordRTC(myStream, options);

    // 2. To save recording to disk
    recordRTC.save();
```

Everything works like a charm, but when my live stream is over 1 hour, the resulting recording file has always a duration of 60 minutes. In other words, I am losing from the minute 60 until the end of my stream. It is too exact to be a coincidence.

Does anyone know what is going on here?

Thank you very much!

**Comment by muaz-khan** [comment]
[MediaStreamRecorder.js](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js) is passing 1-hour maximum recording interval. You can increase this value and recompile RecordRTC.js:

```javascript
mediaRecorder.start(3.6e+6); // default is 60 minutes; enough?
```

PS. Chrome 58-59 may supports 1GB or greater blobs/buffers. Until then, this issue wontfix.
