### ISSUE TITLE
Firefox play recorded webm video with audio only once

### ISSUE THREAD

**Issue by ignl** [muaz-khan/RecordRTC#145]
Problem is reproducible on https://www.webrtc-experiment.com/RecordRTC/. Once you record audio-video with Firefox (47 in my case) and then open new tab video plays fine first time but then hangs on and to play it again browser needs refresh. On my project I tried with another webm sample and it was playing fine, however the one recorded with recordrtc had the same problem. Just in case I tried with all firefox extensions disabled, but result was the same.

**Comment by ignl** [comment]
OK another probably related problem. Files recorded with recordrtc are not "seekable". Again reproducible on https://www.webrtc-experiment.com/RecordRTC/. Record a video and try to play it in new tab. Firefox seeker seems to show a position but does not allow changing it. Chrome does not show position at all and seeker starts to work only on the second play (firefox as mentionet in first post does not play second time). On my project it is the same with recorded webms and with sample "correct" webm it everything works fine. It seems that that there is some problem with recorded file itself.

**Comment by ignl** [comment]
Ok I have checked recorded webm with mkvalidator and here is the warning: WRN800: The segment has Clusters but no Cues section (bad for seeking)

**Comment by ignl** [comment]
OK it seems this is browser bugs as I found issues like these:
https://bugzilla.mozilla.org/show_bug.cgi?id=657791
https://bugzilla.mozilla.org/show_bug.cgi?id=1068001
https://bugs.chromium.org/p/chromium/issues/detail?id=561606

**Comment by ignl** [comment]
This issue is now solved on Firefox 48

**Comment by nicolasxu** [comment]
It is not solved on at all! 57.0.3 (64-bit)
