### ISSUE TITLE
Video has no duration

### ISSUE THREAD

**Issue by reogueone** [muaz-khan/RecordRTC#147]
When I record a video and save it to disk as a webm or mp4 file under chrome or firefox it has no duration attribute.

This makes it difficult to play under VLC or similar media players. You cannot seek a video properly.

What can be done so that the file has a duration. To demonstrate this a video can be taken using this and saved (https://www.webrtc-experiment.com/RecordRTC/)

**Comment by CarpeNecopinum** [comment]
I think this is related to #145 and (if so) is probably caused by a browser bug.
As a (time consuming) workaround you can run it through FFMPEG to repair the files.
At https://www.webrtc-experiment.com/#ffmpeg there are some examples of how to do this inside the Browser even.

**Comment by reogueone** [comment]
Does this happen non your computer with this one: https://www.webrtc-experiment.com/RecordRTC/?

I'm on the latest version of Chrome (v52) and Firefox and its present on both. I figured perhaps it is an issue with the library.

If its isolated to my computer perhaps there's not much to worry about.

**Comment by CarpeNecopinum** [comment]
Unfortunately it appears to be a general issue with both, Firefox and Chrome right now and it occurs on all machines I can test it on.

**Comment by CarpeNecopinum** [comment]
According to @ignl this should now be solved with on Firefox 48, you might want to try it there again.

**Comment by thijstriemstra** [comment]
Some more discussion here: https://github.com/collab-project/videojs-record/issues/31

```
Duration: N/A, start: 0.000000, bitrate: N/A
```
:-1:

**Comment by nicolasxu** [comment]
There is no duration as of today.

**Comment by thijstriemstra** [comment]
As of today?

**Comment by nicolasxu** [comment]
yes, I am using 57.0.3 (64-bit), and it is the same on Chrome.  { nb_streams: 2,
     nb_programs: 0,
     format_name: 'matroska,webm',
     format_long_name: 'Matroska / WebM',
     start_time: '-0.001000',
     duration: 'N/A',
     size: 981330,
     bit_rate: 'N/A',
     probe_score: 100 },

**Comment by vladpoltorin** [comment]
@nicolasxu can you provide part of code you get it?

**Comment by linhe3120** [comment]
how to fix it ?

**Comment by thijstriemstra** [comment]
@linhe3120 

> As a (time consuming) workaround you can run it through FFMPEG to repair the files.

**Comment by imanubhardwaj** [comment]
@nicolasxu [This](https://medium.com/@immanubhardwaj/recordrtc-obtaining-seekable-blob-42d26d2a358d) might help.

**Comment by muaz-khan** [comment]
RecordRTC now exports `getSeekableBlob` : https://recordrtc.org/global.html#getSeekableBlob

Relevant demo: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/seeking-workaround.html

E.g.

```javascript
recorder.stopRecording(function() {
    getSeekableBlob(recorder.getBlob(), function(seekableBlob) {
        video.src = URL.createObjectURL(seekableBlob);
    });
});
```

**Comment by CoreyCole** [comment]
If you are getting the error when using `getSeekableBlob()`:
```
https://www.webrtc-experiment.com/RecordRTC.js 1905:14 Uncaught Error: Please link: https://www.webrtc-experiment.com/EBML.js
```
Make sure to include EBML.js CDN:
```
<script src="https://www.webrtc-experiment.com/EBML.js"></script>
```

**Comment by diveshchakrayat** [comment]
> RecordRTC now exports `getSeekableBlob` : https://recordrtc.org/global.html#getSeekableBlob
> 
> Relevant demo: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/seeking-workaround.html
> 
> E.g.
> 
> ```js
> recorder.stopRecording(function() {
>     getSeekableBlob(recorder.getBlob(), function(seekableBlob) {
>         video.src = URL.createObjectURL(seekableBlob);
>     });
> });
> ```

**Comment by shamseerahammedm** [comment]
@muaz-khan @codeKonami how to add this in react project getting --->
 Uncaught Error: Please link: https://www.webrtc-experiment.com/EBML.js error

**Comment by JimNewaz** [comment]
I'm facing a problem with audio duration length, I have a chrome extension, which works properly but when I download the recorded file it shows 00.00 duration. is there anyone who can solve the bug? Please 
https://github.com/JimNewaz/Record-audio-chrome-extension-

**Comment by priyakloudlearn** [comment]
> RecordRTC now exports `getSeekableBlob` : https://recordrtc.org/global.html#getSeekableBlob
> 
> Relevant demo: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/seeking-workaround.html
> 
> E.g.
> 
> ```js
> recorder.stopRecording(function() {
>     getSeekableBlob(recorder.getBlob(), function(seekableBlob) {
>         video.src = URL.createObjectURL(seekableBlob);
>     });
> });
> ```

Even this code is not helping me to fix the duration issue. End duration is coming only when video plays for the first time.

Im using react js. 
getSeekableBlob(blob, function(seekableBlob) {
          blob = URL.createObjectURL(seekableBlob);
          videoSrc = blob; 
  });

**Comment by oodlesDevAbhishek** [comment]
i'm also facing same problem....pls provide a better sol ..ASAP

**Comment by buynao** [comment]
> RecordRTC now exports `getSeekableBlob` : https://recordrtc.org/global.html#getSeekableBlob
> 
> Relevant demo: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/seeking-workaround.html
> 
> E.g.
> 
> ```js
> recorder.stopRecording(function() {
>     getSeekableBlob(recorder.getBlob(), function(seekableBlob) {
>         video.src = URL.createObjectURL(seekableBlob);
>     });
> });
> ```

This solution has some problems if the video file is larger than 2GB, because it uses arrayBuffer internally, which has a size limit. Based on this, I wrapped `webm-duration-fix`, which uses `blob.stream` to solve the problem of fixing large files and memory usage.

**Comment by MarconLP** [comment]
Here is an example using `fix-webm-duration`

```js
fixWebmDuration(
    recorder.getBlob(),
    duration * 1000,
    (seekableBlob) => {
        console.log(seekableBlob);
    }
);
```
