### ISSUE TITLE
stopRecording calls callback only once

### ISSUE THREAD

**Issue by FunkyloverOne** [muaz-khan/RecordRTC#149]
If I have stopped recording once, starting new one and trying to stop it again the callback is just ignored

**Comment by CarpeNecopinum** [comment]
I noticed a similar issue and found that, as a workaround, you can keep calling stopRecording from a window.setInterval(), until the callback is triggered (which is a horrible hack, but maybe mentioning it helps tracking down the underlying problem).

**Comment by svenstucki** [comment]
I had the same problem, but could work around it by directly using the `MediaStreamRecorder` (check this: https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js#L1600). Just letting you guys know.

So either the bug is in the wrapper or the default `video/webm` recorder is different.

**Comment by FunkyloverOne** [comment]
@muaz-khan has mentioned somewhere (do not remember now) that the recorder currently is for one-time usage only. So when I need to start new recording I'm creating a new recorder, sorry guys I haven't told you earlier.

**Comment by alifyaqhi09** [comment]
can you share the code? or maybe link to issue?

**Comment by FunkyloverOne** [comment]
@alifyaqhi09, if you're asking about this: 

> the recorder currently is for one-time usage only

@muaz-khan mentions that [here](https://github.com/muaz-khan/RecordRTC/issues/163#issuecomment-241195189)
