### ISSUE TITLE
Error while recording screen

### ISSUE THREAD

**Issue by lokesh-mds** [muaz-khan/RecordRTC#15]
Whenever I try to record screen, it says "Multi-capturing of screen is not allowed. Capturing process is denied. Are you enabled flag: "Enable screen capture support in getUserMedia"?"
Could you please help me figure out if I am missing anything?

**Comment by muaz-khan** [comment]
It is [getScreenId](https://github.com/muaz-khan/getScreenId) relevant issue.

* https://github.com/muaz-khan/getScreenId#getscreenid--capture-screen-on-any-domain
