### ISSUE TITLE
RecordRTC MVC Demo, video getting saved without audio

### ISSUE THREAD

**Issue by Sirsendu786** [muaz-khan/RecordRTC#152]
Hi,
am using the RecordRTC MVC Demo sample code, everything works fine and file as well getting saved but after closing the application when I try to play the saved video file only the captured video can be seen but audio is not present. the below code line has no effect at all

```
                       recordAudio.stopRecording(function () {
                            PostBlob(recordAudio.getBlob(), 'audio', fileName + '.webm');
                        });
```

The same can be observed if you try the demo link (https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html) provided in section marked as _Record audio+video in Firefox_. It captured only video but not audio.

Can anyone please help on this. Thank You.

**Comment by ilariut** [comment]
Which player did you use to play the video file? With Firefox48, the audio codec of webm seems to have been changed from vorbis to opus, which on some players comes out as undefined. Directly playing the webm with Firefox 48 or Chrome plays the audio correctly with opus.

**Comment by Sirsendu786** [comment]
@ilariut, That's really strange. yes if I play the saved video file in Firefox or Chrome browser then it works fine both video and audio is coming but when I play it using Windows Media Player (WMP) version 12 in Windows 10 only the video comes but not audio. I did searched in Google and downloaded and installed "WebM" extension for WMP12 but still can't hear any audio.

Is there any restriction that it doesn't play properly in WMP? Do I need to target some specific media player to run it locally? Though it looks fine if I ru it in browser but that's not an option for me.

Please let me know and Thank You for helping me on this.
