### ISSUE TITLE
RecordRTC - Audio cutting out after 3-5 seconds in FF 48

### ISSUE THREAD

**Issue by dkondrat** [muaz-khan/RecordRTC#158]
We are experiencing an issue with Firefox in version 48.

Audio is getting recorded only for first few seconds and then it gets cut off. However video is there for the whole recording. We've tested on about 20 different Windows and Mac machines and same problem occurs on all of them.

We have tested our own application as well as RecordRTC demo page on WebRTC-Experiment.com. Problem occurs in both apps.

We've tried adjusting different parameters on the RecordRTC, however nothing seems to help with the issue.

**Comment by thijstriemstra** [comment]
Can you list all, or some of, the versions of these Mac and Windows machines? Also what recordrtc version etc.

**Comment by asyncrecruiting** [comment]
@thijstriemstra It has fixed itself over time. I think the issue was on a Firefox version and once Firefox released an update it has started to work fine.

**Comment by dkondrat** [comment]
@thijstriemstra It has fixed itself over time. I think the issue was on a Firefox version and once Firefox released an update it has started to work fine.

**Comment by thijstriemstra** [comment]
Ok guess this can be closed then.
