### ISSUE TITLE
Videos/audios recorded by RecordRTC do not go forward or backward when we click on the moving cursor of the playing the particular media .

### ISSUE THREAD

**Issue by Coding-Keeda** [muaz-khan/RecordRTC#159]

**Comment by michelclar** [comment]
I have de same problem, Is there any solution?

**Comment by Coding-Keeda** [comment]
I guess you will be facing this problem while playing videos on Chrome.
You will have to stream video using range header.

**Comment by Coding-Keeda** [comment]
Did it help you?
I have implemented this in C# .
and also I have once processed videos to convert them to web-optimized ones with the help of ffmpeg.

**Comment by muaz-khan** [comment]
Chrome related bug.
