### ISSUE TITLE
Low fps on screen stream

### ISSUE THREAD

**Issue by matheuss** [muaz-khan/RecordRTC#161]
When I'm capturing the screen, the fps never gets better than `8~15`:
<img width="185" alt="screen shot 2016-08-15 at 12 06 03 am" src="https://cloud.githubusercontent.com/assets/4721750/17654670/06ca9d3e-627c-11e6-92a6-d1a20d3abac7.png">

If I choose `video`, to capture the webcam, the fps is perfect (`25~35`).

I'm using https://www.webrtc-experiment.com/RecordRTC. I can also reproduce the same issue on an Electron app.

MacBook Pro retina 13' 
macOS 10.11.6
Chrome 52.0.2743.82
Electron 1.3.3

Any ideas? 😢

**Comment by CodeTheory** [comment]
Also having this issue. 😢

**Comment by muaz-khan** [comment]
[`videoBitsPerSecond`](https://github.com/muaz-khan/RecordRTC#videobitspersecond) and getUserMedia constrains `maxWidth+maxHeight+maxFrameRate` brings a better result.
