### ISSUE TITLE
I'm having problem recording with the demo

### ISSUE THREAD

**Issue by kelvinblade** [muaz-khan/RecordRTC#164]
I'm using chrome 52 on a macbook air. I tried the demo online and locally.

When I stop the video, this is the last thing that is shown on the console:
Stopped recording video stream. RecordRTC.js:100

It is not running the _callback and returning at blob.

Any ideas how I can fix this?

update:
i installed firefox and it works on firefox video + audio.
i tried chrome with just video and it works but with v52, i should be able to get both audio and video right?

**Comment by CarpeNecopinum** [comment]
afaik, with Chrome you currently need to record video and audio separately.

You can use MRecordRTC (https://www.webrtc-experiment.com/RecordRTC/MRecordRTC/) to remove the hassle of having to coordinate the two streams yourself.
For playback use a video and a (hidden) audio tag and wire up the video-tag's events to control the audio tag and keep things synchronous.

If you need a single file with video and audio combined, you can use ffmpeg, either on the server or on the client with ffmpeg-asm.js (https://www.webrtc-experiment.com/ has examples for both).

**Comment by muaz-khan** [comment]
@kelvinblade the last thing it should display is:

```
Stopped recording video stream.
video/webm -> 10 MB
```

Please increase `volume` of the `video` element to make sure that microphone is active/available on Chrome.

PS. You MUST get both audio/video in a single WebM container. It works for me on [Chrome 52.0.2743.116 Mac OSX 10.11.4](https://www.webrtc-experiment.com/DetectRTC/).

**Comment by stewartmegaw** [comment]
CarpeNecopinum was this resolved for you? I'm also not getting the callback in latest Chrome on OSX. Works on Chrome in Ubuntu.

**Comment by muaz-khan** [comment]
Maybe fixed?
