### ISSUE TITLE
Understanding Where and When button.recordRTC.blob is Updated

### ISSUE THREAD

**Issue by daryl3** [muaz-khan/RecordRTC#167]
Hello Everyone,

Thanks in advanced for any help you give me.

I am using Google Chrome as my Browser. In the 'record-audio-plus-video' section, when button.recordRTC is declared, the button.recordRTC.blob is null. At some point, the value changes from null to an object. I have been tracing through the code, and I am having difficulty understanding where it is setup.

Steps I am Following:

1. Open https://github.com/muaz-khan/RecordRTC
2. Select Start Recording
3. Select Stop Recording.

Somewhere after you select the "Start Recording" button, the button.recordRTC.blob changes from null to have a "Blob" object, and I just can't seem to track it down.

Anyone understand where this is happening?

Thanks,

Daryl

**Comment by daryl3** [comment]
I did some more tracing, and found the following:
button.recordRTC = RecordRTC() - From RecordRTC.js
button.recordRTC.initRecorder() Sets up "Recorder" as a Pointer to the MediaStreamRecorder() Class
button.recordRTC.initRecorder() Sets up GLOBAL mediaRecorder as Instantiated Object of MediaStreamRecorder() Class
mediaRecorder.ondataavailable() sets self.blob
mediaRecorder.ondataavailable() -> Calls mediaRecorder.recordingCallback(self.blob) (Passing the Blob)
mediaRecorder.recordingCallback() -> Calls callback(blob) (RecordRTC.stopRecording._callback())

It appears that RecordRTC.stopRecording._callback() now has the blob.

However, I still can't figure out where the RecordRTC.blob ever gets changed. It would seem to me that inside the RecordRTC.stopRecording._callback() would be the spot, but I can't see it happening here.

**Comment by muaz-khan** [comment]
There are two methods to get a recorded `Blob` object:

```javascript
recorder.stopRecording(function() {
    var recordedBlob = recorder.blob; // blob property

    var recorderBlob = recorder.getBlob(); // getBlob method
});
```

[`recordingEndedCallback `](https://github.com/muaz-khan/RecordRTC/blob/master/index.html#L523) is called as soon as RecordRTC is stopped using `stopRecoding` method. E.g.

```javascript
button.recordRTC.stopRecording(function() {
     button.recordingEndedCallback(); // calling inside, here
});

button.recordingEndedCallback = function() {
     var blob = button.recordRTC.blob; // either
     var blob = buttton.recordRTC.getBLob(); // or
};
```

**Comment by daryl3** [comment]
So I finally managed to work my way through it all, and get to the bottom of it.

1. Start the Video.
2. Create the config object.
3. Add the stream to the config, using RecordRTCConfiguration(stream,config);
4. Setup a "Recorder" object: var Recorder = new GetRecorderType();
5. Instantiate the "Recorder" object: mediaRecorder = new Recorder(stream, config);
6. Start Recording: mediaRecorder.record();
7. Stop the Recording: mediaRecorder.stop();
8. mediaRecorder.ondataavailable() is called automatically when mediaRecorder.stop() is called. And it has the Blob object in it.
9. When calling the mediaRecorder.stop() method, you provide it a callback, and the callback has the Blob object in it as the first parameter.
10. At this stage, the data can finally be saved.

So, that is how the Blob object is created. However, the whole reason I was working my way through this was to try and save the data a little bit at a time, before the mediaRecorder.stop() was called.

I would like to save the data (post it to a server) and have the server store the chunks. Once the data is completed, the server can then piece the chunks together into a complete audio/video file for download later.

This would solve a few of problems:
1. If the Browser is closed before the mediaRecorder.stop() method is called, the data will still be available on the server.
2. The client computer does not have to process the entire blob.
3. The client computer does not have to upload the entire large file at the end of the call, instead it was partially uploaded during the conversation.
