### ISSUE TITLE
pause not working

### ISSUE THREAD

**Issue by chessychev** [muaz-khan/RecordRTC#169]
added options for pausing and resuming through
recorder.pauseRecording() and  recorder.resumeRecording(), but when i used them, the video generated contains the whole timespan, including the time between the pause and the resume.
i'm recording through a canvas, and i get the following console messages from your script:
`started recording canvas stream.

Using recorderType: CanvasRecorder

Your browser supports both MediRecorder API and canvas.captureStream!

Passing following config over MediaRecorder API. Object {mimeType: "video/webm"}

Initialized recorderType: CanvasRecorder for output-type: canvas

Paused recording.

Resumed recording.

video/webm -> 951 KB`

**Comment by qandeelabbassi** [comment]
I have the same issue, is there any workaround?

**Comment by muaz-khan** [comment]
**Firefox** related bug.

`CanvasRecorder` was fixed to work on Chrome. You can pause/resume canvas recorders.
