### ISSUE TITLE
encoding with different codec?

### ISSUE THREAD

**Issue by goncabakar** [muaz-khan/RecordRTC#170]
Is it possible to encode video with another codec, in my case VP9?

**Comment by thijstriemstra** [comment]
Yes, here's a list for Chrome: https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

In your case, use mime type `video/webm;codecs=vp9`.

**Comment by muaz-khan** [comment]
`index.html` is updated to support h264, vp8, vp9 and more.
