### ISSUE TITLE
Key-Frames missing on getDataURL()

### ISSUE THREAD

**Issue by FinnFrotscher** [muaz-khan/RecordRTC#172]
```
var vid = RecordRTC(this.state.stream, {
  type: 'video',
  ...
}
//save vid to state
```

after I am done recording I do

```
this.state.vid.getDataURL(upload(data)}) 
```

But when I play the Video, it does not have any `keyframes` and thus, when its played on `chrome`, I can not `seek`. 

My frontend runs react.

**Comment by muaz-khan** [comment]
It is browser-related (Chrome) bug. Firefox works fine though.
