### ISSUE TITLE
RecordRTC  PHP  video file unable to save in uploads folder 

### ISSUE THREAD

**Issue by imranece07** [muaz-khan/RecordRTC#173]
after recording in Firefox the video file is unable to store in uploads folder 
.but can be playback in new tab and can be saved to (save to disk)  these are working fine
but no file is uploaded to the server . it is stopping at progress-end

**Comment by muaz-khan** [comment]
Seems `upload_max_filesize` (php.ini) issue:

* https://github.com/muaz-khan/RecordRTC/wiki/PHP-Upload-Issues
