### ISSUE TITLE
Firefox 48 Sound

### ISSUE THREAD

**Issue by cdanzig** [muaz-khan/RecordRTC#174]
Version 5.4.0 in Firefox 48+ on OSX and Windows:
If you record a video for 120 seconds (or more) the audio cuts out after 30 seconds. We can reproduce this consistently in our app and on your demo page. Any ideas on what might be happening?

**Comment by thijstriemstra** [comment]
What version of Windows and OSX?

**Comment by cdanzig** [comment]
This is an issue that applies to all versions of FF 48 (OS agnostic) and
appears to be a bug in their MediaRecorder class. The temporary workaround
we're using is to record separate streams of audio and video and then
combine them after recording.

**Comment by thijstriemstra** [comment]
Is it fixed in 49?

**Comment by muaz-khan** [comment]
Just tested Firefox 51 using Win10. No audio lagging issues.

**It seems fixed?**
