### ISSUE TITLE
RecordRTC Playback on Audio+Video is broken on Chrome!

### ISSUE THREAD

**Issue by chrisghardwick** [muaz-khan/RecordRTC#177]
Working with Chrome - Version 53.0.2785.116 m (64-bit)

Audio+Video Playback is no longer working on the demo page, or in our application: https://www.webrtc-experiment.com/RecordRTC/

Video is recorded, and blob is correctly created but playback of the recorded video does not happen.

**Comment by chrisghardwick** [comment]
I am using RecordRTC.js - Last time updated: 2016-08-28 3:42:15 AM UTC

**Comment by chrisghardwick** [comment]
@muaz-khan - Hey, can you help with this one?

**Comment by muaz-khan** [comment]
**Maybe fixed.**

PS. Unable to reproduce this bug.
