### ISSUE TITLE
If RecordRTC called from an iframe it doesn't records the full screen

### ISSUE THREAD

**Issue by erickcsh** [muaz-khan/RecordRTC#18]
In order to understand, I have a site and inside of it there is an iframe that loads the RecordRTC file and plays a video. From the iframe I am able to get a reference to the body tag of the outer div. So lets say:

``` <body>
  <div id="container">
    <iframe> 
       <!-- Here are loaded the JS files that record the webpage using RecordRTC -->
```

So basically from the iframe I get a reference to body, and pass it to the builder RecordRTC(stream, options). It records the page but it doesn't records what is inside the iframe tag. Also, it doesn't record the mouse movement.

Original site (the video element is part of the iframe):
![captura de tela 2015-03-25 as 04 07 45 pm](https://cloud.githubusercontent.com/assets/6032548/6836594/316ef67e-d309-11e4-9a25-69451ae82114.png)

Resulting video:
![captura de tela 2015-03-25 as 04 07 55 pm](https://cloud.githubusercontent.com/assets/6032548/6836599/4211594a-d309-11e4-8e1b-e6ce36b51f59.png)

**Comment by muaz-khan** [comment]
It is `getScreenId` issue. Two iframes can NOT interconnect using postMessage API.

You should deploy chrome extension yourself. Your iframe can connect with parent/main window using postMessage API.
