### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by JBerendes** [muaz-khan/RecordRTC#180]
Great work! My issue is far more feature request than bug. Would love to see this working with React Native.

**Comment by sagivo** [comment]
+1

**Comment by a22munir** [comment]
@JBerendes  @sagivo  did either of you getting this working with react web?

**Comment by sagivo** [comment]
@JBerendes this library is not for react-web. for this i'll suggest using other tools like simpleRTC etc..

**Comment by muaz-khan** [comment]
**WontFix?** Closing it for now.
