### ISSUE TITLE
record screen + audio in a single file

### ISSUE THREAD

**Issue by vinaybr** [muaz-khan/RecordRTC#181]
Hi Muaz, 

Is it possible to record screen + audio into a single file?

**Comment by muaz-khan** [comment]
* https://github.com/muaz-khan/Chrome-Extensions/tree/master/screen-recording

Using above extension, go to `options` page and enable the microphone.

### Hints:

1. Capture screen on Chrome or Firefox.
2. Capture audio using a separate getUserMedia request.
3. Use `screenStream.addTrack(audioStream.getAudioTracks()[0])`. Supported both in Chrome and Firefox.
4. Record (the resulting) `screenStream` using RecordRTC and it will record both audio+screen in single WebM.

**Comment by siman** [comment]
@muaz-khan your answer helped me with this: https://github.com/electron/electron/issues/8589
