### ISSUE TITLE
RecordRTC (PHP)video file unable to save in uploads folder .ERROR

### ISSUE THREAD

**Issue by imranece07** [muaz-khan/RecordRTC#184]
REC in Firefox (49) is working but when click to upload it is giving ERROR , Unable to upload

**Comment by muaz-khan** [comment]
This demo still works:

* https://www.webrtc-experiment.com/RecordRTC/PHP/

If you're trying above demo on your own servers:

* https://github.com/muaz-khan/RecordRTC/wiki/PHP-Upload-Issues
