### ISSUE TITLE
support for angular2

### ISSUE THREAD

**Issue by amarewgs** [muaz-khan/RecordRTC#186]
does this support angular2?

**Comment by ShankarSumanth** [comment]
Hi @amarewgs ,
 I know this is kinda pretty late. But I was searching for the same and have created a working repo for this.
https://github.com/ShankarSumanth/Angular2-RecordRTC

**Comment by ShankarSumanth** [comment]
Also Here is an article for the same.  [Integrate RecordRTC With Angular 2](https://medium.com/@SumanthShankar/integrate-recordrtc-with-angular-2-typescript-942c9c4ca93f#.uvf53kwg8)

**Comment by maneeshrao66** [comment]
How I will send the the file to server. I am using below code to send the recorded file but not working.
FormData is showing null after appending in Angular 2.

  public uploadToServer() {
    let blob  = this.recordRTC instanceof Blob ? this.recordRTC : this.recordRTC.blob;
    let fileType = blob.type.split('/')[0] || 'audio';
    let fileName = (Math.random() * 1000).toString().replace('.', '');
    if (fileType === 'audio') {
      fileName += '.' + (!!navigator.mozGetUserMedia ? 'ogg' : 'wav');
    } else {
      fileName += '.webm';
    }
    // create FormData
    var formData: FormData = new FormData();
    formData.append(fileType + '-filename', fileName);
    formData.append(fileType + '-blob', blob);
    this.dashboard.saveRecording(formData).subscribe(
      data => this.saveRecordingSuccess(data),
      error => this.saveRecordingFail(error)
    );
  }

**Comment by amity5020** [comment]
Hii @shankarsumanth does recordRTC works on angular4 i have some issue on importing recordRTC in ts file using angular 4. Pls help me .
