### ISSUE TITLE
Reducing bufferSize to improve latency problems 

### ISSUE THREAD

**Issue by superburrito** [muaz-khan/RecordRTC#189]
Hey everyone, my college friends and I are working on an app which allows users to record a track on top of an existing "base" track on Chrome. For example, someone can record themselves singing on their laptop mic while they listen to a piano piece through their earphones. We're hoping for some guidance on commonly encountered latency issues...

We use the following options:
`const options = {
      mimeType: 'audio/ogg',
      bitsPerSecond: '128000',
      bufferSize: 512, 
      numberOfAudioChannels: 1
    }`

when we call `RecordRTC(stream, options)`. 

As expected, there's a slight latency (~100ms) during recording, so the recorded track doesn't fully sync with the base track. We tried reducing the latency by lowering the bufferSize to 256, but this has somehow caused the recorded track to play **faster** than the base track -- which is really weird, since we typically expect the recorded track to lag behind the base track.  

Any thoughts on why this is happening? Are there other ways to mitigate latency issues? Would really appreciate any help!

**Comment by muaz-khan** [comment]
Current possibilities:

1. You can merge multiple audio tracks using WebAudio API; and get single `destination` stream
2. You can capture all (microphone or non-microphone) audios on a tab using either tabCapture or desktopCapture API; and merge these tracks within microphone using WebAudio API.

E.g.

```javascript
var microphone = captureMicrophoneStream();
var speakersAudioFromAChromeTab = captureUsingTabCaptureAndGetUsingP2POnAddStream();

// merge multiple audio tracks and get single audio track
var singleAudioStream = mergeUsingWebAudio([microphone, speakersAudioFromAChromeTab]);

var recorder = RecordRTC(singleAudioStream, {
    type: 'audio'
});

recorder.startRecording();
```
