### ISSUE TITLE
Crash due to FireFox's multiprocess windows feature AKA Electrolysis(e10s)

### ISSUE THREAD

**Issue by kudlohlavec** [muaz-khan/RecordRTC#191]
Hello everyone,

since version 48 of FireFox, there is feature called Electrolysis that should enable multiprocessing. 
However enabling of this feature (auto-enabled when you have no conflicting addons) causes problem in RecordRTC, namely with mediaRecorder.stop() method - when calling this method or its included method requestData(), the firefox crashes. About 50% of firefox traffic on my website is being affected by this problem (users with some addons should probably have this e10s feature disabled).
Any ideas on how to overcome this problem?

thanks

**Comment by vrajroham** [comment]
@kudlohlavec facing same issue from few days. Even stop() won't cause the error, In mycase there's xhr post() method inside on record complete event. That's the entry point of FF crash. Crash report says that object should be serializable.

**Comment by kudlohlavec** [comment]
Makes sense to me, because demo website (https://www.webrtc-experiment.com/RecordRTC/) works fine on e10s enabled firefox and there should be no XHR calling. However when Im executing the script in my website step by step, it crashes exactly on the mediaRecorder.stop() method that should be called prior to XHR...

**Comment by kudlohlavec** [comment]
After another testing I have to agree that also in my case the problem is really happening in the XHR part. Because of the asynchronous calling I misinterpreted order of the execution steps...

But more important thing - Ive managed to solve the problem. Solution is stated in bug report that I have found on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1264209 (comment 11). You have to fill arrayBuffer with actual blob, create another blob from that arrayBuffer and use this newly created blob in XHR and the problem is gone.

However this is only workarround so please vote for this bug in bugzilla in order to make mozillians to fix this problem ;)

**Comment by vrajroham** [comment]
@kudlohlavec Hope your feedback helps us too. Can you provide your implementation here? But there's problem only in some recent release of RecordRTC. Previously I was using old rel pmease and it was working fine even the multiprocess windows was enabled. Don't know but there's some problem in blob (not sure). If I don't append blob to my xhr request then it works without crash, and when I append blob it crashes. 
If possible please provide your implementation here so future users will get solution with ease, because there will be more users will face same problem.

**Comment by kudlohlavec** [comment]
Its quite simple, you have to do the following with the originalBlob that you are trying to send through XHR:
`var buffer;
var fileReader = new FileReader();
fileReader.onload = function(){
        buffer = this.result;
        var blob2 = new Blob([buffer], {type: "video/webm"});
        makeXMLHttpRequest(!!!USE blob2 here!!!);
}
fileReader.readAsArrayBuffer(originalBlob);
`

**Comment by vrajroham** [comment]
Compairing RecordRTC with old release. I'll try your solution and let you know.

**Comment by vrajroham** [comment]
Thanks @kudlohlavec,
Your solution works well in our case.

**Comment by kudlohlavec** [comment]
Glad to hear it, however major credit goes to Benjamin Smedberg that posted the solution on bugzilla.

Please dont forget to vote for this bug at: https://bugzilla.mozilla.org/show_bug.cgi?id=1264209

**Comment by israelsousa21** [comment]
Amazing guys, I got The same  problema, now I try  to fix it with your  help. Thanx for all. :)

**Comment by israelsousa21** [comment]
Hey guys, Im back here to inform about the new firefox version 50. I have no update my file was in the version 49.2 is not working well, but now, in the new version is work great, some one saw that?

**Comment by vrajroham** [comment]
@israelsousa21 Did you verified is **multiprocess window** enabled or disabled?

**Comment by muaz-khan** [comment]
**Maybe its fixed?**. Closing this issue for now.
