### ISSUE TITLE
Don't want popup message after recording ('Do you want to leave the page')

### ISSUE THREAD

**Issue by manjinderiolcp** [muaz-khan/RecordRTC#193]
Hi Muaz,

I have implemented video recording with MVC demo. Its working fine at my end as well as on server. But I have faced one problem. after recording complete upload on server. When I redirect to another page it ask me 
"Do you want to leave this page" ? Leave/Stay
I don't want to show this popup message, Is there any way to remove this message. when I click on "Stay" or "leave" my other functionality does not work. 

Thanks

**Comment by vrajroham** [comment]
Hey @manjinderiolcp before redirecting to other page call `window.onbeforeunload = null;` or even after completing the recording you can call `window.onbeforeunload = null;`.

It is basically removing the event listener **onbeforeunload** from current window.

**Comment by manjinderiolcp** [comment]
Thanks vrajroham..

**Comment by muaz-khan** [comment]
There is no popup message in the `index.html` demo.

`index.html` demo also supports uploading to both YouTube and PHP servers.
