### ISSUE TITLE
Merging chrome video and audio streams problem

### ISSUE THREAD

**Issue by tezrosolutions** [muaz-khan/RecordRTC#194]
Hi Muaz,

I am trying to run following example on Chrome:

https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC/RecordRTC-to-Nodejs

But FFMPEG is not able to merge the audio and video streams. Due to this the recording never get played on the frontend.

Any solution?

    Umair

**Comment by tezrosolutions** [comment]
Seems like this issue exists on this link too, when you open it in Chrome:

https://www.webrtc-experiment.com/RecordRTC/

**Comment by muaz-khan** [comment]
**Maybe its fixed?** Closing this issue for now.
