### ISSUE TITLE
screen recording into same video when you switch streams

### ISSUE THREAD

**Issue by vinaybr** [muaz-khan/RecordRTC#195]
Hi,

i am using record rtc to record screen of the user, the user switches the region of the screen he is sharing midway which results in a new stream. is it possible to update the stream on record rtc as well to use the new stream so that the end result is a single video?

**Comment by muaz-khan** [comment]
`addStream` method has been added to this section:

* https://github.com/muaz-khan/RecordRTC#record-multiple-videos

Scenarios:

1. You can record up to 4 videos and get single WebM or Mp4
2. You can add additional streams during LIVE recording using `addStream` method

Similar methods are added in [`MediaStreamRecorder.js`](https://github.com/streamproc/MediaStreamRecorder) as well; here is a live demo:

* https://www.webrtc-experiment.com/msr/MultiStreamRecorder.html

You can try "Add Another Video" blue button; which is actually invoking `addStream` method.
