### ISSUE TITLE
Question:  Is there a way to access the blob data on interval during recording?

### ISSUE THREAD

**Issue by erikdonohoo** [muaz-khan/RecordRTC#197]
Currently, I only see a way to get the blob data when a recording has been stopped.  Anyway to get access to it during recording?  With the intention being to upload partial recordings as it goes and have my own server put it together later?  Thanks again for the great library

**Comment by muaz-khan** [comment]
You can use [MediaStreamRecorder.js](https://github.com/streamproc/MediaStreamRecorder):

```javascript
var arrayOfBlobs = [];

var mediaConstraints = {
    audio: true,
    video: true
};

navigator.getUserMedia(mediaConstraints, onMediaSuccess, onMediaError);

function onMediaSuccess(stream) {
    var mediaRecorder = new MediaStreamRecorder(stream);
    mediaRecorder.mimeType = 'video/webm';
    mediaRecorder.ondataavailable = function (blob) {
        arrayOfBlobs.push(blob);
    };
    mediaRecorder.start(1000);

    (function looper() {
        // skip looper if recording has stopped
        if(!mediaRecorder) return;

        var sizeInBytes = new Blob(arrayOfBlobs]).size;
        console.log('Blob size:', bytesToSize(sizeInBytes));

        // check after every 1-second
        setTimeout(looper, 1000);
    })();
}

function onMediaError(e) {
    console.error('media error', e);
}

function bytesToSize(bytes) {
    var k = 1000;
    var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) {
        return '0 Bytes';
    }
    var i = parseInt(Math.floor(Math.log(bytes) / Math.log(k)), 10);
    return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i];
}
```

Use [`mediaRecorder.stop`](https://github.com/streamproc/MediaStreamRecorder#how-to-manually-stop-recordings) method to stop the recording:

```javascript
function stopRecording() {
    mediaRecorder.stop();
    mediaRecorder = null; // MUST set this line to stop "looper"

    setTimeout(function() {
        var file = new File(arrayOfBlobs, 'video.webm', {
            type: 'video/webm'
        });
        window.open(URL.createObjectURL(file));
        uploadToServer(file);
    }, 2 * 1000);
}
```

**Comment by fguillen** [comment]
As I see it,

with this example you will see the `arrayOfBlobs` size constantly growing. And at the end you will upload the whole file at once.

It is not solving the problem of uploading many separate partial videos.

I was trying to find solution to this uploading the actual `arrayOfBlobs` and set it to empty again: 

    arrayOfBlob = [];

But only works for the first partial.. it looks like the first partial has something special I can not reproduce in the rest.
