### ISSUE TITLE
Firefox Recording Blob Chunks are 0 Bytes or Very Small

### ISSUE THREAD

**Issue by daryl3** [muaz-khan/RecordRTC#199]
Most of the computers I have tested with Firefox work just fine. However, one computer has an issue in Firefox. The issue does not happen in Chrome on the same computer.

I modified the RecordRTC.js record interval to be every 5 seconds:
mediaRecorder.start(5000);

I added a Console Log to display the "Blob Chunk" (e.data) every time it is available, ie every 5 seconds:
mediaRecorder.ondataavailable = function(e) {
	console.log('Data Available: ',e.data);
};

On the Computer With the Issue in Firefox:
1st Blob Chunk:  Data Available:  Blob { size: 325, type: "video/webm" }
2nd Blob Chunk: Data Available:  Blob { size: 0, type: "video/webm" }
Other blob Chunk:  Will either be size: 0 or a small amount.
Last Blob Chunk: Data Available:  Blob { size: 78126, type: "video/webm" } (Always larger than 0, but still small. 60K to 70K typically.)

On a computer that works in Firefox (or chrome), I get much larger blob chunks every single time:
1st Blob Chunk:  Data Available:  Blob {size: 646283, type: "video/webm"}
2nd Blob Chunk: Data Available:  Blob {size: 735697, type: "video/webm"}
Other blob Chunk:  Will vary in size between 600K and 1.2 Million.
Last Blob Chunk: Data Available:  Blob {size: 644058, type: "video/webm"} (Varies depending on camera and what is being recorded.)

The Firefox browser with the problem is either 0 or very small.  The interesting part is the first blob is ALWAYS 325. The second blob is always 0. Then other blobs are random amounts. Sometimes 0 and sometimes a number. The last blob is always greater than 0 and around 60k to 70k.

I have tried numerous things on the computer with the problem to try to address the issue. I am not sure what is causing it and was hoping for some input. Here is some of what I have tried:

1. Updated Firefox to current version.
2. Disabled Addons in Firefox.
3. Ran Firefox in Safemode.
4. Refreshed Firefox.
5. Rebooted machine.
6. Turned off machine.
7. Disabled windows firewall.
8. Disabled antivirus software.
9. Disabled user access control.
10. Logged in as another administrative user on the computer.

Thanks in advance!

Daryl

**Comment by muaz-khan** [comment]
[streamproc/MediaStreamRecorder](https://github.com/streamproc/MediaStreamRecorder) should fix this issue because it re-initiates the recorder on each `ondataavailable` event.

* https://github.com/streamproc/MediaStreamRecorder/blob/master/AudioStreamRecorder/MediaRecorderWrapper.js#L122
