### ISSUE TITLE
video and webpage session recording related queries

### ISSUE THREAD

**Issue by abdulaziz86** [muaz-khan/RecordRTC#2]
I am using RecordRTC.js for recording video using webcam and recording web page session, I have some queries related
to each features.

Video recording using webcam:

Query
#1)I am saving the recorded video to the local server using your https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC/RecordRTC-to-ASPNETMVC

   code which is working fine in chrome and opera browsers but not working in firefox as when form data is sent to the server the requested form does not contain
   files so is not save on the server. Is it a known issue? what could be the work around for this issue.?
#2)Is there any way around that i can record video also in intenet explorer and safari?

WebPage Session Recording: 
#1)I am recording webpage session as video on my local server using RecordRTC.js working fine for chrome but not working for firefox 33.1 and internet explorer 10.0

```
.I know that IE and firefox doesnot support webp format , is there any way i can encode blob url into the jpeg format and then into mp4 format?
```
#2) Using the script also slowing down the user experience.What is the reason?
#3) Can I increase the frame rate of the control?

**Comment by muaz-khan** [comment]
CanvasRecorder.js supports only two browsers:

1. Chrome 55+
2. Firefox 40+

WhammyRecorder merely works (ONLY) on Chrome; because Chrome is (currently) the only browser that supports both WebM+WebP encoders.
