### ISSUE TITLE
Write to file in Electron

### ISSUE THREAD

**Issue by nlhkh** [muaz-khan/RecordRTC#200]
I am using `RecordRTC` in Electron environment (mixture of web and node). I want to save a recorded video to file.

I have attempted to save the blob content to file using the `fs` module, but it seems to produce a wrong file, since the file from `save()` has a different size. The file that I created from blob does not play either.

How would you recommend to save a video from RecordRTC object to file?

**Comment by muaz-khan** [comment]
Maybe someone did it here,

* https://github.com/turbographics2000/Electron-MediaStream-Record-Sample/blob/master/win.js#L47

Please use VLC player or Chrome/Firefox browser to play the resulting WebM or Mp4 file.

**Comment by thijstriemstra** [comment]
>  but it seems to produce a wrong file, since the file from save() has a different size.

can you elaborate @nlhkh, hard to interpret without details.

**Comment by muaz-khan** [comment]
Maybe **WontFix**? Closing it for now.
