### ISSUE TITLE
Uploaded Video Files Not Gave Time Line in VLC Player.

### ISSUE THREAD

**Issue by niravjgandhi** [muaz-khan/RecordRTC#202]
I try to video recording using Record RTC. Its Completly Work Fine.
But small issue that i find when i upload video file to server using PHP. 
The Upload is done successfully. But when i play that file in VLC Player Time lines are not display.
Can you explain why this thing happen.
I used same code as you are given in a example to upload file to server using php.

**Comment by vrajroham** [comment]
hey @niravjgandhi, The file recorded would be in webm format. Sometimes webm is just a chunked file without proper encoding (raw video file). It will surely work when you convert it into another format. Try to use ffmpeg for conversion and compression it will solve your issue.

**Comment by thijstriemstra** [comment]
It's a known issue and I think the Chrome team is working on it and adding proper timestamps.
