### ISSUE TITLE
How to record local and remote video?

### ISSUE THREAD

**Issue by liuyang274498** [muaz-khan/RecordRTC#205]
connection.onstream = function(event) {
    var width = parseInt(connection.videosContainer.clientWidth);
    var mediaElement = getMediaElement(event.mediaElement, {
        title: event.userid,
        buttons: ['full'],
	    width: width,
	    showOnMouseEnter: false
});

if(event.type!='local'){
	connection.videosContainer.appendChild(mediaElement);
	
	setTimeout(function() {
		mediaElement.media.play();
	}, 5000);
	
	mediaElement.id = event.streamid;
}
if(event.type=='local'){
	
	sstreamid=event.streamid;
	recorder = RecordRTC(event.stream, {
	    type: 'video',
	    recorderType: MediaStreamRecorder
	});
	
	recorder.startRecording();

	listOfRecorders[event.streamid] = recorder;

}

};

**Comment by muaz-khan** [comment]
Please try MultiStreamRecorder:

* https://github.com/muaz-khan/RecordRTC#record-multiple-videos

Demos:

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/multi-cameras-recording.html
* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/video-plus-screen-recording.html
