### ISSUE TITLE
Record RTC video recording capability

### ISSUE THREAD

**Issue by dinuzhka** [muaz-khan/RecordRTC#206]
I was able to record the audio successfully in RecordRTC. But no video streams. As edge is now open for video recording also

https://blogs.windows.com/msedgedev/2015/05/13/announcing-media-capture-functionality-in-microsoft-edge/#LwsTRW7S2Sd2esYJ.97

Is there anyway to overcome this issue

**Comment by muaz-khan** [comment]
MediaRecorder API are still under consideration:

* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediarecorder/?q=MediaRecorder

WebP is still not planned; so can NOT use WhammyRecorder:

* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webpimageformat/?q=webp

> GifRecorder seems the only available video-recording solution on MSEdge. You will get GIF rather than a WebM video.
