### ISSUE TITLE
RecordRTC demos reject to work with firefox 

### ISSUE THREAD

**Issue by eugen0329** [muaz-khan/RecordRTC#207]
Demo url - **https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html**
Firefox - **50.1.0**
OS - **Ubuntu 16.04.1 LTS**

**Steps:**
1) Open https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html page
2) Click _Record Audio+Video_
3) Click _Share selected devices_ (camera and mic)

**Expected**
Recording begins.

**Got**
Popup with "{}" text and "Ok button"

With Chromium 55.0.2883.87 everything works great.

**Comment by vrajroham** [comment]
Hey @eugen0329,
It's your hardware issue.
Reproduced using same steps given by you and it works fine.
Issue occured (as yours) when I disconnected webcam from computer and run the demo.

Following would help:
While allowing hardware (if there are multiple devices (camera/microphones) then try to select randomly)
Hope it works for you.

**Comment by eugen0329** [comment]
I suppose, the problem was with my Firefox. I have just reinstalled it and everything began to work.
