### ISSUE TITLE
High size of MediaStreamRecorder vs RecordRTC                

### ISSUE THREAD

**Issue by GarvitRajput** [muaz-khan/RecordRTC#208]
I want to push data after each 3 seconds but the size generated by 2 sec of MediaStreamRecorder is equal to 10 sec of RecordRTC

**Comment by muaz-khan** [comment]
Did you refer "MediaStreamRecorder.js"?

* https://github.com/streamproc/MediaStreamRecorder

**Comment by GarvitRajput** [comment]
i used same but size generated is too high
