### ISSUE TITLE
RecordRTC demo shows wrong duration when we click on "Start Recording" button

### ISSUE THREAD

**Issue by apa-narola** [muaz-khan/RecordRTC#209]
Hey Mauz,

It seems you have done great work by proving RecordRTC feature.

BTW, I am using this demo https://www.webrtc-experiment.com/RecordRTC/ , my requirement is Microphone+Audio recording. Everything works fine except i noticed one issue.

Issue is in the mentioned demo link when you click on "Start Recording" button, it starts Audio + Video recording. I noticed it shows wrong video duration. (it is beside play/pause icon). I think it shows total duration of video but not the current recording duration. I need it to be current video duration.

I have attached the screenshot here, Could you please help me to figure it out ?

Looking forward to hear from your reply.
![screenshot from 2017-02-05 10-23-31](https://cloud.githubusercontent.com/assets/5706982/22623907/8ebf18b2-eb90-11e6-98a4-0e8b4782ef2f.png)

Thanks in advance !

PFA

**Comment by muaz-khan** [comment]
> This happens only for LIVE-stream i.e. `MediaStream` object.

#### `Blob` or `File` generates valid duration.

Following snippet works after `stopRecording`:

```javascript
recordingPlayer.currentTime = 5
```

E.g.

```javascript
recorder.stopRecording(function() {
   var blob = recorder.getBlob();
   video.src = URL.createObjectURL(blob);
   video.pause();
   video.currentTime = 5;
   video.play();
});
```

**Comment by apa-narola** [comment]
Hey Mauz,

Thank your for your prompt reply. I appreciate your quick response.

I think you misunderstood me. The you told above i.e. video.currentTime = 5; what it will do is when i click on "Stop Recording" button, it will automatically play a recording video, that video is starting from the set current time. I am not talking about it.

My issue is different, When you click on "Start Recording" button, it still shows video duration in more duration like 221:22, it starts from such weird duration, infact, it should start like 00:00 and then 00:01, 00:02 and so on. This is my issue.

I hope you can understand what i want to say.

Thanks for your assistance.

PFA
![photo_0170380739iemlmq](https://cloud.githubusercontent.com/assets/5706982/22682011/719f66cc-ed36-11e6-9594-8da08cb84d1a.jpg)

**Comment by muaz-khan** [comment]
Sorry. WontFix.

**Comment by sabina-a3logics** [comment]
Hi Muaz,
I'm using audio recorder and when I click on pause button recording paused but when I again resume the recording the time starts with not the paused time but with the added time of pause .

Thanks.

**Comment by durai-optisol** [comment]
readAsArrayBuffer = (blob) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsArrayBuffer(blob);
      reader.onloadend = () => { resolve(reader.result); };
      reader.onerror = (ev) => { reject(ev.error); };
    });
  }

  injectMetadata = blob => {
    const decoder = new Decoder();
    const reader = new Reader();
    reader.logging = false;
    reader.drop_default_duration = false;

    return this.readAsArrayBuffer(blob)
      .then(buffer => {
        const elms = decoder.decode(buffer);
        elms.forEach((elm) => { reader.read(elm); });
        reader.stop();

        const refinedMetadataBuf =
          tools.makeMetadataSeekable(reader.metadatas, reader.duration, reader.cues);
        const body = buffer.slice(reader.metadataSize);

        return new Blob([refinedMetadataBuf, body], { type: blob.type });
      });
  }

// Stop record (getting blob from recordRTC)
recorder.stopRecording(function () {
  
        self.injectMetadata(recorder.getBlob())
          .then(seekableBlob => {
               self.setState({ saveButton: true, recordedBlob: seekableBlob })

          })

This works for me try this
