### ISSUE TITLE
[Crosswalk] Video is lagging / wrong size

### ISSUE THREAD

**Issue by dnish** [muaz-khan/RecordRTC#211]
Hey @muaz-khan,
I'm using RecordRTC within a Cordova Crosswalk application on Android. I'm having 2 issues while recording a single video stream.

1. After creation, the whole video is lagging and everything seems to be recorded on a slow level
2. We recording the video in portrait mode, but after stopping the recording, it is in landscape mode.

Any idea how we could fix both problems? I already tried to set width and height manually, but that didn't work.

**Comment by yayomarin** [comment]
I have the same problem, could you explain what is the form to get the best quality to record in mobile and we have a normal recording velocity, thanks.

**Comment by dnish** [comment]
It seems like we've fixed it in our case. It is a mix of RecordRTC and FFMPEG.

This is our record function on client side:

      recordVideo: function() {

        let video = $("#cameraVideo").get(0); // Video element
        let width = parseInt(video.videoWidth / 1.5); // Reduce the size due to lag issues
        let height = parseInt(video.videoHeight / 1.5);

        this.videoRecord(RecordRTC(this.videoStream(), {bitsPerSecond: 1280000,frameInterval: 1,video:{width,height}, canvas:{width,height}}));
        this.videoRecord().startRecording();
    }

On server side, if you use FFMPEG for de/encoding, you have to set FPS (f.e to 24). If you don't do this, you will get lagging videos (I guess it is a codec issue).

**Comment by yayomarin** [comment]
Hello these are my constrains

`var options = {
        videoBitsPerSecond: 128000,
        mimeType : 'video/webm;codecs=vp8,vp9',
        frameInterval: 30,
        bitsPerSecond: 128000,
        quality: 100
      }

      var optionsAudio = {
        audioBitsPerSecond: 128000,
        sampleRate : 48000,
        mimeType : 'audio/webm',
        bitsPerSecond: 128000
      }`
I use FFMPEG and I have to set 24 FPS and I get slowly recording in mobile, is possible to calculate the best constrains for each device?
Thanks.

**Comment by dnish** [comment]
I guess <code>frameInterval: 30</code> could be the problem, just try to set it to 1.

**Comment by yayomarin** [comment]
Thanks, with this change I have a normal recording, regards.

**Comment by muaz-khan** [comment]
You can try `recorderType:WhammyRecorder`:

* https://github.com/muaz-khan/RecordRTC#recordertype

`frameInterval:1` applies to following recorders:

1. WhammyRecorder
2. CanvasRecorder
3. MultiStreamRecorder
