### ISSUE TITLE
 too many HTTP redirects

### ISSUE THREAD

**Issue by insatmc** [muaz-khan/RecordRTC#215]
When trying to icnlude any JS files with cdn I get an error of  "too many HTTP redirects"
**I just figure out that this problem is only with safari**

    <script src="./bower_components/recordrtc/RecordRTC.js"></script>
    <script src="https://cdn.webrtc-experiment.com/gif-recorder.js"></script>

    <script>
    var options = {
       type: 'gif',
       frameRate: 10,
       quality: 10
    };

    var canvas = document.getElementsByTagName("canvas")[0];
    var recordRTC = RecordRTC(canvas, options);
    function startRecording(){
      recordRTC.startRecording();
    }

    function stopRecording(){
        recordRTC.stopRecording(function(gifURL) {
            console.log({type:"gif", data:gifURL});
      });
    }
    </script>

**Comment by muaz-khan** [comment]
`webrtc-experiment.com` and `cdn.webrtc-experiment.com` both are using same `.htaccess`.

```
RewriteEngine on
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [NE,L,R]

Header set Access-Control-Allow-Origin "*"

RewriteCond %{HTTP_HOST} ^cdn\.webrtc\-experiment\.com$ [OR]
RewriteCond %{HTTP_HOST} ^www\.cdn\.webrtc\-experiment\.com$
RewriteRule ^(.*)$ "https\:\/\/webrtcexperiment\-webrtc\.netdna\-ssl\.com\/$1" [R=301,L]
```

Above rules seems having bugs.

**Comment by muaz-khan** [comment]
Seems fixed now. (tested DetectRTC demo using Safari on iPhone6)
