### ISSUE TITLE
Upload video 

### ISSUE THREAD

**Issue by nizarbechir** [muaz-khan/RecordRTC#216]
thank ou for the nice job super man. 
I want to ask about the upload video to youtube, it doesn't work.
I have tried to host the application in heroku 
here the link : https://fidio.herokuapp.com/

When i try to upload the video to youtube it doesn't work.
could you try it please with the link below ?
here the link : https://fidio.herokuapp.com/

**Comment by muaz-khan** [comment]
Please goto this page, and search for `youtube`:

* https://console.developers.google.com/apis/library?q=youtube&project=

Buy/enable youtube-data-API:

* https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?duration=PT1H&project=

Also set/enable oAuth for your domain:

* https://console.developers.google.com/apis/credentials/consent?project=

Now search for `data-clientid` on the `index.html` demo file:

* https://github.com/muaz-khan/RecordRTC/blob/master/index.html#L184

```html
<span 
      class="g-signin" 
      data-callback="signinCallback" 
      data-clientid="Your_Unique_OAuth_ID_for_YouTube_API_usage" 
      data-cookiepolicy="single_host_origin" 
      data-scope="https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube">
</span>
```

Replace text `Your_Unique_OAuth_ID_for_YouTube_API_usage` with real ID.

**Comment by nizarbechir** [comment]
yes it s done . 
thank you so much it is really helpful for me.
Now i just want to know if i can redirect all saved videos from my website to the same youtube channel, and not every user must sign in and send the you tube video to his personal channel.

Thank you in advance.
Best regards.

**Comment by muaz-khan** [comment]
Sorry @nizarbechir, please check YouTube data-API:

* https://developers.google.com/youtube/v3/docs/
