### ISSUE TITLE
CanvasRecorder pause not working

### ISSUE THREAD

**Issue by qandeelabbassi** [muaz-khan/RecordRTC#217]
I am using recorder.pause() but it doesn't seem to work. Here is my code:
```
var recorder = new CanvasRecorder(canvas, { disableLogs: false });
recorder.record();
```
 after 5 seconds I call `recorder.pause()` and then after another 5 seconds i call `recorder.resume()` but the frames between pause and resume are not discarded they are still there in the final video/blob. When it didn't work i tried calling `recorder.stop` instead of pause and `recorder.record` instead of resume and pushed the blobs in the array. Latter i concatenated the blobs in the array using _ConcatenateBlobs.js_ but the final video was buggy with garbage frames.

Chrome Version: 56.0.2924.87

**Comment by qandeelabbassi** [comment]
I found a solution to this problem and i think some necessary code was missing from CanvasRecorder's pause and resume methods. Below is the code for working pause and resume methods:
```
    /**
     * This method pauses the recording process.
     * @method
     * @memberof CanvasRecorder
     * @example
     * recorder.pause();
     */
    this.pause = function() {
        isPausedRecording = true;
        mediaStreamRecorder.pause(); //added this line
    };

    /**
     * This method resumes the recording process.
     * @method
     * @memberof CanvasRecorder
     * @example
     * recorder.resume();
     */
    this.resume = function() {
        isPausedRecording = false;
        mediaStreamRecorder.resume();//added this line
        if (!isRecording) {
            this.record();
        }
    };
```

**Comment by thijstriemstra** [comment]
@qandeelabbassi can you create a pull request with these changes? cc @muaz-khan

**Comment by muaz-khan** [comment]
Just testing this (need to check for MediaRecorder or Whammy):

```javascript
/**
 * This method pauses the recording process.
 * @method
 * @memberof CanvasRecorder
 * @example
 * recorder.pause();
 */
this.pause = function() {
    isPausedRecording = true;

    if (mediaStreamRecorder instanceof MediaStreamRecorder) {
        mediaStreamRecorder.pause();
        return;
    }
};

/**
 * This method resumes the recording process.
 * @method
 * @memberof CanvasRecorder
 * @example
 * recorder.resume();
 */
this.resume = function() {
    isPausedRecording = false;

    if (mediaStreamRecorder instanceof MediaStreamRecorder) {
        mediaStreamRecorder.resume();
        return;
    }

    if (!isRecording) {
        this.record();
    }
};
```
