### ISSUE TITLE
Embed into app

### ISSUE THREAD

**Issue by a22munir** [muaz-khan/RecordRTC#218]
I can get this to work if I use the instruction, but what I want to do is simply embed the video recording component into an existing file. 

So if I have a index.html file with a set page and there is a div where I want to add this feature of recording video how would I do this using this technology?

Thanks!

**Comment by thijstriemstra** [comment]
ASk on stackoverflow. @muaz-khan this can be closed.

**Comment by muaz-khan** [comment]
@a22munir Please check this video:

* https://youtu.be/YrLzTgdJ-Kg?t=138

Check a few simple demos here:

* https://github.com/muaz-khan/RecordRTC/tree/master/simple-demos
