### ISSUE TITLE
recordRTC.pause is not a function

### ISSUE THREAD

**Issue by a22munir** [muaz-khan/RecordRTC#220]
Hi, I am trying to bind this to react using npm but it is telling me that recordRTC.pauseRecording is not a function, ditto for  recordRTC.stopRecording and recordRTC.save.

My code is: 

`
import React, { Component } from 'react';
import './Record.css';
import 'recordrtc';

class Record extends Component {
  constructor(props){
    super(props);
    this.pauseRec = this.pauseRec.bind(this);
    this.saveRec = this.saveRec.bind(this);
    this.viewRec = this.viewRec.bind(this);
    this.stopRec = this.viewRec.bind(this);
  }
  
  recordRTC = require('recordrtc');

  
  pauseRec(){
    var recordRTC = require('recordrtc');
    recordRTC.pauseRecording();
  }
  
  stopRec(){
    var RecordRTC = require('recordrtc');
    RecordRTC.stopRecording();
  }
    
  saveRec(){
      var RecordRTC = require('recordrtc');
      RecordRTC.save();
  }
    
  viewRec(){
      var RecordRTC = require('recordrtc');
      window.open( RecordRTC.toURL() );
  }

  
  render() {
    var RecordRTC = require('recordrtc');
      function successCallback(stream){
      var vid = document.querySelector('video');
      vid.src = URL.createObjectURL(stream);
      vid.muted = true;
      var recorder = RecordRTC(stream, {
         type: 'video'
      });
      recorder.startRecording();

      setTimeout(function(){
      recorder.stopRecording(function(){
           var blob = recorder.blob;
           console.log(recorder.blob);
           var url = URL.createObjectURL(blob);
           vid.src = url;           
           vid.muted = false;
      });
      }, 5 * 1000, );

    }
    
    function errorCallback(error){
      alert(error);
    }
    
    
    var mediaConstraints = {video: true, audio: true};
    
    
  navigator.mediaDevices.getUserMedia(mediaConstraints).then(successCallback).catch(errorCallback);
    
    return (
      <div>
      <video controls autoPlay id="video">
      </video>
      <br/>
      <div id="buttons">
      <button className="btn btn-warning" onClick={this.pauseRec}>Pause </button>
      <button className="btn btn-danger" onClick={this.pauseRec}>Stop </button>

      <button className="btn btn-primary" onClick={this.saveRec}>Save </button>
      <button className="btn btn-success" onClick={this.viewRec}>View Recording</button>
      </div>
      </div>
    );
  }
}

export default Record;
`

**Comment by muaz-khan** [comment]
Please try this `react.js` demo:

* https://github.com/muaz-khan/RecordRTC#frameworks

`stopRecording` or `pauseRecording` should be used as following:

```javascript
yourRecordRTCInstance.pauseRecording();

yourRecordRTCInstance.resumeRecording();

yourRecordRTCInstance.stopRecording(function() {
    var blob = yourRecordRTCInstance.getBlob();
});
```

`yourRecordRTCInstance` is instance-of `RecordRTC`. i.e.

```javascript
var yourRecordRTCInstance = new RecordRTC(stream, options);

# or
var yourRecordRTCInstance = RecordRTC(stream, options);
```

**Comment by praveenwilson** [comment]
ReferenceError: stream is not defined
