### ISSUE TITLE
Video & audio not working in Microsoft Edge

### ISSUE THREAD

**Issue by nairmahesh** [muaz-khan/RecordRTC#221]
I recorded a video and audio separately and tried playing in Edge browser, got a message in the video section - INVALID SOURCE.

With audio i got the message that THIS AUDIO TYPE IS NOT SUPPORTED.

We are currently saving the Video in both WEBM and MP4 and Audio file in OGG format. How can we play both in EDGE.

**Comment by muaz-khan** [comment]
Microsoft Edge supports **only audio recording**.

```javascript
var recorder = RecordRTC(audioStream, {
   type: 'audio',
   recorderType: StereoAudioRecorder,
   numberOfAudioChannels: 1
});
```

> No video support yet. GifRecorder may (still) work, though.
