### ISSUE TITLE
Use promises

### ISSUE THREAD

**Issue by piuccio** [muaz-khan/RecordRTC#223]
Thanks for the module, amazing, I saw the documentation says [this](https://github.com/muaz-khan/RecordRTC#promises) about promises, however `dev` is excluded from the npm package.

Would be nice to type `import RecordRTC from 'recordrtc/promise'` and have the version using promises

Cheers

**Comment by muaz-khan** [comment]
Latest git-clone supports this:

```javascript
// node test.js
var RecordRTC = require('./RecordRTC.js');
var RecordRTCPromisesHandler = require('./dev/RecordRTC.promises.js');

global.RecordRTC = RecordRTC;

var recorder = new RecordRTCPromisesHandler({}, {
    type: 'video',
    recorderType: RecordRTC.WhammyRecorder
});

recorder.startRecording().then(function() {
    console.log('startRecording success callback');
}).catch(function(error) {
    console.erorr(error);
});
```

**Comment by muaz-khan** [comment]
Closing out of this: https://github.com/muaz-khan/RecordRTC/commit/2240f35fd2cbd6acb0715dc9f778f17ef16346d4
