### ISSUE TITLE
How to sample audio with 16000 or 8000 Hz rate?

### ISSUE THREAD

**Issue by gengshenghong** [muaz-khan/RecordRTC#226]
Hi,

Any idea how to record audio with 16000HZ sample rate? Some other libraries/interfaces requires to use 8000 or 16000 HZ sample rate usually (example: some online speech reorganization API). I've searched around and find below links:
http://stackoverflow.com/questions/28969304/record-audio-on-web-preset-16000hz-16bit/28977136#28977136
http://stackoverflow.com/questions/29900450/recordrtc-with-custom-sample-rate-records-silence

is it possible to implement in the library directly? any reason not to provide them? Any suggestions for best solutions like this?

Thanks very much.

**Comment by gengshenghong** [comment]
I've added the code based on the answer on stackoverflow, the code is almost same as the other library recordjs. As of now, it works as expected. Closing it.

**Comment by muaz-khan** [comment]
Can we merge your solution without affecting the default behavior of StereoAudioRecorder?

i.e. we can read `config` object for `16bit` output e.g.

```javascript
var recorder = new StereoAudioRecorder(stream, {
   get16BitAudio: true
});

// or more versatile to accept multiple values
// default options for "sampleRate" are in between 22050 to 96000
// however we can support "16000" or "8000" according to stackoverflow solution
var recorder = new StereoAudioRecorder(stream, {
   sampleRate: 16000
});
```

**Comment by gengshenghong** [comment]
@muaz-khan ,
Please see https://github.com/muaz-khan/RecordRTC/pull/228 for details, which is the code I am using. It will not affect current behavior if user does not set "desiredSampleRate" option.

Thanks,
Shenghong

**Comment by scm-ns** [comment]
@gengshenghong So to get 8kHz does this piece of code work ? 

```
 var options = 
                {
                    type: "audio",
                    mimeType: "audio/wav",
                    sampleRate: 8000,
                    desiredSampleRate: 8000,
                    recorderType: StereoAudioRecorder,
                    numberOfAudioChannels: 1,
                    ignoreMutedMedia: true
                };
                // create the recordRTC object and store it on the button
                button.recordRTC = RecordRTC(button.stream, options);
```

**Comment by gengshenghong** [comment]
@scm-ns Do not set sampleRate to 8000. Ignore the sampleRate option or set it to correct one (44K usually). The sampleRate is the device sample rate, if it mismatch, recording itself does not work well. desiredSampleRate will re-sample based on recorded results.
Hope it is clear.

Thanks,
Shenghong

**Comment by infinitysiddhu** [comment]
Hi can you please post me working example. I need sample rate 8000hz with 16bit mono audio recording. I tried
              mediaRecorder.stream = stream;
               mediaRecorder.sampleRate=8000;
               mediaRecorder.desiredSampleRate=8000;
               mediaRecorder.recorderType=StereoAudioRecorder;
               mediaRecorder.audioChannels =1;
its not recording. Thank you.

**Comment by gengshenghong** [comment]
@infinitysiddhu Please review the above comments carefully. As mentioned, please ignore "sampleRate" option or set it as correct value (***mention again, sampleRate is the device rate, not software configurable usually***). Below is the code I am using which works of course:

```
RecordRTC(mediaStream, {
        recorderType: StereoAudioRecorder,
        type: 'audio',
        mimeType: 'audio/wav',
        numberOfAudioChannels: 1,
        desiredSampRate: 16000
      });
```

**Comment by night5talker** [comment]
@gengshenghong is it possible to use that RAW sample and using 16khz raw data?
because when I change desiredSampRate: 16000 my audio is in slow motion, any ideas how can I use RAW@16kHz

**Comment by gengshenghong** [comment]
@night5talker Sorry, I am not expert on audio stuff. I've only make the example above works for me, in my case (using StereoAudioRecorder, using audio/wav, 1 channer), setting desiredSampRate does not make the audio slow. I assume you may have something configured differently, please make sure all settings are just same as me and it should work with 16kHz and audio does not change (faster or slower).
