### ISSUE TITLE
Canvas Recording Doesn't Work on Firefox and Safari

### ISSUE THREAD

**Issue by st3wang** [muaz-khan/RecordRTC#23]
I tried the Canvas Recording example on Chrome, Firefox and Safar on both Windows and Mac. It only works on Chrome.
https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/

On Firefox:
The process seems to stop at processInWebWorker around the blob and worker.

On Safari:
I'm getting this error:
[Error] ReferenceError: Can't find variable: atob (blob:https://www.webrtc-experiment.com/d4b761ee-cf0b-4983-a500-796bc9560846, line 317)

**Comment by muaz-khan** [comment]
CanvasRecorder.js now supports Firefox.
