### ISSUE TITLE
Video recording using Webrtc on IOS devices

### ISSUE THREAD

**Issue by nairmahesh** [muaz-khan/RecordRTC#230]
Had a quick doubt,. We are working on a video app which allows users to record live video and audio and send it to others via email.

It works on android and web but not on IOS. But the video recorded and sent to IOS users plays on IOS. Only recording seems to be a problem for us. Can you suggest how we could handle this to male recordings of video possible for IOS users.

**Comment by muaz-khan** [comment]
Because this is currently "seems" not supported in the javascript level (iOS-cordova), that's why closing this thread.

**Comment by chanduthedev** [comment]
Hi Muaz,

Video recording still not supported in IOS devices? Why I am asking this is we are using IOS devices and able to record videos in chrome browser. But video is overlapped. Could you please help on this.

Thanks,

**Comment by brendoni** [comment]
@ nairmahesh did you get your app developed to record video on iOS with Webrtc?
