### ISSUE TITLE
How do you request timeSlice?

### ISSUE THREAD

**Issue by notsoluckycharm** [muaz-khan/RecordRTC#232]
Read through the code, what was the thinking behind removing both RequestData and the timeSlice input parameter? You've got heavy referencing of it in the code and hard coding the time parameter is less than ideal.

Just want to know your thoughts before I try to write it in. Thanks!

**Comment by muaz-khan** [comment]
This one?

```javascript
// void start(optional long mTimeSlice)
// The interval of passing encoded data from EncodedBufferCache to onDataAvailable
// handler. "mTimeSlice < 0" means Session object does not push encoded data to
// onDataAvailable, instead, it passive wait the client side pull encoded data
// by calling requestData API.
mediaRecorder.start(3.6e+6); // default is 60 minutes; enough?
```

Yep, these hints are redundant; and should be removed. These hints explains how `start` method operates internally (on C++ level---by the browser implementation).

Regarding requesting the data, we are using `stop` method instead.

* https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js#L254

```javascript
if (mediaRecorder.state === 'recording') {
    // "stop" method auto invokes "requestData"!
    // mediaRecorder.requestData();
    mediaRecorder.stop();
}
```

Now we get `ondataavailable` event fired, and the resulting blob is passed back to the `stopRecording` callback.
