### ISSUE TITLE
Timestamp of each frame

### ISSUE THREAD

**Issue by br1luca** [muaz-khan/RecordRTC#233]
I need to save the timestamp ( millisecods ) of each frame. ( Also i need only the video not the audio. How its possible with RecordRTC?

This is my code:

```javascript
recordAudio = RecordRTC(stream, {
            frameRate: 30,
            quality: 1,
            onAudioProcessStarted: function() {
                recordVideo.startRecording();
            }
});

recordVideo = RecordRTC(stream, {
            type: 'video'
});

recordAudio.startRecording();`

**Comment by notsoluckycharm** [comment]
The stream you would pass in would have video: true, audio: false, this is not RecordRTC's job. However, RecordRTC does not / can not give you the timestamp per frame as there is no way to inject the ondataavailable callback at this time.

**Comment by muaz-khan** [comment]
To get only video, solution 1:

```javascript
var recorder = RecordRTC(audioVideoStream, {
    type: 'video',
    recorderType: WhammyRecorder
});

recorder.startRecording();
```

Solution 2 (cross-browser):

```javascript
var videoOnlyStream = new MediaStream();
videoOnlyStream.addTrack(audioVideoStream.getVideoTracks()[0]);

var recorder = RecordRTC(videoOnlyStream, {
    type: 'video'
});

recorder.startRecording();
```

To change timeStamp or to get instant ondataavailable events, please modify this file:

* https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js

You can always override individual files:

```html
<script src="RecordRTC.js"></script>

<!--  your modified file goes here -->
<script src="MediaStreamRecorder.js"></script>
```

Now RecordRTC will use your MediaRecorder implementation.

**Comment by br1luca** [comment]
Hi, sorry for the late reply.
I just added this lines of code:

`
        var timestamp = Array();

        // Dispatching OnDataAvailable Handler
        mediaRecorder.ondataavailable = function(e) {

            if (self.dontFireOnDataAvailableEvent) {
                return;
            }

            timestamp.push( new Date().getTime() );
`

So, how i can get the array when i stop the recording session?

**Comment by muaz-khan** [comment]
Modify [MediaStreamRecorder.js](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js); now link this file:

```html
<script src="RecordRTC.js"></script>

<!--  your modified file goes here -->
<script src="MediaStreamRecorder.js"></script>
```

Now use [`getInternalRecorder`](https://github.com/muaz-khan/RecordRTC#getinternalrecorder) in your HTML demo file to access your implementation:

```javascript
var msRecorder = recorder.getInternalRecorder();
msRecorder.onTimeStampUpdate = function(timestamp) {
   console.log(timestamp);
};
var arrayOfTimeStamps = msRecorder.getAllTimeStamps();
```

You can see `onTimeStampUpdate` event as well as `getAllTimeStamps` method. Here is how to define these two in the `MediaStreamRecorder-modified.js`

```javascript
// it is MediaStreamRecorder.js ---- your modified file

// your array
var timestamp = Array();

// Dispatching OnDataAvailable Handler
mediaRecorder.ondataavailable = function(e) {
    if (self.dontFireOnDataAvailableEvent) {
        return;
    }
    var newTimeStamp = new Date().getTime();

    // push new timestamp to the array
    timestamp.push(newTimeStamp);

    // fire your own event
    self.onTimeStampUpdate(newTimeStamp);
};

// your own event
this.onTimeStampUpdate = function(timestamp) {};

// your own method to get array of time stamps
this.getAllTimeStamps = function() {
    return timestamp;
};
```

**Comment by br1luca** [comment]
Sorry, but really i cannot follow you step by step solution Xd
I have this error now:

`javascript
        recordVideo = RecordRTC(stream, {
            frameRate: 30,
            quality: 1,
            type: 'video'
        });

        recordVideo.startRecording();

        var msRecorder = recordVideo.getInternalRecorder();
            msRecorder.onTimeStampUpdate = function(timestamp) {
            console.log(timestamp);
        };
        var arrayOfTimeStamps = msRecorder.getAllTimeStamps();
`

![schermata 2017-04-10 alle 17 00 40](https://cloud.githubusercontent.com/assets/19405688/24868065/41fd4470-1e0f-11e7-851d-393a7ba14389.png)

**Comment by br1luca** [comment]
Ok, i just fixed the error.
But like you said its only fire 1 time.

**Comment by muaz-khan** [comment]
```javascript
var recorder = RecordRTC(stream, {
    type: 'video',
    timeSlice: 1000, // 1 second
    onTimeStamp: function(timestamp, allTimeStamps) {}
});
recorder.startRecording();
```

Or manually get all time-stamps:

```javascript
var msRecorder = recorder.getInternalRecorder();
var allTimeStamps = msRecorder.timestamps;
```

### Hints

`timeSlice` parameter is required to force intervals-based blobs.

Which means that RecordRTC will get blobs based on your timeSlice and concatenate them on stopRecording.

So now `ondataavailable` event fires based on your `timeSlice` parameter.

**Comment by br1luca** [comment]
I just follow your suggestions:
- I override the two individual files: RecordRTC and MediaStreamRecorder
- I just use your lines on code:

```javascript
var recorder = RecordRTC(stream, {
    type: 'video',
    timeSlice: 1000, // 1 second
    onTimeStamp: function(timestamp, allTimeStamps) {}
});
recorder.startRecording();

/**/

var msRecorder = recorder.getInternalRecorder();
var allTimeStamps = msRecorder.timestamps;
console.log( allTimeStamps );

```

But nothing happen, no error no message on console log.
