### ISSUE TITLE
Recording multiple audios reduces the audio qaulity

### ISSUE THREAD

**Issue by indranilatwork** [muaz-khan/RecordRTC#234]
Hi,

I'm trying to multiple audios in a single page using this plugin, but as the number of audios increases to 5-6, the quality of the audio becomes worse.

I've created a dummy plunkr for the issue, please check it. 

https://plnkr.co/edit/uNTRphj1KScTCs6eulZB?p=preview

**Comment by muaz-khan** [comment]
Please try this:

* https://github.com/muaz-khan/RecordRTC#record-multiple-videos

```javascript
var arrayOfStreams = [audio1, audio2, audio3, audio4];

var recordRTC = RecordRTC(arrayOfStreams, {
    mimeType: 'audio/webm',
});

recordRTC.startRecording();
```

**Comment by muaz-khan** [comment]
Lets assume that MultiStreamRecorder's max-limit is 4.
