### ISSUE TITLE
webforms version

### ISSUE THREAD

**Issue by tasoss** [muaz-khan/RecordRTC#235]
Hello and thanks for the software.
I'm trying to use webmethods and webforms but i have no luck.I'm using jquery in order to submit the formdata and i have tried a lot of ways but nothing until now!
Do you have any ideas?
And one second question which is important.As i can see you have a timeslice parameter and i know that a lot of people have written about it.My question is if i can ignore it.I mean that i don't want to use slices just press record,stop recording and then send the file to the web server(iis in my case).
Thanks!

**Comment by muaz-khan** [comment]
RecordRTC do NOT support `timeSlice`. This feature is available on a separate implementation, here:

* https://github.com/streamproc/MediaStreamRecorder

Did you test ASP.NET MVC demo?

* https://github.com/muaz-khan/RecordRTC/tree/master/RecordRTC-to-ASPNETMVC

You've to enable maximum file upload via `web.config` file.

```xml
<configuration>
  <system.web>
    <httpRuntime maxRequestLength="1000000" /> <!-- 1000 MB -->
  </system.web>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="52428800" /> <!--50 MB-->
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```

For more info: http://stackoverflow.com/a/288675/552182

**Comment by tasoss** [comment]
You are correct about the slice.My mistake!
About the other issue.The MVC version works correctly!
I just wanted to make it work on webforms(not mvc) but i'm having issues passing the files in the webmethod.I will try to find a solution and post a reply here in case someone would like to use it.
Thanks again!
