### ISSUE TITLE
echo problem

### ISSUE THREAD

**Issue by niccolomeloni** [muaz-khan/RecordRTC#236]
Hi,

i'm trying to use RecordRTC lib in order to record local stream of a SimpleWebRTC conference from javascript code.

On localStream SimpleWebRTC event i create a RecordRTC object with the stream.
When peers are joined i call startRecording and get the echo problem: i'm working on Ubuntu 16.04 and i can see in sound settings > applications that i have 5 entries for chrome.

If i don't call startRecording i have no echo problem and in sound settings > applications i have only 3 entries.

Does someone get the same problem or do i make something wrong?

Thank you,
Niccolò

**Comment by muaz-khan** [comment]
Still an issue? 

Are you using MultiStreamRecorder ([array-of-streams]) or MediaStreamRecorder(singleStream)?

**Comment by niccolomeloni** [comment]
I create the recorder object with this code: <code>new RecordRTC([stream], { type: 'video', mimeType: 'video/webm' });</code> where <code>stream</code> in arg of callback. Do i make mistake?

Thank you

**Comment by muaz-khan** [comment]
Option 1: Use `RecordRTC.js` from Github (required/recommended):

* https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js

Option 2: Use this code:

```javascript
var recorder = RecordRTC(localStream, {
    type: 'video'
});
```

Otherwise Option 3: Use this instead:

```javascript
var recorder = RecordRTC(localStream, {
    type: 'video',
    timeSlice: 1000
});
```

You can still pass array of streams (Option 4):

```javascript
var recorder = RecordRTC([localStream, remoteStream], {
    type: 'video',
    timeSlice: 1000
});
```

**Comment by niccolomeloni** [comment]
Hi,

the problem was that i was using `[stream]` instead of `stream`. But now, in the recorded video there is no audio. Is it an issue or i have to do something else?

Thanks a lot

**Comment by muaz-khan** [comment]
Are you sure the `stream` has audio tracks?

```javascript
alert(stream.getAudioTracks().length);

stream.getAudioTracks().forEach(function(track) {
    // check for "inactive" or "muted" or "enabled=false"
    console.log(track.enabled, track.muted, track.inactive, track);
});
```

**Comment by niccolomeloni** [comment]
Hi,

i solved by specifying `recorderType: MediaStreamRecorder` in object creation. So i have:
```ruby
recorder = new RecordRTC(stream, {
   type: 'video',
   recorderType: MediaStreamRecorder
});
```

However, the stream had the audio track with `enabled: true`, `muted: false`.
You help was precious :+1:

Thanks a lot and all the best.
