### ISSUE TITLE
Recording problems

### ISSUE THREAD

**Issue by Charliec67** [muaz-khan/RecordRTC#237]
Since last week I have found that the extension claims to be recording, yet when I stop it, a file with 0 bytes is being created. These are for programs and sites that previously have no problem and I've also tried it on skype with the same result. I've reinstalled the extension and had no luck. The only thing different is the updating of Norton anti-virus.

**Comment by Tuizi** [comment]
I have the same issue. I suspect an update of Chrome. Are you using Chrome @Charliec67 ? On Firefox it works well.

**Comment by Tuizi** [comment]
https://www.webrtc-experiment.com/RecordRTC/ Is not working on Chrome for me.

**Comment by kasonjim** [comment]
I am having the same issue now. It was working perfectly fine yesterday, but now it's not working

**Comment by Otsorecruit** [comment]
We could reproduce the bug when we had:
```
      videoRecorder = RecordRTC(videoStream, {
        type: 'video',
        mimeType: 'video/webm;codecs=h264',
```

When we changed `h264` to `vp8` everything started working.

**Comment by muaz-khan** [comment]
This may fix the issue:

```javascript
var recorder = RecordRTC(stream, {
    type: 'video',
    timeSlice: 1000 // add this line
});

recorder.startRecording();
```

**Comment by Charliec67** [comment]
Sorry, I've no idea how to do that?
