### ISSUE TITLE
The video can't see on uploads folder after upload progress-ended

### ISSUE THREAD

**Issue by hoangbienit** [muaz-khan/RecordRTC#240]
Hi,
I am testing record video in the web page. After, upload to server is progress ended I find the video file on uploads folder. However, I can't see it. It work fine in the localhost with wamp, but can't see video file when I test on cloud vps. Please help me.

Thank & kind regards,
Bien

**Comment by muaz-khan** [comment]
Please make sure that you don't have upload-size issues:

* https://github.com/muaz-khan/RecordRTC/wiki/PHP-Upload-Issues

Also make sure that `save.php` has (given) privileges to write to `uploads` directory:

* https://github.com/muaz-khan/RecordRTC/tree/master/RecordRTC-to-PHP/uploads
* https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-PHP/save.php

You can use this to debug PHP:

```php
// via: http://stackoverflow.com/a/21429652
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by hoangbienit** [comment]
Thank Muaz Khan!
I tested with RecordRTC-to-PHP, it worked fine. But, I trying RecordRTC and change the uploads directory, it doesn't work.
In the function uploadToPHPServer, i changed "https://webrtcweb.com/RecordRTC/" to "https://demo.inofthing.com/". Another test, I changed "https://webrtcweb.com/RecordRTC/" to "https://inofthing.com/demo/".
`function uploadToPHPServer(fileName, recordRTC, callback) {
                var blob = recordRTC instanceof Blob ? recordRTC : recordRTC.getBlob();
                
                blob = new File([blob], 'RecordRTC-' + (new Date).toISOString().replace(/:|\./g, '-') + '.' + fileExtension, {
                    type: mimeType
                });

                // create FormData
                var formData = new FormData();
                formData.append('video-filename', fileName);
                formData.append('video-blob', blob);

                callback('Uploading recorded-file to server.');

                makeXMLHttpRequest('https://demo.inofthing.com/', formData, function(progress) {
                    if (progress !== 'upload-ended') {
                        callback(progress);
                        return;
                    }

                    var initialURL = 'https://demo.inofthing.com/uploads/';

                    callback('ended', initialURL + fileName);
                });
            }`
It doesn't work. I can't upload file when select button "upload to php" although the upload finish. I was chmod 777 for index.html and uploads folder.
Please help me, How to fix it?
Thank you & Best regards,
Bien

**Comment by hoangbienit** [comment]
Thank Muaz Khan,
I was fixed it with your help on http://stackoverflow.com/questions/42752157/sending-audio-file-created-with-recordrtc-to-my-server
