### ISSUE TITLE
Support to different file type

### ISSUE THREAD

**Issue by br1luca** [muaz-khan/RecordRTC#254]
At this time its possible save video only in webm.
Its could be possibile save the video in AVI o another format? ( Without compression )

**Comment by muaz-khan** [comment]
AFAIK it is not possible (currently) without using solutions similar to ffmpeg-asm.js (Emscripten). [ref](https://github.com/muaz-khan/Ffmpeg.js)

PS. Currently only two video formats are supported: VP8/VP9 based WebM and H264 based MP4.

h264 may require `chrome://flags/#enable-experimental-web-platform-features` or others.

```javascript
var mp4Recorder = RecordRTC(stream, {
    mimeType: 'video/webm\;codecs=h264'
});

mp4Recorder.startRecording();
```
