### ISSUE TITLE
record is not a function

### ISSUE THREAD

**Issue by hassanshaikley** [muaz-khan/RecordRTC#258]
<script src="https://cdn.webrtc-experiment.com/RecordRTC/CanvasRecorder.js"></script>
	<script src="https://cdn.webrtc-experiment.com/RecordRTC/Whammy.js"></script>
	<script src="https://cdn.webrtc-experiment.com/MediaStreamRecorder.js"> </script>

```
var recorder = new CanvasRecorder(document.getElementById('c'), {
	disableLogs: false
});

recorder.record()
```

gets record is not a function! 

<img width="297" alt="screen shot 2017-05-01 at 10 00 32 pm" src="https://cloud.githubusercontent.com/assets/6746840/25601383/a5ad2ff2-2eb9-11e7-930f-1f3adfd149eb.png">

I am using Chrome (57.0.2987.133 64 bit) on Mac.

Help!

**Comment by billoosijok** [comment]
You are most-likely loading the wrong scripts or in the wrong order!

**Comment by billoosijok** [comment]
I believe this is what you're looking for 
`<script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>`

**Comment by Tuizi** [comment]
@hassanshaikley In your screenshot you do `recorder.record` to see if the function exists, and it's exists but then you make a typo error no? you do `record.record()` instead of `recorder.record()`

**Comment by hassanshaikley** [comment]
@Tuizi Wow. lol
