### ISSUE TITLE
Minified version still failing

### ISSUE THREAD

**Issue by zenix** [muaz-khan/RecordRTC#26]
function (a){postMessage((new FileReaderSync).readAsDataURL(a))}this.onmessage =  function (e) {(e.data);}

**Comment by muaz-khan** [comment]
Are you using this?

```javascript
<script src="https://cdn.webrtc-experiment.com/RecordRTC.min.js"></script>

<!-- or -->
<script src="https://www.webrtc-experiment.com/RecordRTC.min.js"></script>
```

CDN cache is just purged.

**Comment by zenix** [comment]
I'm using  bower w/ master version. Using yeoman angular-fullstack.

**Comment by zenix** [comment]
Tried with minified version from master. Failing also to same error. 

(this time the actual function.name is missing)

**Comment by muaz-khan** [comment]
@noahjerreel Non-minifed version is also NOT working?

* Ref: https://github.com/muaz-khan/WebRTC-Experiment/issues/341#issuecomment-101535565
* https://github.com/cbetta/record-rtc-experiment

**Comment by noahjerreel** [comment]
still not working even the non-minified version @muaz-khan

**Comment by rickyngk** [comment]
Any good news. I've got the same issue with yeoman gulp

**Comment by muaz-khan** [comment]
**Still an issue?** PS. closing this old thread. **You can always reopen.**

**Comment by v88NoahJerreel** [comment]
Thanks @muaz-khan
