### ISSUE TITLE
SampleRate at 16000 with distorted/slow audio

### ISSUE THREAD

**Issue by dfavaro** [muaz-khan/RecordRTC#260]
Hi Muaz,

I have implemented RecordRTC with only audio on Angular 2. I am using Chrome and Firefox. With a sample rate of 16000, an 3 seconds duration audio will be long 8 seconds. With a sample rate of 44000, the audio will be recorded correctly. 

Here is my configuration:

```javascript
this.recordRTC = RecordRTC(audioStream, {
    recorderType: RecordRTC.StereoAudioRecorder,
    type: 'audio',
    mimeType: 'audio/wav',
    numberOfAudioChannels: 1,
    desiredSampRate: 16000,
    sampleRate: 16000
});
this.recordRTC.setRecordingDuration(3000).onRecordingStopped(this.processAudio.bind(this));
this.recordRTC.startRecording();
```

How can i solve it? I need a sample rate of 16000. Thanks.

**Comment by Satys** [comment]
Hi @muaz-khan , I am facing the same issue. Is there any quick work around for this? Thanks.

**Comment by Spatlani** [comment]
+1

**Comment by muaz-khan** [comment]
Please do not set `sampleRate` along with `desiredSampRate`.

Try this demo:

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/16khz-audio-recording.html

```javascript
recorder = RecordRTC(microphone, {
    type: 'audio',
    recorderType: StereoAudioRecorder,
    desiredSampRate: 16000,
    // numberOfAudioChannels: 1 // your choice
});
```

And you will get something like this:

![16khz-audio-recording](https://cloud.githubusercontent.com/assets/477092/26215995/efeb44b8-3c1b-11e7-9a7c-7fe23feb4acd.png)

**Comment by Spatlani** [comment]
I was trying to reduce the size of my recorded audio, I started by reducing the channel to one and then reducing the sample rate. It works fine on 48000 (default)

In my example i'm only using desiredSampleRate
```
 var mediaConstraints = { 
    audio: true ,
    recorderType: StereoAudioRecorder,
    numberOfAudioChannels: 1,
    desiredSampleRate: 16000
}
```
still the sound is recording in slow-mo.

Using Angular v1.6.1 and recordRtc v5.4.1

**Comment by grgrssll** [comment]
I was having this issue too, removed the sampleRate and it works fine with this
`new RecordRTC(stream, {
    type: 'audio',
    mimeType: 'audio/wav',
    recorderType: RecordRTC.StereoAudioRecorder,
    numberOfAudioChannels: 1,
    desiredSampRate: 16000
})`

**Comment by arinhere** [comment]
You can also try this....works perfect

`       type: 'audio',
        numberOfAudioChannels: isEdge ? 1 : 2,
        checkForInactiveTracks: true,
        bufferSize: 16384,
        //bufferSize: 4096,
        recorderType: StereoAudioRecorder,
        desiredSampRate: 22050`

**Comment by ManojIPDeveloperz** [comment]
Hi Muaz,
How can i get HD like video recording using RecordRTC? at present i am passing media stream with video and audio stream objects and options object containing {
                mimeType: 'video/webm',
                disableLogs: true
            }.. do i have to pass any more arguments to get HD like video recording?
