### ISSUE TITLE
Getting raw pcm data from recorded audio

### ISSUE THREAD

**Issue by dfavaro** [muaz-khan/RecordRTC#261]
Can we do it?

**Comment by Satys** [comment]
@dfavaro Did you manage to do this? I have the same need. :)

**Comment by dfavaro** [comment]
@Satys Not yet

**Comment by dfavaro** [comment]
Thank you, i'll try as soon as possible. I'll let you know.

**Comment by Satys** [comment]
@muaz-khan I tried above code and it gives error that,
Uncaught TypeError: Recorder is not a constructor
   at initRecorder (RecordRTC.js:86)
   at Object.startRecording (RecordRTC.js:67)
