### ISSUE TITLE
Make video recording window

### ISSUE THREAD

**Issue by suhomlineugene** [muaz-khan/RecordRTC#262]
Hello. 

I was writing you before , [but](https://github.com/muaz-khan/RecordRTC/issues/252) maybe you didn't understand my  question.

Your sample is working great. But. 

Here [https://www.webrtc-experiment.com/RecordRTC/](url) when I tap start recording video showing in window and when I tap stop, recorded video showing in same window. In  your  ASP.NET MVC sample recorded video is displaying in another container . How I can make same functionality as in link above?

**Comment by muaz-khan** [comment]
It is setting this line during recording:

* [RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml#L162](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-ASPNETMVC/RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml#L162)

and creating a `<video>` element each time you stop the recording.

* [RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml#L126-L141](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-ASPNETMVC/RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml#L126-L141)

## Here is the solution

Replace [this entire code block](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-ASPNETMVC/RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml#L124-L142) with:

```javascript
xhr('/RecordRTC/PostRecordedAudioVideo', formData, progress, percentage, function(fName) {
    // preview in the same <video> element
    preview.src = document.location.origin + '/uploads/' + fName.replace(/"/g, '');
});
```

Now it will use same video container (DOM element) to preview recorded videos.
