### ISSUE TITLE
Crazy framerate for video recorded with Firefox!

### ISSUE THREAD

**Issue by Tuizi** [muaz-khan/RecordRTC#264]
I have an issue when trying to encode a video from Chrome and from Firefox, videos from Firefox took like 300% time more than those from Chrome for the same file size!

So I looked the information returned by ffmpeg and the `tbr` (framerate?) is 16.67 (16.67 tbr) for videos from Chrome but 1000 (1k tbr) for videos from Firefox!!!! It's the only difference between videos from Firefox and Chrome.

Do you know if there is a way to fix that on Firefox?

**Comment by muaz-khan** [comment]
Did you try [bitsPerSecond](https://github.com/muaz-khan/RecordRTC#bitspersecond)?

```javascript
navigator.mediaDevices.getUserMedia({
    audio: true,
    video: {
        frameRate: 30
    }
}).then(function(stream) {
    var recorder = RecordRTC(stream, {
        recorderType: MediaStreamRecorder,
        audioBitsPerSecond: 8 * 1000 * 30,
        videoBitsPerSecond: 8 * 1000 * 100
    });
}).catch(function(error) {});
```

**Comment by Tuizi** [comment]
Even with this setup the video remains a video of 1k fps (information given by ffmpeg 3.2.4)

**Comment by muaz-khan** [comment]
`bitsPerSecond/audioBitsPerSecond/videoBitsPerSecond` didn't seems to (properly/reliably) work in Firefox. (at least in all my local tests)

This issue wontfix until Firefox improves their MediaRecorder implementation.

**Comment by Tuizi** [comment]
Yep it was also my conclusion thank you for giving your feedback :)
