### ISSUE TITLE
Failed to Concatenate Video Blobs

### ISSUE THREAD

**Issue by mir1234** [muaz-khan/RecordRTC#267]
Failing to concatenate using ConcatenateBlobs.js. I am using Uint8Array for concatenate. When I concatenate two or more video blobs it concatenate blobsize is successful but when I play the concatenated video blob it's only play the first recorded video...
My source of concatenateBlobs.js is https://pastebin.com/6iP5sSAf

**Comment by muaz-khan** [comment]
Both [RecordRTC](https://github.com/muaz-khan/RecordRTC) and [MediaStreamRecorder](https://github.com/streamproc/MediaStreamRecorder) can't fix this.

#### Reason

Concatenation seems possible only if we use:

* MediaRecorder API
* Single MediaRecorder instance; and listen to "on-data-available" event
* Concatenate all blobs returned by SINGLE "data-available" event

**According to the spec, blobs returned by "on-dataavailable" (MediaRecorder API) event MUST be concatenate-able.**

```javascript
var arrayOfBlobs = [];
var recorder = new MediaRecorder(audioStream, {
    mimeType: 'audio/webm'
});
recorder.ondataavailable = function(event) {
    arrayOfBlobs.push(event.data);
};
recorder.start(3 * 1000);

btnStopRecording.onclick = function() {
    recorder.stop();
    var singleBlob = new Blob(arrayOfBlobs, {
        type: 'audio/webm'
    });

    // or
    ConcatenateBlobs(arrayOfBlos, 'audio/webm', function(singleBlob) {
        // single blob
    });
};
```

**Each blob returned by "dataavailable" event sets time duration (timecode) based on (according to) the previous blob.**

```
i.e.
1st blobs time duration :     1 to 3 seconds
2nd blobs               :     4 to 6 seconds
                        :     7 to 9 seconds
and so on.
```

You can view EBML data and compare the timecodes for audio tracks.

PS. You must use MediaRecorder API directly instead.
