### ISSUE TITLE
MS Edge no longer recording canvas

### ISSUE THREAD

**Issue by foyleman** [muaz-khan/RecordRTC#270]
I thought this used to work in Edge. But I am now receiving an error that the media source is unavailable.

From the console...

`HTML1300: Navigation occurred.
webpage-recording.html
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
webpage-recording.html (1,1)
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
webgl
Current window: www.webrtc-experiment.com/RecordRTC/Canvas-Recording/webpage-recording.html
This appears to be Edge
gumadapter.js (31,9)
get-user-media error [object MediaStreamError]
webpage-recording.html (226,9)
   "get-user-media error"
   {
      [functions]: ,
      __proto__: { },
      constraintName: null,
      message: null,
      name: "SourceUnavailableError"
   }

started recording canvas stream.
RecordRTC.js (53,13)
Using recorderType: CanvasRecorder
RecordRTC.js (963,9)
Recorder state changed: recording
RecordRTC.js (662,17)
Initialized recorderType: CanvasRecorder for output-type: canvas
RecordRTC.js (93,13)
Stopped recording canvas stream.
RecordRTC.js (119,13)
122/122 frames remaining
...
RecordRTC.js (2961,17)
Generating WebM
RecordRTC.js (2973,13)
Recorder state changed: stopped
RecordRTC.js (662,17)
`

**Comment by muaz-khan** [comment]
Microsoft Edge do not support video-tracks recording yet. WhammyRecorder also not supported out of webp.

In the moment, you can record merely (only) audio tracks (microphone):

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/edge-audio-recording.html

```javascript
recorder = RecordRTC(microphone, {
    type: 'audio',
    recorderType: StereoAudioRecorder, // this line is required for MS-Edge
    // sampleRate: 44100,
    numberOfAudioChannels: 1,
    // bufferSize: 16384
});
```
