### ISSUE TITLE
RecordRTC always saves as type 'video/webm' - Chrome 58.0.3029.110 (64-bit)

### ISSUE THREAD

**Issue by tetreault** [muaz-khan/RecordRTC#272]
Hello, 

Thank you for the library @muaz-khan. I'm using it to try and capture audio client side and will send and save temporarily on my server. 

In my JS I run this in a few pieces ill place below: 
```
  // RecordRTC
  let recordRTC = null;
  const rtcSession = {
    type: 'audio',
    mimeType: 'audio/mpeg',
    audio: true,
    video: false
  };

navigator.getUserMedia(session, (mediaStream) => {
      recordRTC = RecordRTC(mediaStream);
      recordRTC.startRecording();
      // we've started recording so we need to start the timer
      timer = helper.startTimer(multiPurposeText);
      // after X amount of seconds clear the timer interval and stop recording 
      setTimeout(() => {
        helper.clearAndStop(timer, recordRTC);
      }, 6000);
    }, () => {
      console.error('An error has occurred while attempting to get user media.');
    });

// stop recording function & clear timer
 clearAndStop: (timer, recordRTC) => {
    window.clearInterval(timer);
    recordRTC.stopRecording((blob) => {
      const recordRTCBlob = recordRTC.getBlob();
      console.log(recordRTCBlob);
    });
  }
```

It always creates with mimetype 'video/webm' despite setting the session type to 'audio/mpeg' and setting video to false. 

<img width="856" alt="screenshot 2017-06-01 16 58 50" src="https://cloud.githubusercontent.com/assets/5934354/26700541/bba06884-46eb-11e7-9e2c-337056e78247.png">

Am I missing something? Thank you for the assistance. 

If I console log out the session before hand it looks okay, but as soon as RecordRTC starts I see the mimetype changed to video/webm and the type changed to video: 

<img width="863" alt="screenshot 2017-06-01 17 04 09" src="https://cloud.githubusercontent.com/assets/5934354/26700732/79ea7b68-46ec-11e7-8930-6df4aa04a488.png">

I am checking out your FFMPEG library now to see if I can work around the issue by converting it to MP4.

**Comment by muaz-khan** [comment]
RecordRTC requires second parameter named as [`options`](https://github.com/muaz-khan/RecordRTC#options). Please try this:

```javascript
// RecordRTC
var recordRTC = null;

var isMimeTypeSupported = (_mimeType) => {
    // if (webrtcDetectedBrowser === 'edge')  return false;

    if (typeof MediaRecorder.isTypeSupported !== 'function') {
        return true;
    }

    return MediaRecorder.isTypeSupported(_mimeType);
};

var mimeType = 'audio/mpeg';
var recorderType = MediaStreamRecorder;

if(isMimeTypeSupported(mimeType) === false) {
    console.log(mimeType, 'is not supported.');
    mimeType = 'audio/ogg';

    if(isMimeTypeSupported(mimeType) === false) {
        console.log(mimeType, 'is not supported.');
        mimeType = 'audio/webm';

        if(isMimeTypeSupported(mimeType) === false) {
            console.log(mimeType, 'is not supported.');

            // fallback to WebAudio solution
            mimeType = 'audio/wav';
            recorderType = StereoAudioRecorder;
        }
    }
}

const rtcSession = {
    type: 'audio',
    mimeType: mimeType,
    recorderType: recorderType,
    audio: true,
    video: false
};

console.log('final rtcSession object', rtcSession);

navigator.getUserMedia(rtcSession, (mediaStream) => {
    // RecordRTC requires "second" parameter named as "options" or "configuration" or "hints"
    recordRTC = RecordRTC(mediaStream, rtcSession);

    recordRTC.startRecording();

    // after X amount of seconds clear the timer interval and stop recording 
    setTimeout(() => {
        clearAndStop(recordRTC);
    }, 6000);
}, () => {
    console.error('An error has occurred while attempting to get user media.');
});

// stop recording function & clear timer
var clearAndStop = (recordRTC) => {
    recordRTC.stopRecording((blob) => {
        const recordRTCBlob = recordRTC.getBlob();
        console.log(recordRTCBlob);
    });
};
```

**Comment by tetreault** [comment]
thanks for the advice @muaz-khan will try this out right now 👍

**Comment by ShirGrinblat** [comment]
Hey,
Didn't work for me.. i would love your help

**Comment by UsmanKamal** [comment]
@ShirGrinblat @muaz-khan

Did you try changing the recorderType argument? By default it picks MediaStreamRecorder which was causing problem in my case as I only wanted to record Audio and export as 'audio/wav'

`import React, { Component } from 'react'
import { RecordRTC, RecordRTCPromisesHandler, StereoAudioRecorder }  from 'recordrtc'

const hasGetUserMedia = !!(navigator.mediaDevices.getUserMedia || navigator.mediaDevices.webkitGetUserMedia ||
  navigator.mediaDevices.mozGetUserMedia || navigator.mediaDevices.msGetUserMedia);

class RecordRTCComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {

      rtcSession: {
        type: 'audio',
        mimeType: 'audio/wav',
        audio: true,
        recorderType: StereoAudioRecorder
      }

    };

    this.captureUserMedia = this.captureUserMedia.bind(this);

  }

  captureAudio = async () => {

  let stream = await navigator.mediaDevices.getUserMedia(this.state.rtcSession, {audio: true});
  let recorder = new RecordRTCPromisesHandler(stream, this.state.rtcSession);
  recorder.startRecording();

  const sleep = m => new Promise(r => setTimeout(r, m));
  await sleep(3000);

  await recorder.stopRecording();
  let blob = await recorder.getBlob();
  console.log("blob: ", blob)

  }

  componentDidMount() {
    if(!hasGetUserMedia) {
      alert("Your browser cannot stream from your webcam. Please switch to Chrome or Firefox.");
      return;
    }
    this.actualStuff();
  }

}

export default RecordRTCComponent

`
