### ISSUE TITLE
Support Safari 11 (Safari Technology preview 32)

### ISSUE THREAD

**Issue by Tuizi** [muaz-khan/RecordRTC#275]
Safari finally supports WebRTC since... today: https://developer.apple.com/safari/technology-preview/release-notes/

Using **Safari Technology preview 32**, Safari ask for the permission to access the camera but RecordRTC seems to not work well with Safari. Could be good to start supporting it?

**DetectRTC**
Safari Stable: Browser Supports WebRTC (Either 1.0 or 1.1)?	Nope
Safari Technology preview 32: Browser Supports WebRTC (Either 1.0 or 1.1)?	Yep

**Comment by muaz-khan** [comment]
Safari 11 (preview) seems supports following:
1. getUserMedia API
2. WebRTC 1.0 (RTCPeerConnection API)
3. enumerateDevices API (audioinput, videoinput)

No `MediaRecorder` API yet.

WebP encoder/decoder is not supported; that's why we can't use `WhammyRecorder`.

**Comment by Tuizi** [comment]
Alright, so very close. But for sure Safari 11 final will support everything. Good move from Apple, finally :)

**Comment by muaz-khan** [comment]
Yep!

So, currently, same like MS-Edge, RecordRTC supports only `StereoAudioRecorder` on Safari 11.

```javascript
var recorder = RecordRTC(stream, {
    recorderType: StereoAudioRecorder
});
```
