### ISSUE TITLE
Chrome Extension Problem

### ISSUE THREAD

**Issue by ginxx009** [muaz-khan/RecordRTC#276]
I can't get to work it like in the demo here at https://www.webrtc-experiment.com/RecordRTC/

After i click the start recording it'll just turn gray and i need to press the recordrtc extension then it'll work now. So how can i achieve it like on the demo sir muaz?
![a1](https://user-images.githubusercontent.com/28310693/26927400-4e8a4820-4c84-11e7-8fbf-2bea350abc7b.png)

![a2](https://user-images.githubusercontent.com/28310693/26927401-4e9db860-4c84-11e7-875c-c6dcc7382b91.png)

**Comment by muaz-khan** [comment]
# `index.html` demo

RecordRTC demo is name as "index.html" demo:

* https://github.com/muaz-khan/RecordRTC/blob/master/index.html

This demo has its own screen-capturing chrome extension:

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture

> **You must deploy this "desktopCapture" extension for your own domain.**

----

# Standalone Chrome Extension

Screen-recording extension is a standalone plugin; it has no dependencies.

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/screen-recording

Simply deploy (or install) this chrome extension and use it by clicking the extension icon, anytime, from any webpage (HTTP or HTTPs).

----

# Solution for this issue

Deploy following chrome extension (after setting `matches` attribute):

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture

> Make sure that `matches` attribute links to your own domain.

**Now take `index.html` demo, and Audio+Screen or Screen recording options will work on your own domain as well:**

* https://github.com/muaz-khan/RecordRTC/blob/master/index.html

----

# getScreenId (Alternative Solution)

getScreenId is inappropriate to work with `index.html` demo.

* https://github.com/muaz-khan/getScreenId

getScreenId works with following demo:

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/video-plus-screen-recording.html

getScreenId means that you don't need to deploy/publish chrome extension yourself.
