### ISSUE TITLE
Release of camera not working after recording video

### ISSUE THREAD

**Issue by kneeki** [muaz-khan/RecordRTC#280]
After I use RecordRTC the camera will not release. If however, I turn on the camera, and attempt to turn it off again without recording, it works without issue. Here's my 'turnOffCamera' function (I'm using angular). Once again, turning off the camera works fine until I record media. The [demo](https://www.webrtc-experiment.com/RecordRTC/) page allows the user to record video and turn off the camera afterwards. I've tried looking through the code on that page to see what they're doing different, but alas, here I am.

```javascript
    $scope.turnOffCamera = function () {
        // Erase all recorded data
        if (recordRTC) {
            recordRTC.clearRecordedData();
        }

        // If we're recording, stop.
        if ($scope.cameraRecording) {
            $scope.stopVideoRecording();
        }

        // Wipe out the video src
        video.pause();
        video.src = '';

        // !!!!!!!!!!! RELEASE HARDWARE !!!!!!!!!!!

        // Attempt to stop all media tracks
        $scope.localMediaStream.getTracks().forEach(function (track) {
            console.log(track);
            track.stop();
        });

        $scope.localMediaStream = null;

    };
```
Let me know if my `startVideoRecording` or `stopVideoRecording` functions are also needed. I didn't include them because I'm not doing anything out of the bare minimum.

**Comment by muaz-khan** [comment]
RecordRTC writes its own implementation of the `stop` method:

* https://github.com/muaz-khan/RecordRTC/blob/master/dev/Cross-Browser-Declarations.js#L130-L148

```javascript
// override "stop" method for all browsers
MediaStream.prototype.__stop = MediaStream.prototype.stop;
MediaStream.prototype.stop = function() {
    this.getAudioTracks().forEach(function(track) {
        if (!!track.stop) {
            track.stop();
        }
    });

    this.getVideoTracks().forEach(function(track) {
        if (!!track.stop) {
            track.stop();
        }
    });

    if (typeof this.__stop === 'function') {
        // also alling the native "stop" method
        this.__stop();
    }
};
```

`index.html` demo is simply using this:

```javascript
stream.stop(); // using RecordRTC's implementation here
```

**Comment by kneeki** [comment]
I'm very sorry about the delay in response to this. Of course you're correct. After implementing similar code into my application the issue had been resolved. Thanks!
