### ISSUE TITLE
0 byte recording files

### ISSUE THREAD

**Issue by lorensr** [muaz-khan/RecordRTC#281]
This is regarding your great [RecordRTC extension](https://chrome.google.com/webstore/detail/recordrtc/ndcljioonkecdnaaihodjgiliohngojp?hl=en) 😊🙏

A couple of weeks ago it was working for me, but now it has the following behavior:

Record on Default codec: File is 0 bytes
Record on VP8: File is 33 KB
Record on VP9: File is 15 KB

![image](https://user-images.githubusercontent.com/251288/27110808-c9d22b12-5079-11e7-971e-d792bfb35b5b.png)

This is regardless of how long I leave the recording going (eg a minute). I have no idea what could have changed in the past couple weeks. I tried restarting browser, deleting and reinstalling extension, changing which domain I'm recording, and restarting computer. My other settings are:

- Enable microphone recording
- Record the selected tab
- Full HD

When I deselect "Record the selected tab" it works. 

Any ideas on what might be the cause? I tried cloning locally and adding `timeSlice` like you suggested [here](https://github.com/muaz-khan/RecordRTC/issues/237#issuecomment-293597665), but no change.

**Comment by muaz-khan** [comment]
Updated the [chrome-extension](https://github.com/muaz-khan/Chrome-Extensions/tree/master/screen-recording). Please test again.

**Comment by lorensr** [comment]
Hi Muaz, thanks a lot for the quick reply! I updated to 4.2 and restarted Chrome. My settings no longer has "Enable microphone recording" checked. When I record, I still get 0 bytes:

![image](https://user-images.githubusercontent.com/251288/27165786-59d0ff00-5164-11e7-884e-8884dcf3eadf.png)

Which parts of the code would you recommend I look at to further diagnose the issue?

**Comment by muaz-khan** [comment]
0-byte bug is happening too often nowadays; even in RecordRTC main demo (received many error reports):

* https://www.webrtc-experiment.com/RecordRTC/

**Works fine for me on same systems, and same browsers (using same versions/chrome-releases).**

> Unable to reproduce myself, though. **Need help to reproduce this bug.**

**Comment by cdcv** [comment]
Muaz, I am working with Loren on this.  We are needing to get this done quickly if possible.  Open to working with you as a paid consultant if you are interested.  Either way, can you LMK more about what you need to reproduce the bug? I am able to reproduce it on my system (in fact, it's all that is happening on my system).  Perhaps we should screen share and you can have a look?

**Comment by lorensr** [comment]
@muaz-khan have people had the 0-byte bug when using `destopCapture` API, or just `tabCapture`?

**Comment by muaz-khan** [comment]
`index.html` demo now generates an automatic email report on getting `0 bytes` blob:

* https://github.com/muaz-khan/RecordRTC/blob/master/index.html#L1154

Using [main demo](https://www.webrtc-experiment.com/RecordRTC/), open chrome console and paste following:

```javascript
// you will see exact email report
// paste after stopReording
getEmailReport()
```

Here is an email report from a Mac OS X 10_10_5 system:

```sh
RecordRTC seems failed. 

{"fullVersion":"58.0.3029.110","version":58,"name":"Chrome","isPrivateBrowsing":false,"isChrome":true}

Mac OS X 10_12_5 #-------------------- (other systems: Windows 10 + Android 6.0)

mimeType: video/webm #----------------- DEFAULT MediaRecorder usage; NOT forcing vp8 or vp9 or others
recording-media: record-audio-plus-video #---------- both audio+video tracks (NO desktopCapture i.e. NO screen)
media-container-format: default #--------------------- Default codecs (maybe vp8 or vp9 according to browser implementation)
media-resolutions: 640x480 #--------------------- 480p
media-framerates: 24 #---------------------------- 24 frame rates
media-bitrates: default #--------------------------- No "bitsPerSecond" attribute

internal-recorder: MediaStreamRecorder   #----------------------- using MediaRecorder API

recorder-state: stopped #------------ RecordRTC state

# no "timeSlice" here; so using non-timeSlice recording
```

Above report is missing tracks active/mute information. (because stream was stopped before we generated the report)

**Comment by cdcv** [comment]
Muaz, we are needing to get this resolved.  Do you have any further info on what the problem is or how to solve it?  Thanks.

**Comment by cdcv** [comment]
Muaz, I think that we found the problem.  It turns out that the (same) code works as long as there are changes being made in the tab that is being recorded.  If the tab never changes (at all), then the extension does not work properly and may produce the 0 bytes file error.  Hope this is helpful.

**Comment by lorensr** [comment]
Note that "changes being made in the tab" could be an animation, or a playing video, or even a mouse moving around over the tab area.

**Comment by muaz-khan** [comment]
You can pass `ignoreMutedMedia:true` to fix this bug.

```javascript
recorder = RecordRTC(tabCaptureStream, {
   type: 'video',
   ignoreMutedMedia: false // ---- do not ignore muted videos
});
```

**Comment by cdcv** [comment]
Hi Muaz.
	We are using your webRTC code for peer-to-peer videoconferencing.  Thanks!
	I wanted to know how / if we can use the same connection (using RTCMultiConnect) to stream prerecorded video/audio to a peer.
	Here is the use case.
	Normally, if a user calls us, we expect to have an operator to receive their call.
	However, if there is no operator, then we’d like for them to see and hear a pre-recorded video that we stream to them through the webRTC connection (starting at the beginning of the video).
	If an operator becomes available during the video, then we would like to switch to the operator for a peer-to-peer call.
	How can we do this?
	Thanks for your help!


Best,

Christopher

**Comment by muaz-khan** [comment]
Hi Christopher, it should be very easy.

1. Check presence of the user (i.e. agent) using `checkPresence` method
2. If user (i.e. agent) is offline, then load mp3/wav/ogg/etc. from php/any server and play in the background

So we don't need to stream mp3. We can load and play in a loop. So that audio keeps playing until agent comes online.

We can do same thing if agent disconnects the call or keeps the call on hold.

Regards

**Comment by cdcv** [comment]
Thank you very much for your quick reply.
I don’t think it yet solves our problem.
1) When you say play mp3 ‘in the background’, not sure what you mean, or how to do that.
2) We need to do this for video and audio, not just audio.  Will the same technique work?
3) We need to be able to show the video from the beginning or each user that connects (and it’s ok if we assume that there won’t be more than one user connected at a time, so we could restart the video each time someone connects).


Thanks,


CdC

**Comment by muaz-khan** [comment]
Do you want to share pre-recorded video using WebRTC connections? We already [have a similar demo](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/Pre-recorded-Media-Streaming.html). Where we're using `captureStream` API to generate MediaStream object from the pre-recorded or external video file and share using WebRTC peer connections.

Pre-recorded media can be an external video file, a camera's recorded blob, a canvas' animation or anything.

**Comment by pawansingh00** [comment]
@muaz-khan I am facing the same issue in chrome, and iOS when using - RecordRTC

I have attached the screenshot of the log, can you please point me to the right dorection

![Screenshot from 2022-10-13 15-54-54](https://user-images.githubusercontent.com/27332582/195574839-048f780a-907c-4b20-9f89-543b9be6e2db.png)

**Comment by pawansingh00** [comment]
@Locke-bot no luck yet.
