### ISSUE TITLE
Unable to hear Live Video chat audios while recording

### ISSUE THREAD

**Issue by mail2niaz** [muaz-khan/RecordRTC#288]
I am using Jitsi video chat recording to make conference call. This is by default use WebRTC to connect people.

Here i am trying to use your RecordRTC to record the conference call. 
Under options, i chose 2nd i.e Record Selected Tabs Activity and No mic. 
This causes no audio output in Live chat but recorded video contains the audio.

Please advice how to chose your extn properly for this use-case.

**Comment by muaz-khan** [comment]
> This is exactly how [tabCapture API](https://developer.chrome.com/extensions/tabCapture) works. It mutes all audios being played on the selected tab until stream is active (to fix echo issues, maybe).

An alternative option can be, 
1. Use content-scripts to access all video-tags
2. Use captureStream API to capture stream from each video-tag
3. Use MultiStreamRecorder to record all video-tag-streams into single WebM

This option will not disable audios. So you can talk/listen/speak during recording.

**Comment by mail2niaz** [comment]
Thanks & Jazakallahu khairen for your immediate response ! I will check and revert asap..

Workaround fyi .. 
Tab 1 - Live chat (regular user)
Tab 2 - For RecordRTC(mic mute and camera off)

I can still make my call as usual from Tab1 and Tab2 is helping me in recording the conversation.
