### ISSUE TITLE
Feature request (?) – Record RTC from an headless browser or nodejs

### ISSUE THREAD

**Issue by claudioc** [muaz-khan/RecordRTC#289]
My project needs to record the callee and caller streams and I was thinking of using a server-side solution to just "capture" the data stream of the video/audio with the server part acting as a "peer" joining a RTC conversation with the other two parties.

I am not sure this is possible, though.

The other option of course is – obviously – to just record the two videos from one of the two browsers (my application is not "simmetrical": there's an "agent app" and a "customer app") and then send the video/audio to the server for storage. Still feasible (we are also in control of the browsers), but I'd like to know all the options on the table.

Did someone implemented something like this?

**Comment by muaz-khan** [comment]
Please check these demos:

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/multi-cameras-recording.html
* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/video-plus-screen-recording.html

Or the documentation:

* https://github.com/muaz-khan/RecordRTC#record-multiple-videos

```javascript
recorder = RecordRTC([firstUserCamera, secondUserCamera], {
   type: 'video'
});

btnAnyTIme.onclick = function() {
   recorder.addStreams([newUserCamera, anotherNewUserCamera]);
};
```

**Comment by claudioc** [comment]
Thanks :)

I am using RecordRTC in the client now and I will probably stay with this solution.

By the way, amazing work! Been able to merge in one single video 2 video tracks and 2 audio tracks is just awesome :D
