### ISSUE TITLE
Recording fails silently if the microphone is removed. (Chrome and Firefox)

### ISSUE THREAD

**Issue by harshshringi** [muaz-khan/RecordRTC#29]
Hey Muaz, Great work! RecordRTC is a great library which works seamlessly across browsers for recording audio.

There is an important case as listed.
1. We click "Allow" when the browser prompts us for microphone access.
2. Audio recording works fine, except until it fails silently when the microphone is removed either while recording is in progress, or after recording is stopped and we try to record again.

**Comment by muaz-khan** [comment]
Now Chrome stops recording when any of the track is stopped or removed: [StereoAudioRecorder.js#L485-L491](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L485-L491)

```javascript
if (isMediaStreamActive() === false) {
    if (!config.disableLogs) {
        console.error('MediaStream seems stopped.');
    }
    jsAudioNode.disconnect();
    recording = false;
}
```

Same solution can be added in [`MediaStreamRecorder.js`](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js) (inside a timer) to auto-invoke `recorder.stop` as soon as track is disabled or inactive.

**Comment by muaz-khan** [comment]
Maybe fixed. Closing this old thread.
