### ISSUE TITLE
Direct record

### ISSUE THREAD

**Issue by sarahansen223h** [muaz-khan/RecordRTC#30]
Hello dear,

Can i record stream from live url like rtmp, hsl or any kind of live???

if yes can you show me how??? by the way, is there any place a donation can take place?

**Comment by muaz-khan** [comment]
If you're using DASH, and you're playing m3u8 or similar streams in `<video>` element (instead of using Flash player) then you can record the stream in Firefox:

```javascript
var mediaStreamObject = yourLiveVideoPlayer.mozCaptureStream();
var recordRTC = RecordRTC(mediaStreamObject, { type: 'video' } );

// you can even record stream from <canvas> element
var mediaStreamObject = yourCanvasElement.captureStream();
```
