### ISSUE TITLE
Blob size

### ISSUE THREAD

**Issue by SergeyKozlov** [muaz-khan/RecordRTC#301]
How can I limit the size of the video file (blob)?

**Comment by sanpangzi** [comment]
I know to  it can limit the recording time.

**Comment by SergeyKozlov** [comment]
Time should not be limited. How to limit blob size in bytes?

**Comment by muaz-khan** [comment]
Please try this demo:

* https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/preview-blob-size-during-recording.html#L70

Go to line 70 and add following code:

```javascript
(function looper() {
    if (!recorder) {
        return;
    }
    var internal = recorder.getInternalRecorder();
    if (internal && internal.getArrayOfBlobs) {
        var blob = new Blob(internal.getArrayOfBlobs(), {
            type: 'video/webm'
        });

        // -------------------------------------------------------------
        if (blob.size > 100 * 1000) { // if blob is greater than 100 MB
            recorder.stopRecording(callback); // stop recording here
            return;
        }
        // -------------------------------------------------------------

        document.querySelector('h1').innerHTML = 'Recording length: ' + bytesToSize(blob.size);
    }
    setTimeout(looper, 1000);
})();
```

**Comment by SergeyKozlov** [comment]
Many thanks.

Everything works as it should.

My question is why **`timeSlice: 1000`**

And use:
`if (blob.size > 100 * 1000000) { // if blob is greater than 100 MB`

Thank you.

**Comment by sanpangzi** [comment]
ss

**Comment by sanpangzi** [comment]
1M = 1024k, I think it should ` if (blob.size > 100 * 1024) { // if blob is greater than 100 MB`

**Comment by SergeyKozlov** [comment]
Yes

**Comment by qyj19920704** [comment]
> 1M = 1024k, I think it should ` if (blob.size > 100 * 1024) { // if blob is greater than 100 MB`

blob unit is byte
1M=1024KB=1048576byte
so  if (blob.size > 100 * 1048576)
