### ISSUE TITLE
Record Canvas + Audio

### ISSUE THREAD

**Issue by nuthinking** [muaz-khan/RecordRTC#305]
Trying to figure out if it is ultimately possible to record both the canvas with an audio played without using a Chrome extension (ideally working on most browsers).

Codepen [here](https://codepen.io/nuthinking/pen/wqKrXj?editors=0011).

Thanks!

**Comment by muaz-khan** [comment]
Enable this flag on Windows (MacOSX/Linux may not require this):

```
chrome://flags/#enable-experimental-web-platform-features
```

Now use this code to record both Canvas2D and microphone or audio into single container.

```javascript
// first step: use captureStream API
var canvasStream = canvas.captureStream();

// second step: either use captureStream or WebAudio or getUserMedia
var audioStream = getMp3StreamUsingWebAudioAPI();

// last step: merge both audio/video tracks into single MediaStream
var finalStream = new MediaStream();
canvasStream.getVideoTracks().forEach(function(track) {
    finalStream.addTrack(track);
});
audioStream.getAudioTracks().forEach(function(track) {
    finalStream.addTrack(track);
});

// now RecordRTC goes here
// record the resulting single MediaStream that contains both audio+video tracks
recorder = RecordRTC(finalStream, {
    type: 'video'
});
recorder.startRecording();
```

**Comment by nuthinking** [comment]
So this will only work on my Chrome, not other website visitors without flag? Which experimental API should I track to see if it gets adopted by official browsers?

**Comment by nuthinking** [comment]
Even with the flag set, the audio doesn't get recorded (used _audio.captureStream()_).

[new codepen](https://codepen.io/nuthinking/pen/vJNpJo)

**Comment by muaz-khan** [comment]
Demo: https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/Canvas-Animation-Recording-Plus-Micropohe.html

Source: https://github.com/muaz-khan/RecordRTC/blob/master/Canvas-Recording/Canvas-Animation-Recording-Plus-Micropohe.html#L239-L249

**Comment by nuthinking** [comment]
That's great, it also works on Chrome 60 Mac without the Experimental flag set!

Any idea why the audio element doesn't work in my case? Is it because I analyse it also? Thanks a lot!

**Comment by nuthinking** [comment]
Happy to push a demo with my use case, in case you want to add it to the examples.

**Comment by muaz-khan** [comment]
Two new demos:

1. [Canvas + Mp3 recording](https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/Canvas-Animation-Recording-Plus-Mp3.html)
2. [Canvas + Mp3 + Microphone recording](https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/Canvas-Animation-Recording-Plus-Microphone-Plus-Mp3.html)

Source codes here: https://github.com/muaz-khan/RecordRTC/tree/master/Canvas-Recording

**Comment by nuthinking** [comment]
Amazing!

`gainNode.gain.value = 0; // don't play for self`

...really tricked me! ;)

Hopefully it should all work with the sound analyser 🙏

**Comment by nuthinking** [comment]
Like in #285 I am getting very poor quality in Chrome (bitsPerSecond seems to be ignored).

**Comment by nuthinking** [comment]
All went well, [hacked together](https://codepen.io/nuthinking/pen/vJNpJo?editors=0011) the visualization. Than you so much @muaz-khan for the library and for the support!

**Comment by methodbox** [comment]
I'm having the same issue, except I'm trying to capture audio from other participants in a WebRTC video chat session.

I've tried using the video element as the source but it doesn't get any audio. Any tips?

**Comment by kiranparajuli589** [comment]
> I'm having the same issue, except I'm trying to capture audio from other participants in a WebRTC video chat session.
> 
> I've tried using the video element as the source but it doesn't get any audio. Any tips?

Any luck on this @methodbox ?
