### ISSUE TITLE
How does the record file output to mp4 format?

### ISSUE THREAD

**Issue by sanpangzi** [muaz-khan/RecordRTC#308]
Dear Muaz,
         Thank you very much for your work. Now I want to output the recording file 's format is mp4 in order to play on the mobile device. According to your code, my code is as follow:
`
    var recorder; 
    document.getElementById('start').onclick = function() {
        document.getElementById('start').disabled = true;

        navigator.mediaDevices.getUserMedia({
            audio: true
        }).then(function(microphone) {
            var canvasStream = window.canvasElementToBeRecorded.captureStream();
            microphone.getAudioTracks().forEach(function(audioTrack) {
                canvasStream.addTrack(audioTrack);
            });

            var options = {
                recorderType: MediaStreamRecorder,
                mimeType: 'video/mp4'
            };

            // now you can record "canvasStream" which include "microphone" tracks as well
            recorder = RecordRTC(canvasStream,options);

            recorder.startRecording();
        });     

        setTimeout(function() {
             document.getElementById('stop').disabled = false;
        }, 1000); 
    };

    document.getElementById('stop').onclick = function() {
       this.disabled = true;
      
       setTimeout(function() {
            recorder.stopRecording(function() {

                var timestamp = (new Date()).valueOf();
                fileName = timestamp + '.mp4';
               
                invokeSaveAsDialog(this.getBlob(), fileName);

                // var blob = recorder.getBlob();
                // var file = new File([blob], fileName, {
                //     type: 'video/webm'
                // });

                var blob = recorder.getBlob();
                var video = document.createElement('video');
                video.src = URL.createObjectURL(blob);
                video.setAttribute('style', 'height: 100%; position: absolute; top:0; left:0;z-index:9999;width:100%;');
                document.body.appendChild(video);
                video.controls = true;
                video.play();
            });
        }, 100);
    };

`
    
       When I finished the recording and opened  the saved file, it only have audio and no have video, can you help me, Muaz? Thank you very much. Looking forward to your reply.

**Comment by sanpangzi** [comment]
Dear Muaz, I tell you a good news. I use FFMPEG and can transform .webm to .mp4.  Using the .mp4 file, I can play on the mobile phone. Thank you all the same, Muaz.

**Comment by sanpangzi** [comment]
FFmpeg:     http://www.ffmpeg.org/download.html

**Comment by muaz-khan** [comment]
Or this one: https://github.com/muaz-khan/Ffmpeg.js
