### ISSUE TITLE
How to reduce the size of audio files?

### ISSUE THREAD

**Issue by CatPrincess** [muaz-khan/RecordRTC#31]
When I record audio by *Chrome*, the file's size if too big, `1 seconds` is about `200 KB` around.
I want to know, is there any config to make the file's size smaller?

by the way, I use this lib to achieve voice chat. I do not need the high quality audio.

Any suggestion would help me, thanks in advance.

**Comment by philazzi44** [comment]
While not something part of this repo, I had a similar problem and went down the route of creating a PNaCL component that converts the captured .wav audio into an .ogg using libvorbis. That might be an avenue you can use to bring Chrome into a similar file size as Firefox provides natively via the MediaRecorder API.

**Comment by muaz-khan** [comment]
@CatPrincess You can use [`numberOfAudioChannels`](https://github.com/muaz-khan/RecordRTC#numberofaudiochannels) and [`bufferSize`](https://github.com/muaz-khan/RecordRTC#buffersize) to reduce WAV size 3-times of the original:

```javascript
var recrdRTC = RecordRTC(audioStream, {
    numberOfAudioChannels: 1,
    bufferSize: 256
});
```

Buffer-size lower-values may decrease the audio quality however `numberOfAudioChannels` will still affect and force generating half of the original WAV.

**Comment by muaz-khan** [comment]
There is an alternative ffmpeg-based solution as well:

* [https://github.com/muaz-khan/Ffmpeg.js/blob/master/wav-to-ogg.html](https://github.com/muaz-khan/Ffmpeg.js/blob/master/wav-to-ogg.html)

BTW, there is [`audioconverter.js`](https://github.com/sopel39/audioconverter.js) as well which is having 2MB minified file-size, I guess. There are many alternative solutions as well, e.g. [http://stackoverflow.com/a/26245260/552182](http://stackoverflow.com/a/26245260/552182)
