### ISSUE TITLE
Please invoke getUserMedia only once

### ISSUE THREAD

**Issue by paul-mesnilgrente** [muaz-khan/RecordRTC#312]
Hi,

I am using the last Firefox on Ubuntu 16.04. My aim is to do a camera selector, display the stream and finally record it in a webm file when clicking on a button and finish at the end of a timer.

The recording is working but I have a problem with the stream selection. I must misunderstand how DetectRTC is working. When I execute only this simple code without anything else:

```javascript
DetectRTC.load(function () {
  DetectRTC.videoInputDevices.forEach(function (device, idx) {
    console.log(device.label);
  });
});
```

My javascripts are this:

- `https://cdn.WebRTC-Experiment.com/RecordRTC.js`
- `https://cdn.webrtc-experiment.com/DetectRTC.js`
- `https://cdn.webrtc-experiment.com/gumadapter.js`

The console is printing me only "Please invoke getUserMedia only once" but I never called it and I haven't even be prompted to accept the camera on the page (the id is the good one). Is it a bug or am I doing something wrong?

Thank you very much, the API is amazing :)

**Comment by muaz-khan** [comment]
DetectRTC demo [has this snippet](https://github.com/muaz-khan/DetectRTC/blob/master/index.html#L346-L378):

```javascript
if (DetectRTC.MediaDevices[0] && DetectRTC.MediaDevices[0].label === 'Please invoke getUserMedia once.') {
    navigator.mediaDevices.getUserMedia({
        audio: true,
        video: true
    }).then(function(stream) {
        var video;
        try {
            video = document.createElement('video');
            video.muted = true;
            video.src = URL.createObjectURL(stream);
            video.style.display = 'none';
            (document.body || document.documentElement).appendChild(vide);
        } catch (e) {}

        DetectRTC.load(function() {
            DetectRTC.videoInputDevices.forEach(function(device, idx) {
                // ------------------------------
                // now you get valid label here
                console.log(device.label);
                // ------------------------------
            });

            // release camera
            stream.getTracks().forEach(function(track) {
                track.stop();
            });

            if (video && video.parentNode) {
                video.parentNode.removeChild(video);
            }
        });
    });
} else {
    DetectRTC.videoInputDevices.forEach(function(device, idx) {
        console.log(device.label);
    });
}
```
