### ISSUE TITLE
Screen capture in Chrome

### ISSUE THREAD

**Issue by Sketchypop** [muaz-khan/RecordRTC#313]
Hello Muaz khan, Your work is absolutely great. Can you please guide how we can enable screen capture and record in google chrome. It works like a charm in firefox.
thanks

**Comment by muaz-khan** [comment]
Please check this: http://www.muazkhan.com/2017/08/write-screen-sharing-application-for.html

(After setup & installation) Now you can use this library to capture screen:

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/Screen-Capturing.js

If you don't want to setup & deploy your own extension: https://github.com/muaz-khan/getScreenId

**Comment by Dhanashri04** [comment]
how can we record full webpage and not just remote video? please help
