### ISSUE TITLE
configuration of server

### ISSUE THREAD

**Issue by jigneshaussizz** [muaz-khan/RecordRTC#316]
Hi muaz,
   I am facing problem to set up server.
i want to give socketURL like https://domain.com:90 for video streaming in my application.
i installed rtcmulticonnection-v3 in my system32 folder and change port to 90 or 443 i nserver.js file.
and then i uploaded a webiste in IIS with SSL and then i start server with command "node server.js"
but it is not started so please help me how to configure server using rtcmulticonnection
And can you please give me you email id so i can send you screen shot of my server configuration?
help me please to set up server

**Comment by muaz-khan** [comment]
Please open issue here: https://github.com/muaz-khan/RTCMultiConnection/issues
