### ISSUE TITLE
Can't stop audio stream

### ISSUE THREAD

**Issue by lazyexpert** [muaz-khan/RecordRTC#32]
Hi, running an issue with stopping an audio stream. 
Two questions: 
- where correctly to capture it; 
- how to stop;

For while I do capture localStream and stop it. This stops video recording, but not audio.

Thanks for any help.

Forgot to mention, I'm trying to adapt https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC/PHP-and-FFmpeg. 
I'm recording both audio and video, streaming them and sending save on server.

**Comment by muaz-khan** [comment]
1. Capture device using getUserMedia
2. Call [`recordRTC.startRecording`](http://recordrtc.org/RecordRTC.html#startRecording) in the getUserMedia success_callback
3. Call [`recordRTC.stopRecording`](http://recordrtc.org/RecordRTC.html#stopRecording) and pass success_callback as the only function over this method. In the success_callback, call `mediaStream.stop()`

If you're recording audio/video separately/parallel:

1. Capture device using getUserMedia
2. Call [`recordRTC1.startRecording`](http://recordrtc.org/RecordRTC.html#startRecording) and [`recordRTC2.startRecording`](http://recordrtc.org/RecordRTC.html#startRecording) in the getUserMedia success_callback
3. Call [`recordRTC1.stopRecording`](http://recordrtc.org/RecordRTC.html#stopRecording) then call [`recordRTC2.stopRecording`](http://recordrtc.org/RecordRTC.html#stopRecording). In their success_callback, call `mediaStream.stop()`

E.g.

```javascript
var recordRTC1, recordRTC2, mediaStream;
navigator.webkitGetUserMedia({
    audio: true,
    video: true
}, function(stream) {
    mediaStream = stream;

    recordRTC1 = RecordRTC(mediaStream, {
        type: 'audio'
    });

    recordRTC2 = RecordRTC(mediaStream, {
        type: 'video'
    });

    recordRTC1.startRecording();
    recordRTC2.startRecording();
}, function(error) {});

btnStopRecording.onclick = function() {
    recordRTC1.stopRecording(function(audioURL) {
        recordRTC2.stopRecording(function(videoURL) {
            mediaStream.stop(); // Release Camera/Microphone
            Upload_Blobs_to_PHPServer(recordRTC1.blob, recordRTC2.blob);
        });
    });
};
```

**Comment by lazyexpert** [comment]
Thanks for your advice, but looks that i'm doing this already, and yet no profit.

I've tried mediaStream.stop() - this stops my video recording process. And looks like camera is released.
But I still can't hear audio and capture it once more.
I have also tried mediaStream.getAudioTracks()[0].stop() - but, unfortunatelly..

getUserMedia - gives access to your media, and I wish to releaseMyMedia.

**Comment by lazyexpert** [comment]
I've figured.. so stupid..

I've added on record.stop 2 lines:
window.stream = undefined;
preview.muted = false;
