### ISSUE TITLE
How to save the video within javascript

### ISSUE THREAD

**Issue by daicoolb** [muaz-khan/RecordRTC#327]
If I have got the stream. How can I save the video into the local disk or some place which I can control.

Can anbody help me ?

Thanks.

**Comment by xavicolomer** [comment]
Create recorder and start recording:
```
recordRTC = RecordRTC(this.stream, options);
recordRTC.startRecording();
```

Stop Recording and Save:
```
recordRTC.stopRecording(() => {
    recordRTC.save('./video.webm');
});
```

**Comment by daicoolb** [comment]
Thanks a lot
