### ISSUE TITLE
Add destroy method

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#332]
When I destroy my plugin that uses RecordRTC, it prints this to the console:

```
Unable to stop the recording. Recording state:  stopped
```

I couldn't find a proper destroy method, is it possible to add one that (at minimum) stops the recording process?

I need one that is not async..

**Comment by muaz-khan** [comment]
As a quick workaround, you can try this:

```javascript
recorder.state = 'recording';
recorder.stopRecording(function() {
    //
});
```

BTW, I'll add `destroy` method in the next commit, soon.

**Comment by thijstriemstra** [comment]
Thanks for the quick reply. Also add it to `MRecordRTC` while you're at it ;)

**Comment by thijstriemstra** [comment]
thanks, seems to work fine. A new npm release and I'm good to go.
