### ISSUE TITLE
timeSlice option doesn't work with StereoAudioRecorder

### ISSUE THREAD

**Issue by osukono** [muaz-khan/RecordRTC#337]
I am trying to record audio with RecotdRTC and it's important that I get audio in small pieces.
In your demo you show how to use timeSlice parameter along with ondataavailable function while video is being recorded and it works well, but when I switch to StereoAudioRecorder the ondataavailable function is never called.

**Comment by muaz-khan** [comment]
Commit: https://github.com/muaz-khan/RecordRTC/commit/ab6300aad251f71cf5988b5e5eca17f37b991e64

Please check:

```
simple-demos/ondataavailable-StereoAudioRecorder.html
```

**Comment by jdavidbakr** [comment]
Is there a reason that the overriding of StereoAudioRecorder is necessary instead of just making those adjustments to the master file?  It seems silly that the solution is to basically copy the package into my local javascript just because there are a few lines missing.

**Comment by osukono** [comment]
Thank you very much. It works.
