### ISSUE TITLE
Firefox NotReadableError

### ISSUE THREAD

**Issue by mathiassamyn** [muaz-khan/RecordRTC#338]
I am trying to test the [audio-recording demo](https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/audio-recording.html) in my Firefox browser. 

After I click start recording, it will ask to use my microphone, which I allow. After doing this, I get a pop up that says the following: Unable to capture your microphone. Please check console logs.

When I check the console log I see the following error:
MediaStreamError { name: "NotReadableError", message: "Failed to allocate audiosource", constraint: "", stack: "" }

How can I make this work in Firefox, as it works just fine in chrome?

**Comment by osukono** [comment]
It doesn't solve your problem but this part `.catch(function(error)` is a little bit confusing, because when you get any exception in `callback` function you will see "Unable to capture your microphone. Please check console logs." message.
