### ISSUE TITLE
Clear() method seems to be missing 

### ISSUE THREAD

**Issue by dipaktelangre** [muaz-khan/RecordRTC#34]
I want to clear the recorded blob object after some interval so I can upload chuck of blob to server, and  record another chunk of blob instead of posting completed large file. 

While recording, after 2 min of video I am getting array memory out of exception. So to solve that I thought to record the video in chunks and upload that to server in real time and merge that again at server using FFMPEG. So that save blob chunk, I need Clear() method as similar in RecordJs clear() method. I tried to add this method into RecordRTC library byt setting blob to null but it not solve the issue. 

Please help to solve this !

**Comment by muaz-khan** [comment]
RecordRTC is now having [`clearRecordedData`](https://github.com/muaz-khan/RecordRTC#clearrecordeddata) method:

```javascript
recorder.clearRecordedData();
```

I'll strongly suggest using this alternative solution instead:

* [https://github.com/streamproc/Record-Entire-Meeting](https://github.com/streamproc/Record-Entire-Meeting)

**Comment by dipaktelangre** [comment]
Really thanks, Will check and revert back to you !

[image: TCS] <http://www.2zerozero.com>
Dipak Telangre  | Web Developer @ Netwin ; Co-Founder @ 2zerozero.com
Netwin | Gangapur Road, Nashik- 422001
Tel: | Mob: 9970056608
[image: WebsiteGB] <http://www.2zerozero.com>   [image: email]
<dipaktelangre@gmail.com>    [image: Facebook button]
<http://https://www.facebook.com/dipaktelangre>
<http://www.companysig.com>
