### ISSUE TITLE
MediaStreamRecorder got 0 blob size these days.

### ISSUE THREAD

**Issue by zslucky** [muaz-khan/RecordRTC#341]
env:
`recordrtc`:  `5.4.2`
`Chrome`: `61.0.3163.100 (Official Build) (64-bit)`
`OS`: `Mac 10.12.5`

I'm using `MediaStreamRecorder` for few months, it works fine. But these days, I got error when playing audio due to audio blob size is 0.

For init:
```javascript
// stream comes from webrtc
// navigator.mediaDevices.getUserMedia({audio: true})
const recordRTC = RecordRTC(stream, {
  recorderType: RecordRTC.MediaStreamRecorder,
  mimeType: 'audio/webm'
})
```
In start recording button:
```javascript
recordRTC.recordRTC.startRecording()
```

In stop recording button:
```javascript
recordRTC.stopRecording(url => {
  this.audioUrl = url // add url for <audio> here
  const blobData = recordRTC.getBlob();
  // Use blobData here to create audio file for uploading.
})
```

**Comment by zslucky** [comment]
I tried your other simple demos for audio record. most of them are recorded audio as mime type `audio/wav`, they are all silent, I dont know why...

**Comment by muaz-khan** [comment]
Did you try [this one](https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html)?

You may need to pass [custom sampleRate](https://github.com/muaz-khan/RecordRTC#samplerate) and/or [bufferSize as well](https://github.com/muaz-khan/RecordRTC#buffersize).

**Comment by zslucky** [comment]
@muaz-khan , yes, sure. I can recording and playing record on your most demos, but can't hear anything on my `mac chrome`.

BTW. I tested my issue on `windows chrome`, looks like everything is OK, (as I have no micphone, I only tested the function, worked correctly like before)
But on my `mac chrome`, add the `sampleRate` and `bufferSize` still not worked, I still got `blob size: 0`. 

An interesting thing is that, the `MediaStream` will be stopped by itself in a few seconds after you open micphone if I only set audio to true. e.g.
```javascript
navigator.mediaDevices.getUserMedia({audio: true}).then(stream => { //... })
```
you can try to run this script on chrome console, obviously you can see that the stream stopped on Mac, but still work on Windows... I guess this maybe the root cause... but I don't know why? And how to fixit 😢

**Comment by zslucky** [comment]
Solved, not sure, but maybe the OS and Chrome problem, not this repo's issue.

I upgrade the mac os from `10.12.5` ->  `10.12.6`, Chrome from `61` -> `62`, solved.
