### ISSUE TITLE
Recording not working on Opera OSX

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#347]
When I try to record an example on https://www.webrtc-experiment.com/RecordRTC/ using Opera 48 on OSX it produces a blank video file.

**Comment by muaz-khan** [comment]
If I select VP8 or VP9 from the dropdown then Opera on Win+Mac works as well. i.e. you should be passing following mimeType:

```javascript
recorder = RecordRTC(stream, {
    mimeType: 'video/webm\;codecs=vp8' // or vp9
});
```

Following mimeType generates a blank video:

```javascript
recorder = RecordRTC(stream, {
    mimeType: 'video/webm' // i.e. without video codecs indication
});
```

**Comment by thijstriemstra** [comment]
Thanks, that worked.
