### ISSUE TITLE
InvalidCharacterError and Stream does not contain audio track

### ISSUE THREAD

**Issue by Almarane** [muaz-khan/RecordRTC#35]
Hi Muaz

I am trying to record a video+audio stream with Node.js on Firefox, but it doesn't seem to work. I have two problems:

1. When I try to use "new RecortRTC" with config.type="audio", I get the error "your stream does not contain audio track", even though I allow Firefox to have access to my microphone.
Here is my console log:
```
"Asking recording" cVEtGxq6EQ:1869:5
"Starting recording for room cVEtGxq6EQ!" cVEtGxq6EQ:1749:4
"started recording audio stream." RecordRTC.js:92:13
uncaught exception: Your stream has no audio tracks. <inconnu>
```
2. I managed to get past this first error by setting config.type="video", but then I get a second error. As soon as I try to use ".stopRecording", Firefow throws the error ": InvalidCharacterError: String contains an invalid character". Sometimes this error is replaced by "TypeError: riff.RIFF is undefined".
Once again, my console log:
```
"Asking recording" cVEtGxq6EQ:1869:5
"Starting recording for room cVEtGxq6EQ!" cVEtGxq6EQ:1749:4
"started recording video stream." RecordRTC.js:92:13
"canvas resolutions" 320 "*" 240 RecordRTC.js:2053:13
"video width/height" 320 "*" 240 RecordRTC.js:2054:13
"Asking to stop recording" cVEtGxq6EQ:1875:5
"stopRecord" cVEtGxq6EQ:1805:4
"TRACE 1/2" cVEtGxq6EQ:1810:5
"Stopped recording video stream." RecordRTC.js:169:13
: InvalidCharacterError: String contains an invalid character
```
Finally, here is the code I use:
```
socket.on("startRecord", function(data)
		{
			console.log("Starting recording for room " + data.webconf_key + "!");
			if(isFirefox)
			{
				navigator.getUserMedia = navigator.mozGetUserMedia;
				navigator.getUserMedia({
					audio: true,
					video: true
				}, function(stream) {
					recordVideo = window.RecordRTC(stream, {
            					type: "audio" //changed to "video" on 2.
					});
					recordVideo.startRecording();
				}, function(error) {
					console.error(error);
				});
			}
			else //is isChrome
			{
				//[...]
			}
		});
		socket.on("stopRecord", function(data)
		{
			console.log("stopRecord");

			if(isFirefox)
			{
				console.log("TRACE 1/2");
				recordVideo.stopRecording(function() {
					console.log("TRACE 2/2");
					console.log(window.recordVideo.getBlob());
				});
			}
			else
			{
				//[...]
			}
		});
```

Also, I am using RecordRTC.js updated at August 23, 2015, 08:32:23

**Comment by muaz-khan** [comment]
If you're recording audio+video in Firefox:

```javascript
navigator.getUserMedia = navigator.mozGetUserMedia;
navigator.getUserMedia({
    audio: true,
    video: true
}, function(stream) {
    recordVideo = window.RecordRTC(stream, {
        type: "video",
        recorderType: MediaStreamRecorder // optional
    });
    recordVideo.startRecording();
}, function(error) {
    console.error(error);
});
```

If you're recording audio from a media stream that is having both audio/video tracks:

```javascript
navigator.getUserMedia = navigator.mozGetUserMedia;
navigator.getUserMedia({
    audio: true,
    video: true
}, function(stream) {
    recordVideo = window.RecordRTC(stream, {
        type: "video",
        recorderType: StereoAudioRecorder // force WebAudio API
    });
    recordVideo.startRecording();
}, function(error) {
    console.error(error);
});
```

If Firefox is having no `getAudioTracks` method:

```javascript
MediaStream.prototype.getAudioTracks = function() {
     return [this];
};
```

If you wanna record audio but wanna use [`MediaStreamRecorder.js`](http://recordrtc.org/MediaStreamRecorder.html):

```javascript
navigator.getUserMedia = navigator.mozGetUserMedia;
navigator.getUserMedia({
    audio: true,
    video: false //------------------DON'T CAPTURE VIDEO STREAM
}, function(stream) {
    recordVideo = window.RecordRTC(stream, {
        type: "audio",
        recorderType: MediaStreamRecorder // optional
    });
    recordVideo.startRecording();
}, function(error) {
    console.error(error);
});
````

**Comment by muaz-khan** [comment]
AFAIK, webp format is NOT supported by Firefox. That's why we can't use this:

* http://recordrtc.org/WhammyRecorder.html

**Comment by Almarane** [comment]
Thank you for your answer, I think it is working.

Is it possible to record a screen too, with the same method as audio+video record ?

**Comment by muaz-khan** [comment]
[RecordRTC demo](https://www.webrtc-experiment.com/RecordRTC/) is supporting `audio+screen` recording in Firefox.

Simply make sure that you installed this [Open-Sourced Firefox Extension](https://github.com/muaz-khan/Firefox-Extensions):

* [enable-screen-capturing.xpi](https://www.webrtc-experiment.com/store/firefox-extension/enable-screen-capturing.xpi)

Chrome doesn't yet supports audio+screen capturing in single MediaStream object. It doesn't even supports MediaRecorder API. That's why we are still bond to use solutions like [Ffmpeg.js](https://github.com/muaz-khan/Ffmpeg.js) to merge/mux two separate files: WAV and WebM -- into single WebM or similar container formats.
