### ISSUE TITLE
Trouble saving long videos

### ISSUE THREAD

**Issue by jasonblanchard** [muaz-khan/RecordRTC#36]
We've had great success running RecordRTC in a NW.js app (formerly node-webkit).

We're having an issue, however, with longer recordings. In our app, since we have a node.js context via NW.js, we're doing something like this to write the recording to a file (simplified for readability):

```
videoRTC.stopRecording(function(url) {
  var blob = videoRTC.getBlob();
  var fs = require('fs');
  var reader = new FileReader();

  reader.addEventListener('loadend', function() {
    fs.writeFile('/scratch/video.webm', reader.result, function() {});
  })

  reader.readAsArrayBuffer(blob);
});
```

When we record a video less than 9 minutes, this all works fine. In the `loadend` callback on `reader`, we get a proper `ArrayBuffer` object in `reader.result` with a normal `byteLength` and we can write that file to disk just fine.

However, after about 9 minutes of recording, in the `loadend` callback, `reader.result` does not exist, and `reader.error` gives us:

```
{ 
  error: FileError,
  code: 1,
  message: "A requested file or directory could not be found at the time an operation was processed."name: "NotFoundError"
}
```

Before calling `reader.readAsArrayBuffer(blob)`,  `blob.size` does show a file size, usually around 100mb, so I think there's data in there. The problem seems to be when we read that out into binary data to be saved to a file.

We had various other strange behavior reading the data out of the blob in total and in slices, but this has been the most consistent, concrete error.

Anyone else encountering this?

**Comment by muaz-khan** [comment]
ArrayBuffer in browser having `byteLength` limitations. We can either use ArrayBuffer in nodejs side or try an alternative solution like this one:

* [https://github.com/streamproc/Record-Entire-Meeting](https://github.com/streamproc/Record-Entire-Meeting)

[ConcatenateBlobs.js](https://github.com/muaz-khan/ConcatenateBlobs) doesn't works as well.
