### ISSUE TITLE
Safari iOS11 returns empty audio data when using the NPM version of RecordRTC

### ISSUE THREAD

**Issue by keyhole425** [muaz-khan/RecordRTC#365]
Hi all,
Working on a project to capture audio from browser on all devices (I know, I know, so much fun!)

I'm working in Node + React using the NPM installed version of RecordRTC and have it working for Chrome/FF/Edge on the usual devices, and also have Safari on macOS working.  The only issue is, no matter what, Safari on iOS (both iPads and iPhones exhibit this) always returns silence from recording.

I've been following all of the issue threads related to Safari on here so far, and there appear to be a few claimed solutions from various users, but many of these seem to only work for the client-side version of RecordRTC and when applied to this project, either do nothing or break the build.

EDIT: I had a colleague try the [simple audio](https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html) link as per the [browser support](https://github.com/muaz-khan/RecordRTC#browsers-support) on this project's README.  Running iPhone 6s with iOS 11.2.1, nothing worked and the "This browser does not supports (sic) WebRTC getUserMedia API."  error appeared.

Double Edit: HOWEVER, another colleague on his iPhone 7 (different version - iOS 11.1.2) received *some* audio 40 seconds into recording using our project (not the link above).  On second attempt at recording, full audio was captured as expected.  Behaviour seems incredibly unreliable though...

Questions:

- Am I chasing ghosts with this?
- Are there any working examples of RecordRTC working for Safari iOS11 using the NPM version of RecordRTC?

Happy to provide current code samples if need be, would just need to clean them up for posting.

**Comment by lokielse** [comment]
@keyhole425 

The audio data empty is becaues `onaudioprocess` is not called on iOS 11

https://stackoverflow.com/a/46534088/4759808

> Safari on iOS 11 seems to automatically suspend new AudioContext's that aren't created in response to a tap

**Comment by keyhole425** [comment]
Thanks lokielse.  Seems like a non-issue now with the use of StereoAudioRecorder so I'm closing this for now
