### ISSUE TITLE
Audio gets distorted on video resizing

### ISSUE THREAD

**Issue by rafaelbuiu** [muaz-khan/RecordRTC#37]
I am using the RecordRTC-to-Nodejs example to record a testimonial video from my application.
The default setup records the videos very fine, but I need them in a bigger size instead of 320x240.
ie: 1920x1080 or 1280x720.

The audio gets distorted (like a robot) when I change the video config to:
```javascript
var videoConfig = {
     type: 'video',
     recorderType: WhammyRecorder,
     width: 1280,
     height: 720
};
```
**Is there anything I am missing?**

> Google Chrome Version 45.0.2454.85 (64-bit) on Mac Yosemite OSX

**Comment by rafaelbuiu** [comment]
Actually it happens if I resize to any size. I just tried 800x600 and 640x480.

**Comment by muaz-khan** [comment]
Setting `bufferSize: 16384` fixes this issue.

```javascript
// Legal values are (256, 512, 1024, 2048, 4096, 8192, 16384).

var options = {
   bufferSize: 16384
};
var recordRTC = RecordRTC(audioStream, options);
```

Relevant commit: https://github.com/muaz-khan/RecordRTC/commit/329e38610f72e6a8b3f630c637be53f6bbee48e5
