### ISSUE TITLE
Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by jrohlandt** [muaz-khan/RecordRTC#370]
Hey Muaz, 
Thank you for a great library.

Does it work in Firefox 57 and later?
I tried the experiment at https://www.webrtc-experiment.com/RecordRTC/ but it does not record video.

![screenshot from 2017-12-22 15 41 17](https://user-images.githubusercontent.com/4688503/34299977-a2a0895c-e72e-11e7-9e2e-6f39412d4450.png)

**Comment by thijstriemstra** [comment]
Yep it does.

**Comment by jrohlandt** [comment]
Seems to be working, thanks.
