### ISSUE TITLE
setRecordDuration problem

### ISSUE THREAD

**Issue by p0d3r** [muaz-khan/RecordRTC#39]
Well, thank you for the fast update.

I have updated the new commit but now there's another issue occured. 

I set the max duration time to 15 \* 1000 but now it stops at 7th second. I changed time to 30 \* 1000 it stopped at 15th second.

Thanks.

**Comment by AliPoder** [comment]
Also how can I set framerate for video?

**Comment by AliPoder** [comment]
AND I tried that new commit looks like it works for VIDEO but not for audio.

For a video recording which 15 seconds AUDIO file is more than 15 secs. in my case it was 35 secs.
