### ISSUE TITLE
Query about idle state

### ISSUE THREAD

**Issue by arinhere** [muaz-khan/RecordRTC#406]
Hello Muaz,

First of all, thank you for your brilliant article. It helps us a lot.

In my project, I would like to stop recording when user is silenced for 3-4 seconds. I wanted to make this automated, without clicking stop button. Is there anyway this can be achieved.

Please let me know

Thanks - Arin

**Comment by muaz-khan** [comment]
Here is the demo:

* https://www.webrtc-experiment.com/RecordRTC/simple-demos/auto-stop-on-silence.html

**Comment by arinhere** [comment]
Thanks Muaz, you are a life saver. Much appreciated :)

Thanks again
