### ISSUE TITLE
Video recorded through Chrome has stuttering audio

### ISSUE THREAD

**Issue by maxpaj** [muaz-khan/RecordRTC#415]
**Some background**
I'm using RecordRTC through [videojs-record](https://www.npmjs.com/package/videojs-record) in my application. It's part of a platform where our users can record videos of themselves or their screen and send them as video messages to customers / clients. Works great for sales or support for example.

I need the videos to run in as many browsers as possible, so I'm using a 3rd party service (Zencoder) to transcode videos from whatever format I'm getting from the recorder in Google Chrome to a H.265/AAC MP4 container ([caniuse MPEG-4/H.264](https://caniuse.com/#feat=mpeg4)). The codecs that are used for recording are VP8/OPUS (WEBM container)

**The issue**
Lately I've seen that some of the videos that are recorded through Google Chrome have the video and audio out of sync or that the video and audio stutters, depending on which player we're using. Playing the file in Chrome renders smooth playing audio. Playing the video in VLC on my Windows machine renders stuttering audio. You might call these video files **corrupt**. To my knowledge, this have so far only occurred on Mac OSX machines.

When we run the **corrupt** video files through Zencoder we see MP4 video files coming out of there with stuttering audio, no matter which player we're using. According to them, it's because of their mechanisms that try to sync up the audio and video from the corrupt file that Chrome has recorded.

According to their support:
> Inspecting our encoding logs, I've noticed the following kind of warnings:
> 
> [2018-05-16 14:08:38.009]  [pcm_s16le @ 0x1d608c0] pcm_encode_frame: filling in for 5856 missing samples (122 ms) before pts 40800 to correct sync!
> [2018-05-16 14:08:38.009]  [pcm_s16le @ 0x1d608c0] pcm_encode_frame: dropping 2880 samples (60 ms) at pts 43392 to help correct sync to -3168 samples (-66 ms)!
> 
> The problem here comes from the way that the audio in the original source file is encoded.

>  you should ensure that the audio is not out of sync (audio timestamps are correct) in your source file before submitting the job to ZC 

Running the file through `ffmpeg`, re-encoding with the same codecs, produces the same stuttering video. The logs produce an alarming amount of errors. Here is a sample of the log output:
```[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15196, current: 15193; changing to 15196. This may result in incorrect timestamps in the output file.
[libopus @ 0000029938e24d80] Queue input is backward in timeitrate= 194.8kbits/s dup=0 drop=5 speed=0.31x
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15434, current: 15394; changing to 15434. This may result in incorrect timestamps in the output file.
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15434, current: 15414; changing to 15434. This may result in incorrect timestamps in the output file.
[libopus @ 0000029938e24d80] Queue input is backward in timeitrate= 193.3kbits/s dup=0 drop=5 speed=0.309x
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15539, current: 15499; changing to 15539. This may result in incorrect timestamps in the output file.
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15539, current: 15519; changing to 15539. This may result in incorrect timestamps in the output file.
[libopus @ 0000029938e24d80] Queue input is backward in timeitrate= 192.0kbits/s dup=0 drop=5 speed=0.308x
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15667, current: 15627; changing to 15667. This may result in incorrect timestamps in the output file.
[webm @ 0000029938e09b00] Non-monotonous DTS in output stream 0:1; previous: 15667, current: 15647; changing to 15667. This may result in incorrect timestamps in the output file.
[libopus @ 0000029938e24d80] Queue input is backward in time
```

I tried running the same inputs through another transcoding service called Coconut and those outputs worked a lot better - video was still stuttering but the audio played smoothly, which is more important to the use case of my application. I guess we could simply switch to using Coconut, but I'm curious why this happens in the first place.

Previously I've noticed that recording video in Google Chrome has produced videos that have unavailable stream durations. It's not available in the metadata of the file ([I guess this is related](https://bugs.chromium.org/p/chromium/issues/detail?id=642012)). However, I'm quite certain my current issue does not stem from that, since most files come through with fine video/audio.

I'm far from sure that this is related to RecordRTC, but that's the closest I can get to the source of the issue. If I'm in the wrong forum - please point me in the right direction. Should I post this on the Chromium bug tracker?

One step in the right direction would be to just be able to detect when the video is corrupt. How can I do that?

**Comment by jhemarcos** [comment]
@maxpaj Did you find a solution for this problem?
