### ISSUE TITLE
URL.createObjectURL will be removed (very) soon from Chrome

### ISSUE THREAD

**Issue by claudioc** [muaz-khan/RecordRTC#423]
Hello,

apparently RecordRTC is using a deprecated method which is about to be removed from Chrome. Do you have any plan to replace it with the replacement (srcObject)? Thanks!

```
[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed
in M68, around July 2018. Please use HTMLMediaElement.srcObject instead.
See https://www.chromestatus.com/features/5618491470118912 for more details.
```

**Comment by claudioc** [comment]
As I see it, this could be a problem since Chrome (and Firefox) will remove the support to a stream to be used as a parameter for the createObjectURL method, not the method itself (I see the test in `setSrcObject`)

**Comment by muaz-khan** [comment]
Try-catch was added only for canvas-recording demos. Those demos do not work anymore.

So now we can update `setSrcObject` as following:

```javascript
function setSrcObject(stream, element, ignoreCreateObjectURL) {
    if ('srcObject' in element) {
        element.srcObject = stream;
    } else if ('mozSrcObject' in element) {
        element.mozSrcObject = stream;
    } else if ('createObjectURL' in URL && !ignoreCreateObjectURL) {
        try {
            element.src = URL.createObjectURL(stream);
        } catch (e) {
            setSrcObject(stream, element, true);
            return;
        }
    } else {
        alert('createObjectURL/srcObject both are not supported.');
    }
}
```

I'm reopening this issue. I'll close it via commit. (need to make some tests before making a change in the `RecordRTC.js`)

**Comment by gzelibean** [comment]
@muaz-khan Is this already updated on the latest commit? Thanks

**Comment by muaz-khan** [comment]
Nope. Not yet. Sorry missed it. Fix will be included in the next release.
