### ISSUE TITLE
"Uncaught TypeError: e is not a function" when using RecordRTC in Angular-CLI app

### ISSUE THREAD

**Issue by jeffgammon** [muaz-khan/RecordRTC#429]
When stopping a recording, the generated blob JavaScript has an onmessage method in it whose parameter name is "e". This is the bit of generated JavaScript:

this.onmessage =  function (e) {whammyInWebWorker(e.data);}

However, when including RecordRTC in an Angular2 application, the Angular CLI re-minifies/uglifies RecordRTC.min.js, resulting in the whammyInWebWorker function being renamed to "e" in my particular bundle. This is the bit of generated JavaScript now:

this.onmessage = function(e) { e(e.data); }

Because the uglified name is "e", and the parameter name is also "e", the function errors with

Uncaught TypeError: e is not a function
    at onmessage (blob:https://....)

Is it possible that you rename the "e" parameter name in onmessage to a name that is much less likely to collide with a minified/uglified name? I believe you generate this in the "processInWebWorker" method around line 2759.

**Comment by bsmarsh333** [comment]
Would be great to get some feedback about this. I am also experiencing the same problem.

**Comment by jeffgammon** [comment]
@muaz-khan , I tried to submit a pull request with the fix for this issue, but I get access denied when trying to push the branch. Is it possible for me to create a pull request?

**Comment by thijstriemstra** [comment]
@muaz-khan can you release a new version?

**Comment by bsmarsh333** [comment]
Thank you, @muaz-khan, for adding this commit. We are getting more users encountering this issue and we would appreciate a new release.
