### ISSUE TITLE
Audio+video recording in Firefox produces corrupt webm files

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#43]
When trying to record audio + video on Firefox 41.0.1 (on osx 10.10.5) the resulting webm file is corrupt and cannot be played. This is using the latest RecordRTC (October 04, 2015) on https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html.

**Comment by muaz-khan** [comment]
Can you please test experimental branch and see if it is fixed now:

* [https://github.com/muaz-khan/RecordRTC/tree/experimental](https://github.com/muaz-khan/RecordRTC/tree/experimental)

Test: `127.0.0.1/index.html`

**Comment by thijstriemstra** [comment]
Thanks that fixed it!

**Comment by szwang** [comment]
I'm getting the same issue and can no longer access the experimental branch. What fixed it previously? Thanks!
