### ISSUE TITLE
High CPU usages with MultiStreamRecorder.js

### ISSUE THREAD

**Issue by ravipatel07** [muaz-khan/RecordRTC#442]
Hi, we are creating a video conferencing project with RTCMulticonnection. Now we have to implemented recording functionality using MultiStreamRecorder.js. We used to start recording with 5 seconds interval. But using this CPU usages getting 90% - 100%. So how can we reduce CPU usages?

**Comment by farukhzahoor** [comment]
Hi @ravipatel07 

Did you solve that issue? I am getting same issue with MultiStreamRecorder...

**Comment by ranahemantkumar** [comment]
i also have same issue with MultiStreamRecorder.

**Comment by ravipatel07** [comment]
@farukhzahoor and @ranahemantkumar, I didn't find any solution for this issue.
