### ISSUE TITLE
Recording cancas video can play but download file can not open

### ISSUE THREAD

**Issue by lis1314** [muaz-khan/RecordRTC#443]
I consulted the webpage-recording and made a recording of canvas,it can be played on <video>, but after downloading, the video can not be opened, I do not know how to solve?can you give me some suggestions? thank you !

`var recorder = new RecordRTC(canvas2d, {
    type: 'canvas',
	getNativeBlob:true
});

 var recordedBlobs= recorder.getBlob();     
 var blob =new Blob([recordedBlobs], {type: 'video/mp4'});
        const url = $window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.style.display = 'none';
        a.href = url;
        a.download = 'test.mp4';
        document.body.appendChild(a);
        a.click();
        setTimeout(function () {
            document.body.removeChild(a);
            $window.URL.revokeObjectURL(url);
        }, 100);
`

**Comment by muaz-khan** [comment]
Please test in VLC player. Also include `mimeType: 'video/webm\;codecs=h264'`. E.g.

```javascript
var recorder = new RecordRTC(canvas2d, {
    type: 'canvas',
    mimeType: 'video/webm\;codecs=h264',
    getNativeBlob: true
});

var recordedBlobs = recorder.getBlob();
var file = new File([recordedBlobs], 'video.mp4', {
    type: 'video/mp4'
});

invokeSaveAsDialog(file);
```

**Comment by lis1314** [comment]
Thanks for your reply. I tryed your code , when use firefox download , it can be played by video player, but when i use chrome download , it can't be played by video player.

chrome version  69.0.3497.92         firefox version  firefox 62.0

**Comment by muaz-khan** [comment]
Maybe you should try `{recorderType: WhammyRecorder}` on chrome or otherwise a different `mimeType` e.g.

```javascript
var recorder = new RecordRTC(canvas2d, {
    type: 'canvas',
    mimeType: 'video/webm'
});

var recordedBlobs = recorder.getBlob();
var file = new File([recordedBlobs], 'video.webm', {
    type: 'video/webm'
});

invokeSaveAsDialog(file);
```
List of mime-types:
* https://github.com/muaz-khan/RecordRTC#recordrtc-containers-format

**Comment by lis1314** [comment]
The effect I want is to record the animation in canvas, and finally download it into MP4 format. 

i refferance this page 
https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/webpage-recording.html

download success ,video player can not play .

WhammyRecorder may not suit me

**Comment by lis1314** [comment]
I resolved this problem by change mimeType e.g.
`var recorder = new RecordRTC(canvas2d, {
    type: 'canvas',
    mimeType: 'video/webm;codecs=vp9',
    getNativeBlob: true
});
`

**Comment by hussain2y2** [comment]
@muaz-khan I'm trying to show the recording Video in video tag but not able.... Can you share any helpful script?
