### ISSUE TITLE
support for webm-wasm

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#468]
There's a really new project that seems to allows you to 'create webm videos in JavaScript via WebAssembly': https://github.com/GoogleChromeLabs/webm-wasm

Perhaps this can replace/work as alternative to Whammy @muaz-khan?

**Comment by muaz-khan** [comment]
Just added a new demo:
* https://www.webrtc-experiment.com/RecordRTC/simple-demos/WebAssemblyRecorder.html

`Grunt-contrib-uglify` fails to parse `dev/WebAssemblyRecorder.js`; Maybe we should use `uglify-es` instead? (`Gruntfile.js` line 56)

**Comment by thijstriemstra** [comment]
thanks @muaz-khan. Just tested the demo on firefox win 10 and it throws this error:

```
ReferenceError: ReadableStream is not defined
```

**Comment by muaz-khan** [comment]
Following demo now works on Firefox as well:
* https://www.webrtc-experiment.com/RecordRTC/simple-demos/WebAssemblyRecorder.html

It required following polyfill:

```html
<script src="https://unpkg.com/@mattiasbuelens/web-streams-polyfill/dist/polyfill.min.js"></script>
```

**Current support:** Chrome and Firefox.

Firefox may require following two flags via `about:config`:

```
dom.streams.enabled;true
javascript.options.streams;true
```

**Comment by thijstriemstra** [comment]
@muaz-khan tried the demo and looks like you're including a older version of webm-wasm because the metadata is missing and that was recently fixed.

```
Input #0, matroska,webm, from '/foo/Downloads/abc.webm':
  Metadata:
    encoder         : libwebm-0.2.1.0 but in wasm
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p(progressive), 640x480, SAR 1:1 DAR 4:3, 30.30 fps, 30 tbr, 1k tbn, 1k tbc (default)
```

**Comment by muaz-khan** [comment]
@thijstriemstra Just updated MRecordRTC. I've tested only following scenarios:

```javascript
mRecordRTC.mediaType = {
     audio: SteoreoAudioRecorder,
     video: WebAssemblyRecorder
};
```

I didn't test other combinations yet.

**Comment by thijstriemstra** [comment]
thanks @muaz-khan, can you publish 5.5.3 on npm?

**Comment by muaz-khan** [comment]
@thijstriemstra Published.

**Comment by thijstriemstra** [comment]
Fyi, Readable Streams have been enabled by default in Firefox 65, `javascript.options.streams` setting is no longer needed.

**Comment by pwob** [comment]
Hi I manage to make this work with Safari 12 with no playback (webm), but video recorded is too short. Am I missing something in the options or configs? Thanks!

**Comment by muaz-khan** [comment]
@pwob please test this (i.e. pass `bitrate:200`): [ via [WebAssemblyRecorder.js#L31](https://github.com/muaz-khan/RecordRTC/blob/master/dev/WebAssemblyRecorder.js#L31) ]

```html
<title>WebAssembly Recorder using RecordRTC</title>
<style type="text/css">
body {
  text-align: center;
}

video {
  border-radius: 5px;
  border: 1px solid black;
}
</style>

<h1>WebAssembly Recorder using RecordRTC</h1>
<button id="start">Start Recording</button>
<button id="stop" disabled>Stop Recording</button>
<br><br>
<video id="video" controls autoplay playsinline></video>

<!-- web streams API polyfill to support Firefox -->
<script src="https://unpkg.com/@mattiasbuelens/web-streams-polyfill/dist/polyfill.min.js"></script>

<script src="https://cdn.webrtc-experiment.com/RecordRTC.js"></script>
<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

<script>
var recorder;

document.getElementById('start').onclick = function() {
    this.disabled = true;
    navigator.mediaDevices.getUserMedia({
        video: {
            width: {
                ideal: 640
            },
            height: {
                ideal: 480
            }
        },
        audio: false
    }).then(function(stream) {
        document.getElementById('video').srcObject = stream;

        recorder = RecordRTC(stream, {
            recorderType: WebAssemblyRecorder,
            // workerPath: '../libs/webm-worker.js',
            // webAssemblyPath: '../libs/webm-wasm.wasm',
            width: 640,
            height: 480,
            frameRate: 30,
            bitrate: 200
        });
        recorder.startRecording();

        document.getElementById('stop').disabled = false;
    });
};

document.getElementById('stop').onclick = function() {
    document.getElementById('video').srcObject = null;

    this.disabled = true;
    recorder.stopRecording(function(blob) {
        document.getElementById('video').src = URL.createObjectURL(recorder.getBlob());
        document.getElementById('start').disabled = false;
    });
}
</script>
```

**Comment by pwob** [comment]
Works! Also I needed to add timeout when stopping the recording. In my case it does not record my last gesture before stopping (i smiled before ending the 10 second video to test, but I did not see it in the preview).

`setTimeout(() => {
			terminate();
			this.blob = new Blob(arrayOfBuffers, {
				type: 'video/webm'
			});

			callback(this.blob)
		}, 3000);`

**Comment by thijstriemstra** [comment]
Looks good to me, closing as fixed.
