### ISSUE TITLE
How to support .amr file?

### ISSUE THREAD

**Issue by TongDaDa** [muaz-khan/RecordRTC#483]
<img width="687" alt="2019-02-19 5 10 25" src="https://user-images.githubusercontent.com/23241188/53003185-5a238b00-3469-11e9-9653-a9e8b4a82da1.png">

but 

<img width="718" alt="2019-02-19 5 15 45" src="https://user-images.githubusercontent.com/23241188/53003502-05ccdb00-346a-11e9-8b75-dcfb153fdfae.png">

It seems has changed the mimeType, I set the mimeType as a 'audio/wav', but a moment, It is modified as `webm`.

I want it to support mp3 and wav and other formats. not only webm format.

**Comment by muaz-khan** [comment]
`audio/wav` requires `reocrderType: SteoreAudioRecorder`. Please try this:

```javascript
recordAudioWAV = RecordRTC(stream, { recorderType: StereoAudioRecorder } );
```

**Comment by TongDaDa** [comment]
@muaz-khan Hi, what is SteoreAudioRecorder?

**Comment by TongDaDa** [comment]
Ok, I have know about it, thanks!!!

**Comment by TongDaDa** [comment]
warn: It seems that recorder is destroyed or "startRecording" is not invoked for audio recorder.

```
 this.state.recordVideo = RecordRTC(stream, { type: 'audio', mimeType: 'audio/wav',  recorderType: 'StereoAudioRecorder'});
```

**Comment by TongDaDa** [comment]
I think this condition should process in codes? 

Judging that mimeType and give it a proper `recorderType` automatically,  so this has any problems?

**Comment by TongDaDa** [comment]
@muaz-khan Hi, does it support amr format?

**Comment by muaz-khan** [comment]
@TongDaDa You can release camera using `track.stop`. E.g.

```javascript
stream.getTracks().forEach(track => {
   track.stop();
});
```

**Comment by TongDaDa** [comment]
@muaz-khan Pakistan friend, I am Chinese...
