### ISSUE TITLE
In Chrome, video recording eventually starts staggering/faltering after doing one or more longer recordings

### ISSUE THREAD

**Issue by jostheeuwen** [muaz-khan/RecordRTC#49]
When recording a video in Chrome (46.0.2490.71), the end result starts out with a smooth frame rate, but eventually it will start to stagger/falter. I have reproduced this on this RecordRTC demo site:
https://www.webrtc-experiment.com/RecordRTC/

Reproduction scenarios I have used:
1) 
- Start a new Chrome browser 
- Record 10 min, watch the recording (with or without seeking), recording is fine 
- Record another 5 min, watch the recording (with or without seeking), recording will start to stagger/falter after 1-3 min.

2) 
- Start a new Chrome browser 
- Record 5 min, watch the recording (with or without seeking), recording is fine 
- Record another 5 minutes, watch the recording (with or without seeking), recording is fine 
- Record another 5 minutes, watch the recording (with or without seeking), recording will start to stagger/falter after 1-3 min.

So it seems to have something to do with the total time you are recording in Chrome, but it doesn't seem to be a constant number of minutes. It is also likely that it varies across different client machines (?)

**Comment by Waterdhavian** [comment]
I have encountered the same issue after i just updated my chrome browser. Can we get this fixed please? :)

**Comment by jostheeuwen** [comment]
I've just retested this with the latest RecordRTC (5.2.3) and Chrome (48.0.2550.0 canary) and it is still an issue. Any thoughts?

**Comment by muaz-khan** [comment]
**Still an issue?** PS. closing this thread because its too old.
