### ISSUE TITLE
can i record screen only?

### ISSUE THREAD

**Issue by lukuilian** [muaz-khan/RecordRTC#491]
if i don't have microphone or speaker , can i record screen only?
In my pc without audio device, i set { audio:false, video:true} to record screen, but it is not OK. it occurs error in detect audio device.

for the plugin, it can record screen only. code as follow:

var recorder = new RecordRTC_Extension();

recorder.startRecording({
    enableScreen: true,
    enableMicrophone: true,
    enableSpeakers: true
});

btnStopRecording.onclick = function() {
    recorder.stopRecording(function(blob) {
        console.log(blob.size, blob);
        var url = URL.createObjectURL(blob);
        video.src = url;
    });
};

**Comment by lukuilian** [comment]
it is OK in chrome 72. but it is not OK in FireFox.

**Comment by muaz-khan** [comment]
I'll recommend getDisplayMedia API that is supported by all browsers today, including Safari-preview.

#### Screen ONLY

```javascript
let stream = await navigator.mediaDevices.getDisplayMedia({video: true});
let recorder = new RecordRTCPromisesHandler(stream, {
    type: 'video'
});
recorder.startRecording();

const sleep = m => new Promise(r => setTimeout(r, m));
await sleep(3000);

await recorder.stopRecording();
let blob = await recorder.getBlob();
invokeSaveAsDialog(blob);
```

#### Screen + Microphone

```javascript
let mic = await navigator.mediaDevices.getUserMedia({audio: true});
let screenPlusMic = await navigator.mediaDevices.getDisplayMedia({video: true});
screenPlusMic.addTrack(mic.getTracks()[0]);
let recorder = new RecordRTCPromisesHandler(screenPlusMic, {
    type: 'video'
});
recorder.startRecording();

const sleep = m => new Promise(r => setTimeout(r, m));
await sleep(3000);

await recorder.stopRecording();
let blob = await recorder.getBlob();
invokeSaveAsDialog(blob);
```

#### Screen + Speakers

Work in progress. Browser vendors may implement this feature in next 2-3 months. (because it is supported by the spec).

**Comment by lukuilian** [comment]
I got it.
Thank you
