### ISSUE TITLE
RecordRTC example (and other examples) doesn't work on iOS 12

### ISSUE THREAD

**Issue by alexbazilev** [muaz-khan/RecordRTC#495]
# Expected Behavior

Record audio multiple times.

# Current Behavior

Recording audio is possible only 4 times. On 5th try there is an alert with error.

# Failure Information

`null is not an object (evaluating 'context.createMediaStreamSource')`

# Steps to Reproduce

1. Open https://www.webrtc-experiment.com/RecordRTC/ using iOS 12 (or any other example like https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html ).
2. Use default recording parameters.
3. Click on "Start recording" and "Stop recording" 4 times.
4. On 5th try you will see an error.

# Context

* Operating System: iOS 12.1.4
* Browser: latest Safari 

# Screenshot

![2019-03-19 11-31-45](https://user-images.githubusercontent.com/2733010/54593887-8f0f0780-4a40-11e9-8882-ab15a24494b3.PNG)

**Comment by alexbazilev** [comment]
I'm upping this because not working example means not working library on iOS devices (iPhones, iPads). I received multiple complaints from users who can't record audio more than 4 times without page reloading in my application. So after that I tried RecordRTC examples, and they didn't work either.
@muaz-khan do you think it could be related to incorrect destroying RecordRTC object? Or maybe some Safari limitations? Other platforms work well.

**Comment by thaihau** [comment]
hi @alexbazilev This is because safari not support MediaRecordAPI yet 
https://caniuse.com/#feat=mediarecorder

https://blog.addpipe.com/safari-technology-preview-73-adds-limited-mediastream-recorder-api-support/

**Comment by xcloarec** [comment]
Hi everyone, I had exactly the same issue with my project.

@thaihau the example **audio-recording.html** mentioned by @alexbazilev  use StereoAudioRecorder on Safari browser which is working well, except the context problem which is limiting the number of uses.

I managed to solve this by using RecordRTC.Storage within StereoAudioRecorder, so the audio context can be closed when calling RecordRTC.close().

I created a pull request for this : https://github.com/muaz-khan/RecordRTC/pull/504

**Comment by Tayyaba03** [comment]
Hi everyone, we are facing the exact same issue, that recorder stops working after 4 recordings and it throws the `null is not an object (evaluating 'context.createMediaStreamSource')` error.

I tried the fix given by @xcloarec but it doesn't seem to work. 

@muaz-khan any update on this issue?

Any help would be appreciated

Thanks

**Comment by alexbazilev** [comment]
I can confirm that @xcloarec solution worked for me.
I manually updated RecordRTC.js code in node_modules folder with the code provided in his pull request and now I'm able to record audio more than 4 times in Safari (iOS 12).

**Comment by Tayyaba03** [comment]
@alexbazilev Thank you for confirmation. 

Can you please guide me in which file did you make the change? Maybe I changed the code in the wrong file.

Thank you

**Comment by alexbazilev** [comment]
@Tayyaba03 I went to PROJECT_FOLDER/node_modules/recordrtc/RecordRTC.js and applied this instead of lines 2879-2890 (RecordRTC version is 5.5.4):

`    
if (typeof RecordRTC.Storage === 'undefined') {
        RecordRTC.Storage = {
            AudioContextConstructor: null,
            AudioContext: window.AudioContext || window.webkitAudioContext
        };
    }

    if (!RecordRTC.Storage.AudioContextConstructor || RecordRTC.Storage.AudioContextConstructor.state === 'closed') {
        RecordRTC.Storage.AudioContextConstructor = new RecordRTC.Storage.AudioContext();
    }

    var context = RecordRTC.Storage.AudioContextConstructor;
`

This is not a good approach, because there is also RecordRTC.min.js that may probably be used for production bundle creation. What is more, "npm install" command may remove these temporary changes. So it is better to use pull request directly (https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request) or wait @muaz-khan to update the library. 
But for my current development purpose it works like a charm.

**Comment by Tayyaba03** [comment]
Thank you @alexbazilev and @xcloarec, it's working now :)

**Comment by fwang-laralabs** [comment]
@alexbazilev 당신 덕분에 시간을 벌었습니다. 감사합니다. 빠른 시일내에 반영 되길 희망합니다. :)

**Comment by Nandhan-augment** [comment]
Still facing the issue after taking a build.

**Comment by dpetryuk-amplify** [comment]
@muaz-khan hi, i'm still facing this issue on safari 13.1 in macOS catalina. It seems like the AudioContext is not set properly in safari, even though you are using webkitAudioContext to set it.
