### ISSUE TITLE
RecordRTC with PHP and ffmpeg audio/video not in sync

### ISSUE THREAD

**Issue by stevemccann** [muaz-khan/RecordRTC#5]
I have just tried to use the PHP-and-FFmpeg demo on my ubuntu server. It records the audio and video, uploads the files, but when it plays the merged video after uploading the audio and video are not in sync. It's probably more than 1 second out of sync. Can be tweaked? Or is it a issue with Chrome capturing the seperate audio and video files?

I'm using Chrome 38.0.2125.122 (64-bit) on Ubuntu 14.10 x64 to access with chrome web browser. The back end is a debian/ubuntu server with FFmpeg 2.4.3 (fetched from http://johnvansickle.com/ffmpeg/).

**Comment by unmanner89** [comment]
Hi,

may be root cause of this problen in "-itsoffset -00:00:01" option?

**Comment by muaz-khan** [comment]
It varies among different platfroms. Mac is having no latency however Windows is having about 100ms latency out of shared audio mode.

So, if you're invoking ffmpeg on Windows, then use `-itsoffset -00:00:03` and for Mac: skip it.

RecordRTC is having `onAudioProcessStarted`. Please use it along with external `video`. E.g.

```javascript
recordAudio = RecordRTC(stream, {
    onAudioProcessStarted: function() {  // ------- this line
        // start recording video here
        recordVideo.startRecording();
    }
});

recordVideo = RecordRTC(stream, {
    type: 'video',
    video: YourExternalHTMLVideoElement // ------- this line
});

recordAudio.startRecording();
```
