### ISSUE TITLE
Broken URL CDN

### ISSUE THREAD

**Issue by diegogarce** [muaz-khan/RecordRTC#522]
Good evening, I have a project and use RECORDRTC, today in the morning I noticed that it showed an error when recording, in console it showed me that I could not find the following resource:

https://cdn.WebRTC-Experiment.com/RecordRTC.js

Apparently the problem arises when solving the dns.
I used another CDN service, but I report this problem because if one of you is using it, you will see that the problem persists.

**Comment by daothanhduy305** [comment]
Change the "cdn" to "www" and it should work. See the latest commits for more info.

**Comment by diegogarce** [comment]
I tried and now it works. At some point announced the change? It would be useful to know about the notifications and thus prevent an incident.
Thank you very much for the contribution
