### ISSUE TITLE
Video recording dropping all frames in Chrome

### ISSUE THREAD

**Issue by bradyisom** [muaz-khan/RecordRTC#53]
The issue is around line 2586 of RecordRTC.js in the `dropBlackFrames` function:

```javascript
var image = new Image();
image.src = _frames[f].image;
context2d.drawImage(image, 0, 0, canvas.width, canvas.height);
```

The problem is that the image is not guaranteed to be loaded immediately after setting the `src` attribute, even though it is a data URL (http://stackoverflow.com/a/4807114/591310). If I put some logging around this code, `image.complete` is `false` in many, but not all, of my tests. This causes the entire image to be black and all frames to be dropped from the resulting video file except the first one.

The sample pages do not have this issue, nor does a simple test page that I wrote. However, when I integrate the library into my AngularJS application, it shows up. So, it could be a timing issue, or only show up when the page is more complex.

I am totally willing to put together a PR that fixes this issue. There are a couple of ways that it could be fixed and I wanted feedback before building the PR.

1. I could rewrite `dropBlackFrames` to use the `onload` event of the image element to ensure that the image is loaded before drawing it to the canvas. Since this would change the function to be asynchronous, I would have to add a callback method to the parameters.
2. I could just add a configuration option to not attempt to drop black frames. That would be a simple fix and get my code working.

Are there other solutions? Or, which of these would you prefer?

**Comment by bradyisom** [comment]
I added PR #53 that solves this by doing option 1.

**Comment by thijstriemstra** [comment]
Can be closed?

**Comment by bradyisom** [comment]
Yes, this should be closed. #55 solved this.
