### ISSUE TITLE
TypeError: "RecordRTC.RecordRTCPromisesHandler is not a constructor"

### ISSUE THREAD

**Issue by mustafaekim** [muaz-khan/RecordRTC#532]
```
let RecordRTC = require("recordrtc");
...
let recorder = new RecordRTC.RecordRTCPromisesHandler(this.stream, options);
```
that code throws the error below:
**TypeError: "RecordRTC.RecordRTCPromisesHandler is not a constructor"**

The problem is that RecortRTC does not include the RecordRTCPromisesHandler function at all.

if I use RecortRTC as a function, it returns a recorder (but that does not support promises)

**Comment by mustafaekim** [comment]
I forgot to say, I use **"recordrtc": "^5.5.6"**

**Comment by muaz-khan** [comment]
Can you try exact `5.5.5`?

**Comment by leo108** [comment]
@muaz-khan I got the same error in version `5.5.6`, I think it was caused by this line https://github.com/muaz-khan/RecordRTC/blob/5.5.6/RecordRTC.js#L5378, the MultiStreamsMixer override the  RecordRTC
