### ISSUE TITLE
Native iOS not Recording 

### ISSUE THREAD

**Issue by austinbarnes** [muaz-khan/RecordRTC#533]
Summary:
We manually build the Native iOS WebRTC framework for our application so that we can support bitcode. We update this framework every quarter. Back in February I tried to update and had issues recording the iOS stream.

I just tried today to update to the most recent version and am having issues recording the stream. Attached are logs showing the 2 different versions of the WebRTC Framework and how RecordRTC is dealing with the streams it gets. 

Failure version 76:
![webrtc_v68_record_rtc_log_success](https://user-images.githubusercontent.com/5625732/59798774-326df380-92a0-11e9-923a-e5e166ab8543.png)

Success version 68:
![webrtc_v76_record_rtc_log_failure](https://user-images.githubusercontent.com/5625732/59798775-326df380-92a0-11e9-890a-8762434a2b91.png)

From the logs I noticed that the ondataavailable event for the MediaRecorder is not firing. Which is really strange since the Chrome user and the iOS device are able to stream video to each other in a call no problem so there should be media stream data there. I also tried to log any of the other MediaRecorder events and the onerror did not fire. 

I thought that the problem might be with our version of RecordRTC, so I updated to most recent version and still had the same issue. It feels like the record issue might be caused by the native iOS framework, but I don’t want to rule anything out. 

Attached also is the config object the MediaStreamRecorder is using for the iOS stream.
![webrtc_v76_media_stream_recorder_config](https://user-images.githubusercontent.com/5625732/59798779-33068a00-92a0-11e9-972c-ae8976541404.png)

I tried changing the config’s value for the mimeType and it didn’t seem to make a difference. Is there anything else you would recommend trying? 

I really appreciate any help I can get, thanks!

Steps to Reproduce:
1. Start a call from an iOS device that uses WebRTC Framework version 76
2. Answer call on Chrome on a Desktop machine. 
3. Use RecordRTC to start recording the stream from the iOS device. 

Expected Results:
The iOS device stream is able to be recorded and the data saved into a file. 

Actual Results:
The iOS device stream is not recorded. 

Version/Build:
RecordRTC 5.5.6
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
MacOS Mojave 10.14.5
iOS 12.3.1
iOS WebRTC Framework m76

webrtc_v76_record_rtc_log_failure

**Comment by austinbarnes** [comment]
Here is the bug ticket I submitted to Google for the same issue: https://bugs.chromium.org/p/webrtc/issues/detail?id=10754

**Comment by austinbarnes** [comment]
Also good to note is that Android on the most recent native version works perfect and so does any other web to web call.

**Comment by austinbarnes** [comment]
So this was an issue with the Native iOS WebRTC code. They were using H264 to encode the stream which the MediaRecorder doesn't know how to use. I fixed this issue by forcing the iOS side to use the VP8 encoder.

**Comment by sachq** [comment]
Hi @austinbarnes, Could you tell me the steps you did to resolve this issue?

**Comment by DevJhns** [comment]
@austinbarnes , your results sounds promising!
Can you show how you forced ios to use other codecs, I want to use MediaRecorder to record audio webm on ios/mac side, so I need to force it to use opus codecs, have no idea how to do it, thx!
