### ISSUE TITLE
Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided.

### ISSUE THREAD

**Issue by lcyuhe** [muaz-khan/RecordRTC#534]
I got this error "Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided." when I use "addSreams" method.

https://recordrtc.org/MultiStreamRecorder.html#.this.addStreams

**Comment by muaz-khan** [comment]
Please try latest release i.e. v5.5.7:
* https://github.com/muaz-khan/RecordRTC/releases/tag/5.5.7

**Comment by lcyuhe** [comment]
@muaz-khan It works for me. Thank you.
