### ISSUE TITLE
RecordRTCPromisesHandler does not return an object with similar properties

### ISSUE THREAD

**Issue by mustafaekim** [muaz-khan/RecordRTC#535]
I started using the promise based approach, but the code breaks in many parts.

`var recorder = new RecordRTC.RecordRTCPromisesHandler(stream, options);`

recorder object does not have a **getState** or **reset** properties being a function.

Is there any documentation about what we are getting back when we use the constructor **RecordRTCPromisesHandler**?

I use library at version  **5.5.7**

**Comment by muaz-khan** [comment]
Fixed: https://github.com/muaz-khan/RecordRTC/commit/06c3d158a0b6dfc4b12679b951a43c4d80f180aa
