### ISSUE TITLE
WebAssemblyRecorder is not defined

### ISSUE THREAD

**Issue by s3and0s** [muaz-khan/RecordRTC#538]
I'm following the example demo here: https://www.webrtc-experiment.com/RecordRTC/simple-demos/WebAssemblyRecorder.html

```javascript
document.getElementById('video').srcObject = stream;
        recorder = RecordRTC(stream, {
            recorderType: WebAssemblyRecorder,
            // workerPath: '../libs/webm-worker.js',
            // webAssemblyPath: '../libs/webm-wasm.wasm',
            width: 640,
            height: 480,
            frameRate: 30
        });
```

I added the same recorderType option into the RecordRTC and my webpage shows that WebAssemblyRecorder is undefined.

I'm using React and using this import line:
```javascript
import RecordRTC from 'recordrtc';
```

My RecordRTC version is 5.5.8.

**Comment by s3and0s** [comment]
I figured it out, needed: 

```javascript
import RecordRTC, { WebAssemblyRecorder } from 'recordrtc';
```

**Comment by QC2168** [comment]
![image](https://github.com/muaz-khan/RecordRTC/assets/82024018/c9225045-aadf-47f4-aa93-3f366fccef7e)
He's not working properly.

**Comment by marceloxp** [comment]
Will no one pay attention to this problem?

**Comment by pascal-lcc** [comment]
add 
<script src="https://unpkg.com/@mattiasbuelens/web-streams-polyfill/dist/polyfill.min.js"></script>
