### ISSUE TITLE
all audio blob after first one in ondataavailable interval unplayable

### ISSUE THREAD

**Issue by PhaDuong** [muaz-khan/RecordRTC#539]
So i'm working on angular 7 project.
I have a code setup like below, after each loop of timeslice, i sending a blob that recorded to server,  first blob has no problem in serverside, but from second one, blobs is not playable to process in server side, please help

this.recorder = new RecordRTC.MediaStreamRecorder(this.stream, {
      type: 'audio',
      desiredSampRate: 16000,
      numberOfAudioChannels: 1,
      bitrate: 256000,
      mimeType: 'audio/wav',
      timeSlice: dur,
      ondataavailable: function (blob) {
        // var b = new Blob([blob], { type: 'audio/wav' });
        // upload file to server
        const formData = new FormData();
        formData.append('files', blob);
        formData.append('idSession', idSession);
        formData.append('pathSession', pathSession);
        formData.append('idAudio', idAudio);
        formData.append('fileNameAudio', name);
        formData.append('isTranslateNow', isTranslate);
        // thời gian chờm các file
        formData.append('seconds', overlap);
        if (fistBlob) {
          formData.append('type', "0");
          postService.post('fileAudio/uploadFileMicro', formData).subscribe(
            (resp) => {
              console.log(resp);
              if (resp.status !== 1) {
                _self.abortRecording();
                alert('error');
                return;
              }
              idAudio = resp.data.idAudioParent;
            },
            (err) => {
              alert('Error: ' + err);
            }
          );
          fistBlob = false;
        } else {
          formData.append('type', "1");
          postService.post('fileAudio/uploadFileMicro', formData).subscribe(
            (resp) => {
              console.log(resp);
              if (resp.status !== 1) {
                _self.abortRecording();
                alert('error');
                return;
              }
            },
            (err) => {
              alert('Error: ' + err);
            }
          );
        }
      }
    });

**Comment by vignestion** [comment]
Any update on this issue?

**Comment by thijstriemstra** [comment]
@muaz-khan any idea? also hitting this in videojs-record I think. (https://github.com/collab-project/videojs-record/issues/376)

**Comment by thijstriemstra** [comment]
#505 looks like a similar issue.

**Comment by PhaDuong** [comment]
It seems that MediaStreamRecorder has a problem, I switched to using StereoRecorder instead and it's work for me

**Comment by muaz-khan** [comment]
This is how MediaRecorder API works (internally). I think the METADATA (info) is included on first-chunk only. That's why only first chunk is playable.

You need to concatenate all chunks to play them.

Otherwise we need to stop/start MediaRecorder after every `timeSlice`. So that MediaRecorder setups a fresh instance and creates new chunk with fresh META-info.

PSEUDO (`dev/MediaStreamRecorder.js`):

```javascript
function lopper() {
    recorder = new MediaRecorder(stream, hints);
    recorder.ondataavailable = function(blob) {
          recordRTC.ondataavailable(blob); // send to RecordRTC
          looper(); // it will create a fresh MediaRecorder instance
    };
    recorder.start(9999999999);
    setTimeout(function() {
           recorder.stop(); // stop recorder after every time-slice
    }, timeSlice);
}
```

**Comment by PhaDuong** [comment]
Thanks, ill try your solution.

**Comment by anish2591** [comment]
> This is how MediaRecorder API works (internally). I think the METADATA (info) is included on first-chunk only. That's why only first chunk is playable.
> 
> You need to concatenate all chunks to play them.
> 
> Otherwise we need to stop/start MediaRecorder after every `timeSlice`. So that MediaRecorder setups a fresh instance and creates new chunk with fresh META-info.
> 
> PSEUDO (`dev/MediaStreamRecorder.js`):
> 
> ```js
> function lopper() {
>     recorder = new MediaRecorder(stream, hints);
>     recorder.ondataavailable = function(blob) {
>           recordRTC.ondataavailable(blob); // send to RecordRTC
>           looper(); // it will create a fresh MediaRecorder instance
>     };
>     recorder.start(9999999999);
>     setTimeout(function() {
>            recorder.stop(); // stop recorder after every time-slice
>     }, timeSlice);
> }
> ```

@muaz-khan Do you have any recommendation on how to combine the chunks to be able to play the entire video? I tried using ffmpeg and it doesn't work.

**Comment by aisnote** [comment]
>>


function lopper() {
    recorder = new MediaRecorder(stream, hints);
    recorder.ondataavailable = function(blob) {
          recordRTC.ondataavailable(blob); // send to RecordRTC
          looper(); // it will create a fresh MediaRecorder instance
    };
    recorder.start(9999999999);
    setTimeout(function() {
           recorder.stop(); // stop recorder after every time-slice
    }, timeSlice);
}

**Comment by aisnote** [comment]
> > >
> 
> function lopper() { recorder = new MediaRecorder(stream, hints); recorder.ondataavailable = function(blob) { recordRTC.ondataavailable(blob); // send to RecordRTC looper(); // it will create a fresh MediaRecorder instance }; recorder.start(9999999999); setTimeout(function() { recorder.stop(); // stop recorder after every time-slice }, timeSlice); }

this will lost some chunk?
