### ISSUE TITLE
RecordRTC , type:MediaStreamRecorder, timeSlice: 5000 calling onDataAvailable 2 times on each timeslice causing corrupted data

### ISSUE THREAD

**Issue by nileshsargar** [muaz-khan/RecordRTC#540]
let recordrtc = require('recordrtc');
                this.recorder = recordrtc(this.stream, {
                    recorderType: MediaStreamRecorder,
                    type: 'audio',
                    mimeType: 'audio/webm',
                    bitsPerSecond: 256 * 8 * 1024,
                    checkForInactiveTracks: false,
                    timeSlice: 5000,
                    ondataavailable: this.onChunkAvailable
                });

This code behaving differently for users, few users getting data on each 5 sec timeslice, but few getting data 2 times per 5 sec timeslice which is corrupted and duplicate data.

**Comment by IsmaeelHaider** [comment]
Hi. I am facing the same issue. If you find any solution do let me know as well and If i find anything I'll keep you posted.

**Comment by muaz-khan** [comment]
@nileshsargar All users are using Chrome/Firefox?

**Comment by IsmaeelHaider** [comment]
Yes.

**Comment by nileshsargar** [comment]
Apologies from my part, my code was calling the "startRecording()" api twice for one user, like user who is sending the command "startRecording" for each participant, getting called twice, I have resolved it, there was no bug for atleast me.
