### ISSUE TITLE
"GET https://cdn.webrtc-experiment.com/gif-recorder.js net::ERR_NAME_NOT_RESOLVED"

### ISSUE THREAD

**Issue by CarolineChaudey** [muaz-khan/RecordRTC#542]
It looks like your CDN is no longer accessible.
What happened ? Is there a way to download the cdn content ?

**Comment by muaz-khan** [comment]
The files you mentioned can be found in this directory:
* https://github.com/muaz-khan/RecordRTC/tree/master/libs

All the files from CDN are open-sourced. At least in this repo: https://github.com/muaz-khan/WebRTC-Experiment

_PS. DNS (A/CName propagation) is having issues. I'm working on fixing it._

**Comment by CarolineChaudey** [comment]
Thank you, I used the cdn sources so my app can still record the next time the cdn has a problem.
You were quick fixing it ;)
