### ISSUE TITLE
Video Not working in safari

### ISSUE THREAD

**Issue by pankaj1989** [muaz-khan/RecordRTC#56]
Hi please suggest this video is not working in safari  how to resolve it

**Comment by muaz-khan** [comment]
Neither webm, nor webp; including getUserMedia and MediaStream ------ all these API are not available in Safari. So, RecordRTC can't work in Safari or <=IE11.

**Comment by arunkamboj** [comment]
Hi can you please tell me any other alternative for IE.

**Comment by zang** [comment]
@arunkamboj , Chrome and Firefox.
