### ISSUE TITLE
Webrtc conference call recording using recordrtc

### ISSUE THREAD

**Issue by MusabBasheer** [muaz-khan/RecordRTC#563]
'm building new application using Angular 7 and WebRTC,and I use recordRTC.js to recording (audio&video) my issue is when I record multiple streams only audio of first stream is recorded.

      public addStreamToRecorder(stream: MediaStream) 
     {
       if (!this.recorder) 
     {
      this.recorder = RecordRTC([stream],{type: "video"});
      this.recorder.startRecording();
     } 
     else 
     {
      this.recorder.getInternalRecorder().addStreams([stream]);
      }
    }
after investigation i found that appendStreams function in reocrdrtc not mix audios

**Comment by MusabBasheer** [comment]
I fixed this issue by updating  appendStreams  function with latest version in MultiStreamRecorder

**Comment by aditya2337** [comment]
@MusabBasheer how do you update the appendStreams function?

**Comment by MusabBasheer** [comment]
@aditya2337

**Comment by MusabBasheer** [comment]
@aditya2337  [Please see this link](https://stackoverflow.com/questions/58166881/webrtc-conference-call-recording-using-recordrtc/58215865#58215865)

**Comment by methodbox** [comment]
@MusabBasheer 
Can you please give a detailed explanation of how you solved this? 

I have a Jitsi Meet instance where I need to capture WebRTC peer audio - i.e. participants in a conference call - and I can't seem to make this work.

I've tried `captureStream` on the audio elements of the participants, but it just ends up destroying the source audio (the audio dies even in the call).

I've also tried this, note that the iframe is on the same server so I *am* able to access the audio elements:

```js
    const combinedStream = new MediaStream();
    let iframe = document.querySelector("iframe");
    let participantAudioNode = iframe.contentWindow.document.querySelector(
      "audio"
    );
    const audioContext = new AudioContext();
    const participantSourceAudio = audioContext.createMediaElementSource(
      participantAudioNode
    );

    // The media element source stops audio playout of the audio element.
    // Hook it up to speakers again.
    participantSourceAudio.connect(audioContext.destination);

    // Hook up the audio element to a MediaStream.
    const dest = audioContext.createMediaStreamDestination();
    participantSourceAudio.connect(dest);

    const participantAudioTrack = dest.stream.getAudioTracks()[0];

    combinedStream.addTracks(participantAudioTrack);
```

Other tracks added via `navigator.mediaDevices.getUserMedia` and `...getDisplayMedia` (for video) work fine, but the participant audio still does nothing.

**Comment by DevJhns** [comment]
@MusabBasheer thx for fix, it worked!
But I tested out weird bug, affecting audio record
1) Connect 2 participants, start record
2) connect third participant
3) disconnect second
4) connect new one

and u get like x10 speed or silence sometime...

**Comment by ashwini-springct** [comment]
@https://github.com/MusabBasheer

I am using MultiStreamRecorder still not able to capture audio in conference call. here is what I am doing. Can you please point out what am I missing here -

 var config = {
        mimeType: 'video/webm', // vp8, vp9, h264, mkv, opus/vorbis
        audioBitsPerSecond : 256 * 8 * 1024,
        videoBitsPerSecond : 256 * 8 * 1024,
        bitsPerSecond: 256 * 8 * 1024,  // if this is provided, skip above two
        checkForInactiveTracks: true,
        timeSlice: 1000, // concatenate intervals based blobs
        ondataavailable: function() {} // get intervals based blobs
      }
let recorder = new MultiStreamRecorder(screen, config);
let mixer = recorder.getMixer();
mixer.appendStreams(audioStream);
recorder.stop(function(blob) {
     var file = new File([blob], 'video.webm', {
            type: 'video/webm'
     });
    invokeSaveAsDialog(file, file.name);
});

**Comment by VidhiShah1569** [comment]
Hey there,

Thanks for the solution.
Is it  possible to record a call using this?

TIA
