### ISSUE TITLE
Can't change aspect ration to 16:9

### ISSUE THREAD

**Issue by napalias** [muaz-khan/RecordRTC#565]
Can't record video at 640x380 resolution 16:9. I can  record only at 640x480 and aspect ratio 4:3. 

```js
recorder = RecordRTC(camera, {
            type: 'video',
            width : 640,
            height: 360
        });
```

**Comment by napalias** [comment]
I found why do not work for me:

need add constrains to:
```js
 navigator.mediaDevices.getUserMedia({ 
            audio: true, 
            video: { width: 1280, height: 720 }        
 })
```

admin with 640x360 this ratio do not works

**Comment by cristisocialboost** [comment]
@napalias I have the same issue, this is my code but the recorder do not want to record the video as 720p, the recorded video is made on 480p. Can you help me to understand why this does not have any effect?

navigator.mediaDevices.getUserMedia({
                        audio: true,
                        video: {
                            minHeight: 720,
                            minWidth: 1280,
                            maxHeight: 1080,
                            maxWidth: 1920,
                            height: 720,
                            width: 1280,
                        },
                    }).then(async function(stream)
                    {
                        recorder = RecordRTC(stream, {
                            type: 'video',
                            height: 720,
                            width: 1280,
                        });

                        recorder.startRecording();
                        recorder.stream = stream;
                       
                    });
                });
            }
