### ISSUE TITLE
CanvasRecording doesn't work on firefox

### ISSUE THREAD

**Issue by muthusmkmtp** [muaz-khan/RecordRTC#57]
@muaz-khan 
On using CanvasRecording in firefox , When I click start recording it throws an error in console like "The UA cannot provide the codec or recording option that has been requested". 
This occurs on creating a new MediaRecorder, where the stream is of "CanvasCaptureMediaStream "
Could you suggest me a solution??

P.S : I enabled the value to true for 'canvas.capturestream.enabled' in about:config. So that's not a problem.

**Comment by muaz-khan** [comment]
It works now.

**Comment by danieltaborda** [comment]
Hi, this is still a problem.
And is related to the MediaRecorder inside Firefox in true its a bug more related to Firefox, if you even can record try to resize your recording window or moving it to other screen, and you will see the even onerror from the MediaRecorder.
It need to be reported, but is not really related to the lib, nice work there, if you may have any clues about tell me something!

cheers, 
Daniel
