### ISSUE TITLE
What is "real MediaStream object, that is passed over RecordRTC" ? I get 'ERROR TypeError: Failed to construct 'MediaRecorder': parameter 1 is not of type 'MediaStream' with Agora stream'

### ISSUE THREAD

**Issue by ishwara-bhat** [muaz-khan/RecordRTC#586]
Hi,
I am using Agora service which I guess uses WebRTC internally. It returns stream object.

            this.agoraService.client.on('stream-published', function (evt) {
                console.log("Publish local stream successfully");

When I try to create MediaRecorder using it, 
const mediaRecorder = new MediaRecorder(evt.stream, { mimeType: 'video/webm' });

I get error - ERROR TypeError: Failed to construct 'MediaRecorder': parameter 1 is not of type 'MediaStream'. 

But the API works if I do it with the stream returned from GetUserMedia() API.

Question:- In issue#130 (https://github.com/muaz-khan/RecordRTC/issues/130), I saw that 'the stream object has to be 'real'. What exactly is real?
Any suggestions on how I should tap the stream from Agora returned stream handle? Since this is more on WebRTC side in my unique usecase, they are unable to help.

Log of the stream object (from Agora) looks like it is properly formed object:-
av-session.ts:302 {dispatcher: {…}, addEventListener: ƒ, hasListeners: ƒ, on: ƒ, removeEventListener: ƒ, …}dispatcher: {eventListeners: {…}}addEventListener: ƒ (t,n)hasListeners: ƒ (t)on: ƒ (t,n)removeEventListener: ƒ (t,n)dispatchEvent: ƒ (t)dispatchSocketEvent: ƒ (t)params: {streamID: 3096665285, audio: true, cameraId: null, microphoneId: null, video: true, …}stream: MediaStream {id: "uwsNgd6v5ksUy6tIrItSoxYwKoL8BpniiJFa", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}url: undefinedonClose: ƒ ()local: truevideoSource: undefinedaudioSource: undefinedvideo: trueaudio: truescreenAttributes: {width: 1920, height: 1080, maxFr: 5, minFr: 1}videoSize: (4) [640, 480, 640, 480]player: {dispatcher: {…}, addEventListener: ƒ, hasListeners: ƒ, on: ƒ, removeEventListener: ƒ, …}audioLevelHelper: nullattributes: {resolution: "1280x720", minFrameRate: 30, maxFrameRate: 30, minVideoBW: 120, maxVideoBW: 1710}microphoneId: nullcameraId: nullinSwitchDevice: falseuserMuteVideo: falseuserMuteAudio: falsepeerMuteVideo: falsepeerMuteAudio: falselowStream: nullvideoWidth: 1280videoHeight: 720streamId: 3096665285userId: 3096665285mirror: trueDTX: undefinedaudioProcessing: undefinedhighQuality: falsestereo: falsespeech: falseinitialized: trueaudioMixing: {audioContextInited: false, defaultVolume: 100, inEarMonitoring: "FILE", sounds: {…}, states: {…}, …}_initSoundIfNotExists: ƒ (t,n)loadAudioBuffer: ƒ (t,n,i)createAudioBufferSource: ƒ (t)clearAudioBufferSource: ƒ ()_isSoundExists: ƒ (t)_initAudioContext: ƒ ()_cleanupAudioMixing: ƒ ()_reloadInEarMonitoringMode: ƒ (t)_startAudioMixingBufferSource: ƒ (t)_stopAudioMixingBufferSource: ƒ (t)_flushAudioMixingMuteStatus: ƒ (t)_handleAudioMixingInvalidStateError: ƒ (t,n,i)_handleAudioMixingNoSourceError: ƒ (t,n,i)_getOneEffectStates: ƒ (t)_audioMixingFinishedListener: ƒ ()_playOneEffect: ƒ (t,n)_stopOneEffect: ƒ (t,n)_pauseOneEffect: ƒ (t,n)_resumeOneEffect: ƒ (t,n)_getOneEffectDuration: ƒ (t)_getOneEffectCurrentPosition: ƒ (t,n)_setOneEffectPosition: ƒ (t,n,i)startAudioMixing: ƒ (t,n)stopAudioMixing: ƒ (t)pauseAudioMixing: ƒ (t)resumeAudioMixing: ƒ (t)adjustAudioMixingVolume: ƒ (t)getAudioMixingDuration: ƒ ()getAudioMixingCurrentPosition: ƒ ()setAudioMixingPosition: ƒ (t,n)playEffect: ƒ (t,n)stopEffect: ƒ (t,n)stopAllEffects: ƒ (t)preloadEffect: ƒ (t,n,i)unloadEffect: ƒ (t,n)pauseEffect: ƒ (t,n)pauseAllEffects: ƒ (t)resumeEffect: ƒ (t,n)resumeAllEffects: ƒ (t)getEffectsVolume: ƒ ()setEffectsVolume: ƒ (t,n)setVolumeOfEffect: ƒ (t,n,i)videoConstraint: {width: 1280, height: 720, frameRate: {…}}audioConstraint: {}screenConstraint: {mediaSource: "screen", width: 1920, height: 1080, frameRate: {…}}setVideoResolution: ƒ (n)setVideoFrameRate: ƒ (n)setVideoBitRate: ƒ (n)setScreenBitRate: ƒ (n)setScreenProfile: ƒ (t)setVideoProfileCustom: ƒ (t)setVideoProfileCustomPlus: ƒ (n)setVideoProfile: ƒ (n)setAudioProfile: ƒ (t)setVideoEncoderConfiguration: ƒ (t)getSupportedProfile: ƒ (t)getId: ƒ ()getUserId: ƒ ()setUserId: ƒ (e)getAttributes: ƒ ()hasAudio: ƒ ()hasVideo: ƒ ()hasScreen: ƒ ()isVideoOn: ƒ ()isAudioOn: ƒ ()init: ƒ (i,o)reloadDeviceName: ƒ ()close: ƒ ()enableAudio: ƒ ()disableAudio: ƒ ()enableVideo: ƒ ()disableVideo: ƒ ()unmuteAudio: ƒ ()muteAudio: ƒ ()unmuteVideo: ƒ ()muteVideo: ƒ ()_unmuteAudio: ƒ ()_isAudioMuted: ƒ ()_muteAudio: ƒ ()_unmuteVideo: ƒ ()_muteVideo: ƒ ()addTrack: ƒ (i)removeTrack: ƒ (n)setAudioOutput: ƒ (e,n,i)play: ƒ (e,n,i)stop: ƒ ()isPlaying: ƒ ()isPaused: ƒ ()resume: ƒ ()getVideoTrack: ƒ ()getAudioTrack: ƒ ()_replaceMediaStreamTrack: ƒ (e,n,i)replaceTrack: ƒ (e,i,o)setAudioVolume: ƒ (e)getStats: ƒ (e,n,i)_getPCStats: ƒ (e)getAudioLevel: ƒ ()profile: "720p_3"_switchVideoDevice: ƒ (e,n,i)_switchAudioDevice: ƒ (e,n,i)switchDevice: ƒ (e,n,i,o)videoName: "Integrated Webcam (1bcf:2b8a)"audioName: "Communications - Microphone (Realtek Audio)"elementID: "agora_local"playOptions: undefinedpublishLTS: 1576658684300p2pId: 33918connectionSpec: {audio: true, video: true, screen: undefined, isSubscriber: false, callback: ƒ, …}pc: {uid: undefined, isVideoMute: false, isAudioMute: false, isSubscriber: false, clientId: "AD53D", …}_onAudioUnmute: ƒ ()_onVideoUnmute: ƒ ()_onAudioMute: ƒ ()_onVideoMute: ƒ ()sid: "907ACA145E984406B414A6A3D69FC6E3"uplinkStats: {uplink_fraction_lost: 0, uplink_cumulative_lost: 0, uplink_available_bandwidth: 386122}traffic_stats: {access_delay: 2015}__proto__: Object
core.js:6014

**Comment by ishwara-bhat** [comment]
My issue is solved. Agora RTC uses an object type called Stream for other purposes. I needed to extract tracks from it and construct my MediaStream and then create MediaRecorder from it.

**Comment by mahmednisar** [comment]
How will you please provide snapshot regarding that
