### ISSUE TITLE
`audio/wav` and `audio/mp3` mimeTypes are not supported in Chrome?

### ISSUE THREAD

**Issue by jonsadka** [muaz-khan/RecordRTC#589]
Was there a change in Chrome that removed `mp3` and `wav` support from the MediaRecorder?

 I'm getting the error `MediaRecorder API seems unable to record mimeType: audio/wav` when using Chrome Version 79.0.3945.88 on macOS Catalina.

Calling 
```js
MediaRecorder.isTypeSupported('audio/mp3') // false
MediaRecorder.isTypeSupported('audio/wav') // false
```

### Error
![Screen Shot 2020-01-02 at 10 35 12 AM](https://user-images.githubusercontent.com/6504944/71684896-a3ac5a00-2d4b-11ea-9a31-7c8c6bb84616.png)

### Configuration
```js
RecordRTC(mediaStream, {
  mimeType: 'audio/wav',
  numberOfAudioChannels: isEdge ? 1 : 2,
  type: 'audio',
  checkForInactiveTracks: true,
  ...(isSafari || isEdge ? {recorderType: RecordRTC.StereoAudioRecorder} : {}),
});
```

**Comment by jonsadka** [comment]
@muaz-khan any thoughts on this?

**Comment by muaz-khan** [comment]
Please try (and force) `{recorderType: RecordRTC.StereoAudioRecorder}` on all browsers including Chrome. It will generate `audio/wav`.

You can use mp3 encoders to convert `.wav` into `.mp3`. (You can find such js-encoders on github)

```javascript
recorder = new RecordRTC(mediaStream, {
    type: 'audio',
    recorderType: RecordRTC.StereoAudioRecorder, // force for all browsers
    numberOfAudioChannels: 2
});
```

**Comment by jonsadka** [comment]
Was just reaching that same conclusion after looking at https://github.com/muaz-khan/RecordRTC/blob/master/dev/GetRecorderType.js#L25. 

Thank you for your help and your contributions to this library
