### ISSUE TITLE
RecordRTC-over-Socketio problem

### ISSUE THREAD

**Issue by pitrackster** [muaz-khan/RecordRTC#59]
Hi Muaz,

I'm trying to test this demo project but can't get it work.
`npm install recordrtc-socketio` seems to work
`node ./node_modules/recordrtc-socketio/server.js` tell me that `sys is depcrecated. Use util instead.` but nothing else.

Then I open http://localhost/patrick/webrtcSocketIO/node_modules/recordrtc-socketio/index.html and get 2 errors : 
- RecordRTC.js:1191:5  `TypeError: setting a property that has only a getter` I don't know if this one matters
- recordrtc-socketio:78:17  `ReferenceError: io is not defined` I think this one is the real problem

I'm totally new to NodeJs... Any help ?
Thanks

**Comment by pitrackster** [comment]
Hi,
I figured out some of the problems.

In server.js file : 
- had to change ``` filename = path.join(process.cwd(), uri); ``` to ```filename = process.cwd() + '/node_modules/recordrtc-socketio/';```

- put the block : 

```
 var sys = require('sys'),
    path = require('path'),
    exec = require('child_process').exec;
```
before ``` var app = http.createServer(function (request, response) { ```

- in writeToDisk function, replaced : 
``` fileRootNameWithBase = './uploads/' + fileName ```  
with
``` fileRootNameWithBase = 'node_modules/recordrtc-socketio/uploads/' + fileName ```


Now I've got an FFMPEG error : ffmpeg exited with code 1 (on Chrome)

And now a question... Why Firefox is set to record only audio ? (by the way it is not working on FF because of navigator.getUserMedia not recognized...)

Thanks for any tip...

**Comment by xmclark** [comment]
@pitrackster 
add the adapter.js library to your client side js. This should remove the problems with getUserMedia not recognized.

**Comment by pitrackster** [comment]
@xmclark thanks for the tip !
