### ISSUE TITLE
Webm Firefox video audio is chopped

### ISSUE THREAD

**Issue by pitrackster** [muaz-khan/RecordRTC#62]
Hi,

When I use Firefox to record webcam and audio stream everything is perfect as long as I stay in the Navigator (video plays through <video> tag) .
But when I download (or upload) the .webm file, the audio part is chopped... (using VLC)

Is it due to the encoding library ? Any other Idea ?

Thanks

**Comment by xmclark** [comment]
I've also noticed this too: the download webm comes out not that great, but in the browser it is fine.

**Comment by KristjanLiiva** [comment]
I am also having this issue.
Does anyone know a solution?

**Comment by muaz-khan** [comment]
Chrome Canary with this flag enabled `chrome://flags/#enable-experimental-web-platform-features` seems working great. Which is not only keeping the video quality; but also no audio sync or echo issues.

Firefox seems working great if we increase time interval `mediaRecorder.start(3 * 1000)`. Currently RecordRTC is using `1 millisecond` to get accurate output on calling `stopRecording`. Here word **accurate** is referring **recording-duration**.

Ref: [dev/MediaStreamRecorder.js#L151-L156](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js#L151-L156)

**Comment by pitrackster** [comment]
Hi muaz-khan,

I'm not sure to understand what your solution is.

I changed ```mediaRecorder.start(1)``` to  ```mediaRecorder.start(3000)``` in RecordRTC.js (~ l. 1551).

When I play the video inside the web browser there is no problems. But the recorded file played in VLC still have chopped audio.

Any idea ?
Thanks.
