### ISSUE TITLE
Timeslices in Safari 13

### ISSUE THREAD

**Issue by taylerz** [muaz-khan/RecordRTC#638]
@thijstriemstra asked to open a ticket and provide a link to the original issue as filed under videojs recorder. Timeslices does not work when using Safari 13. See below. Thanks.

https://github.com/collab-project/videojs-record/issues/485

**Comment by taylerz** [comment]
This issue is fixed in Safari Technology Preview 111, and presumably in Safari 14 when it's released this fall with Mac OS Big Sur.

**Comment by thijstriemstra** [comment]
@taylerz I assume you tested this? Bonus points: a link to the webkit ticket/commit where it's fixed..

**Comment by taylerz** [comment]
This was tested and confirmed as working on this page: https://www.webrtc-experiment.com/RecordRTC/simple-demos/ondataavailable.html
