### ISSUE TITLE
How to difine audio type in MRecordRTC

### ISSUE THREAD

**Issue by niravjgandhi** [muaz-khan/RecordRTC#64]

**Comment by muaz-khan** [comment]
```html
<script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
<script src="https://cdn.rawgit.com/webrtc/adapter/master/adapter.js"></script>

<script>
var recordRTC;

function successCallback(stream) {
    // RecordRTC usage goes here

    var options = {
         recorderType: StereoAudioRecorder // force WAV for all browsers
    };
    recordRTC = RecordRTC(MediaStream, options);
    recordRTC.startRecording();
}

function errorCallback(errror) {
    // maybe another application is using the device
}

var mediaConstraints = { audio: true };

navigator.mediaDevices.getUserMedia(mediaConstraints).then(successCallback).catch(errorCallback);

btnStopRecording.onclick = function () {
    recordRTC.stopRecording(function (wavURL) {
        audio.src = wavURL;

        var recordedBlob = recordRTC.getBlob();
        recordRTC.getDataURL(function(dataURL) {
              // upload DataURL to server
        });
    });
};
</script>
```

Ref:

* https://github.com/muaz-khan/RecordRTC#recordertype

If you want to use `MRecordRTC` instead, try adding `recorderType:StereoAudioRecorder` here:

* [MRecordRTC.js#L75](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MRecordRTC.js#L75)

E.g.

```javascript
if (this.mediaType.audio) {
    this.audioRecorder = new RecordRTC(mediaStream, {
        type: 'audio',
        bufferSize: this.bufferSize,
        sampleRate: this.sampleRate,
        recorderType: StereoAudioRecorder // force WAV for all browsers
    });
    this.audioRecorder.startRecording();
}
```

**Comment by gdiodati** [comment]
What if i want to force ogg for all browsers?

**Comment by niravjgandhi** [comment]
Thanks, But is there any possibility for "ogg" in all browser because we are developing a software for English language lab and in this i need to record at least 15 mins and 15mins wav become more heavy so if any solution of "ogg" is good for me.

**Comment by muaz-khan** [comment]
Ogg can be recorded both in Firefox and Chrome Canary/Dev. Chrome stable support coming soon.

Currently Chrome (Canary/Dev) requires this flag to be manually enabled: `chrome://flags/#enable-experimental-web-platform-features`

RecordRTC will soon prefer MediaRecorder over StereoAudioRecorder. So default output will always be Ogg.

**Comment by thijstriemstra** [comment]
It's currently not possible to specify the audio and/or video `recorderType` in MRecordRTC. Maybe we can add optional `audioRecorderType` and `videoRecorderType` attributes, I'll look into a PR.

**Comment by mayank6199** [comment]
I recorded video upto 1 min, but it not upload on server. how can i upload large size video ??

**Comment by CarpeNecopinum** [comment]
@mayank6199 (you should have probably posted that as a separate issue).

Assuming you are using PHP on the server side, did you make sure to set `upload_max_filesize` and `post_max_size` in the php.ini of your web server to a size large enough for the videos you are trying to upload?
