### ISSUE TITLE
Changing recording format

### ISSUE THREAD

**Issue by sonnyk22** [muaz-khan/RecordRTC#66]
Great library!

Is there a way to record Audio in any other formats such as .mp3 than the .wav?  If yes, is there a way to also adjusting the Bit Per Second recording for better quality?

**Comment by sonnyk22** [comment]
Found the answer for the first one related .mp3 recording. but cant find info on the BPS saving rate.

**Comment by sonnyk22** [comment]
Found it:

var options = {
      mimeType: 'video/webm', // or video/mp4 or audio/ogg
      audioBitsPerSecond: 128000,
      videoBitsPerSecond: 128000,
      bitsPerSecond: 128000 // if this line is provided, skip above two
    };

**Comment by CoericK** [comment]
@sonnyk22  what whas the answer to record and save as mp3?
