### ISSUE TITLE
StereoAudioRecorder: Byte rate calculation is incorrect.

### ISSUE THREAD

**Issue by marcopennekamp** [muaz-khan/RecordRTC#665]
The StereoAudioRecorder uses the wrong formula to calculate byte rate: https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L261

Since the sample size is 16 bits, for files with two or more channels, the byte rate should be `sampleRate * numberOfAudioChannels * 16/8`. Also see here: http://www.topherlee.com/software/pcm-tut-wavformat.html. The calculation in StereoAudioRecorder erroneously omits the number of channels.

This effectively leads to a playback issue in Chrome. Recording a 2-channel WAV file with RecordRTC results in a WAV that reports half its real byte rate. As Chrome seems to utilize the byte rate in its implementation of skipping, skipping ahead in a 10-second 2-channel WAV will result in a total length of up to 20 seconds reported in the audio player. The file will not actually play for 20 seconds, but, for example, skipping to the 50% point of the audio actually skips to the 25% point of the broken WAV file and then keeps playing the file until the end, ultimately reporting 12.5 seconds total time. This means that a WAV produced by RecordRTC can't be comfortably skipped through with Chrome.

To see this issue for yourself, unzip and try the two attached files in Chrome. The first one is a file produced with RecordRTC, which has the wrong byte rate. Even though it is only 4 seconds long, opening it with Chrome allows me to "achieve" a total length of 8 seconds. Skipping is also broken. The second file is the same WAV file, just with a fixed byte rate edited with a hex editor. You can see that this file works perfectly in Chrome.

[wavs.zip](https://github.com/muaz-khan/RecordRTC/files/5069158/wavs.zip)

**Comment by tiku91** [comment]
This fixes an issue, which I am also having, thank you.
I hope this gehts merged soon.

**Comment by saadena2** [comment]
Hello muaz , i hope i can record a real mp3 audio file , i am using this library but its result is .ogg sound file 
could you help me to generate real mp3 file

**Comment by marcopennekamp** [comment]
Fixed by #671.
