### ISSUE TITLE
Recorded video is slow to seek

### ISSUE THREAD

**Issue by farukhzahoor** [muaz-khan/RecordRTC#679]
Thanks for the API. I am facing one issue. Video is recorded using RecordRTC and seekableBlob is transferred to Amazon S3. When I playback video and seek at the end of video it takes lot of time until video buffer reach to that seek point. Other videos which are not recorded from RecordRTC seek quickly to the end of file and start taking buffers from seek point. Please help...

**Comment by farukhzahoor** [comment]
I was able to achieve it using mimeType: 'video/x-matroska;codecs=avc1'

**Comment by dengshicheng1996** [comment]
> 我能够使用 mimeType: 'video/x-matroska;codecs=avc1' 实现它

那您是否在使用avc1 编码 的时候产生视频合成的问题？ 我在采用 'video/x-matroska;codecs=avc1' 时，用FFmpeg 合成视频，产生了快进、或者丢失部分blob 的情况。我知道是因为该数据不带有PPS/SPS、起始码，那么我如何才能生成一个好的视频？
