### ISSUE TITLE
Fails to record when mouse is held down

### ISSUE THREAD

**Issue by oodavid** [muaz-khan/RecordRTC#68]
I've created a simple canvas "app" that draws onmousemove; however, when holding the mouse DOWN, RecordRTC fails to record properly, see example output:

https://www.youtube.com/watch?v=Y_Mn0bJSwPo

Tested in Chrome, Canvas not supported in Firefox ;-)

**Comment by oodavid** [comment]
The same issue occurs when holding non-modifier keys down.

For example holding "a" while recording will also trigger the problem.

**Comment by Geraden07** [comment]
I'm seeing the same issue as well. @muaz-khan has any investigation been done yet on this?

**Comment by muaz-khan** [comment]
Please refer this:

* https://github.com/muaz-khan/RecordRTC/tree/master/Canvas-Recording#record-canvas

```html
<script src="https://cdn.webrtc-experiment.com/RecordRTC/Whammy.js"></script>
<script src="https://cdn.webrtc-experiment.com/RecordRTC/CanvasRecorder.js"></script>
<canvas></canvas>
<script>
var canvas = document.querySelector('canvas');
var recorder = new CanvasRecorder(window.canvasElementToBeRecorded, {
    disableLogs: false,
    showMousePointer: true // optional; used only for NON-CANVAS elements
});

// start recording <canvas> drawings
recorder.record();

// a few minutes later
recorder.stop(function(blob) {
    var url = URL.createObjectURL(blob);
    window.open(url);
});
</script>
```

**Comment by muaz-khan** [comment]
This issue seems fixed only in Canary.

**Comment by oodavid** [comment]
Can confirm fixed in Chrome and Canary :)
