### ISSUE TITLE
Please link: https://www.webrtc-experiment.com/screenshot.js ERROR in Crome Console

### ISSUE THREAD

**Issue by hiren3897** [muaz-khan/RecordRTC#681]
I am trying to record animation overlayed over video element using RecordRTC in Angular 9 but when I start recording it gives me an error of "Please link: https://www.webrtc-experiment.com/screenshot.js"

![Screenshot from 2020-09-28 14-37-45](https://user-images.githubusercontent.com/59652404/94433194-39203180-0198-11eb-991b-27315641bc7e.png)
 You can see the error in the above image 

my code
 `play = () => {
    const square = new Square(this.ctx);
    this.squares = this.squares.concat(square);
    // this.draw();
    const recorder = new RecordRTC(this.canvas.nativeElement, {
      type: 'canvas',
      mimeType: 'video/webm\;codecs=h264'
    });
    recorder.startRecording();

    recorder.stopRecording(() => {
      const recordedBlobs = recorder.getBlob();
      const url = URL.createObjectURL(recordedBlobs);
      console.log(url);
      const file = new File([recordedBlobs], 'video.mp4', {
        type: 'video/mp4'
      });
      invokeSaveAsDialog(file, 'test');
    });
  }`
@muaz-khan

**Comment by hiren3897** [comment]
@muaz-khan How can i add screensort.js to my angular.json or install in my angular project to fix this issue

**Comment by mhackeras** [comment]
Wonder why is this closed?
I am getting this in my vue.js project.

**Comment by hiren3897** [comment]
> Wonder why is this closed?
> I am getting this in my vue.js project.

Hello there!
[](https://www.webrtc-experiment.com/screenshot.js)
I solved this with a quick hack by creating screensort.js and copy-paste the content for the above website
by configuring it in my angular project my error was resolved 
I hope is works for you as well. cheers

**Comment by MoukimHF** [comment]
Hello  @hiren3897 I just added this script to the project and it was solved 
https://www.webrtc-experiment.com/EBML.js

**Comment by RacketyWater7** [comment]
@hiren3897 
For me, its creating a lot of errors in the screenshot.js file. What I did is I created this file in the same directory as the file where I'm using it and imported it like:  ```import "./screenshot.js"``` and its showing a lot of errors in the screenshot.js file. :(
some are below:
![image](https://user-images.githubusercontent.com/52341921/173001167-34d9475c-4bac-446b-bed3-f42166264084.png)

**Comment by nhhai1605** [comment]
@RacketyWater7 
I fixed it by adding `<script src="https://www.webrtc-experiment.com/screenshot.js"></script>`
