### ISSUE TITLE
Video too slow on high solution. Canvas problem? How screencastify can do it?

### ISSUE THREAD

**Issue by vuanhduy1** [muaz-khan/RecordRTC#69]
At 320x240 RecordRTC can record 12-15 frame/sec. At 640x360, It work at 5-7 frame/sec. And at 1280x720, It work at 2-3 frame/sec. It's too slow. 
I think it's the limit of canvas which Whammy are using. Anyone know how to solve this problem. I find that screencastify  use other solution to save video with maximum 30 fram/sec. Anyone have idea about this?

Thank you for any comments & suggestion.

**Comment by muaz-khan** [comment]
MediaRecorder API are implemented in Chrome Canary/Dev however still behind a flag. These API seems solving all such issues.

Canvas2D can NEVER be used in WebWorker or non-DOM threads; that's why it is really very hard to not only keep the quality but also handle performance issues.

Chrome extension APIs are having `chrome.tabs.captureVisibleTab` which returns PNG or JPEG. One can convert such formats into WebP to use with `Whammy.js`.

**Comment by vuanhduy1** [comment]
Thanks @muaz-khan for your comments. Do you have any ideas on screencastify https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en which also use desktopCapture but it can record high resolution screen with 30 frame/sec?

**Comment by vhmth** [comment]
For anyone stumbling across this who's working on Chrome Extension to record a tab screen, I tried getting this working by taking regular tab captures using [chrome.tabs.captureVisibleTab](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab), but the performance was really bad when the screen got larger.

Essentially I took a tab capture every `1000 / FPS`, saved those blob URLs in an array, looped through the array and converted those blobs to `webp` format, and then threw that into [Whammy](https://github.com/antimatter15/whammy). The capturing of the frames was what actually showed a noticeable slowdown on the page. The stringing together of the frames took a while but did not seem to slow the browser down considerably. Although the video size was untenably large for any screen captures over a few seconds (~ `2MB` for about 3-4 seconds of video full width/height on a retina 13" MacBook Pro).

I have surrendered to the idea that, in this situation with trying to record a video MediaStream in Chrome (with good quality), you should take advantage of a WebRTC Media Server. Currently looking into [Janus](https://github.com/meetecho/janus-gateway), but there are other supposedly good ones like [Kurento](https://github.com/Kurento/kms-core).

**Comment by vhmth** [comment]
Also @muaz-khan thank you so much for all the work you've done with WebRTC. It's incredible, and I greatly appreciate it. If you're ever in the San Francisco Bay Area, please feel free to reach out and I would be happy to get you lunch/dinner/alcohol/whatever. My twitter handle is [@vhmth](https://twitter.com/vhmth).
