### ISSUE TITLE
Is it possible to change video capture resolution in RecordRTC?

### ISSUE THREAD

**Issue by stevemccann** [muaz-khan/RecordRTC#7]
Is it possible to specify the resolution of video captured with RecordRTC? I do not currently see it as a parameter to be passed in any of the methods.

**Comment by unmanner89** [comment]
Muaz, hello!

How to record with a max camera resolution?
It's possible to limit **height** only?

The different cameras have a different resolution and proportions of result video is broken..

**Comment by muaz-khan** [comment]
AFAIK, **capturing** and **recording** are two different terms. Capturing means, accessing a media (device or file) however recording means, processing RAW-data coming from that media source and storing somewhere in the system.

RecordRTC isn't handling getUserMedia part. You can use `maxWidth:1920` and `maxHeight:1080` to let chrome chose best possible resolution available in the capturing device.

RecordRTC relies on [Whammy.js](http://recordrtc.org/WhammyRecorder.html) for video encoding, which captures Data-URIs (DataURL) from Canvas2D. Now all Canvas2D limitations applies e.g. performance issues, only visible area can be captured/drawn/recorded, etc.

If you capture a video using 720p or 1080p and then use same resolutions for `canvas` parameter,then you'll see a better output. However, recording process will be many times slower and hanging comparing normal 320p or 280p.

It isn't possible to handle DOM elements in the WebWorkers, so it'll be still slow until MediaRecorder API are implemented in the Chrome.

**Comment by unmanner89** [comment]
Thank you for you reply!

Now I got the max resolution by getUserMedia call with:

```
var mediaConstraint = {
    video: {
        mandatory: {
            maxHeight: 720,
            maxWidth: 1280
        },
        optional: [
            {minWidth: 320},
            {minWidth: 640},
            {minWidth: 960},
            {minWidth: 1024},
            {minWidth: 1280}
        ]
    },
    audio: true
};
```

**Comment by unmanner89** [comment]
I agree with you, Muaz!

720p canvas size leads to twitches on a video file (real webm file).

May be it is possible to get ride on twitches by change quality of capture, or some one else performance tweaks do you know?

**Comment by muaz-khan** [comment]
1. Capture 720p or 1080p video along with minFrameRate+maxFrameRate==30 using getUserMedia
2. Record using MediaStreamRecorder; pass huge videoBitsPerSecond or bitsPerSecond

**Comment by saitejad** [comment]
How to increase the quality of audio? I am using RecordRTC and Angular4
