### ISSUE TITLE
PHP-and-FFmpeg is not supported in Mozilla firefox.

### ISSUE THREAD

**Issue by Amarjit1234** [muaz-khan/RecordRTC#71]

**Comment by bkuehhnle** [comment]
I'd like to second this!  I've been trying to build a workaround but not getting very far; it would be nice to use the same code cross browser (FF and Chrome at least).

This if condition in the sample index.html file prevents Firefox from uploading, but ther is no `else` condition.

`       if (!isFirefox) {
            recordAudio.stopRecording(function() {
                document.querySelector('h1').innerHTML = 'Got audio-blob. Getting video-blob...';
                recordVideo.stopRecording(function() {
                    document.querySelector('h1').innerHTML = 'Uploading to server...';
                    PostBlob(recordAudio.getBlob(), recordVideo.getBlob(), fileName);
                });
            });
        }`
