### ISSUE TITLE
Pause only audio recording.

### ISSUE THREAD

**Issue by changbenny** [muaz-khan/RecordRTC#73]
I found that `stopRecording` will pause both audio and video recording.
Does RecordRTC supports the feature to pause only audio recording (the video is recording normally)?

**Comment by muaz-khan** [comment]
`pause` method in the `MediaRecorder` API doesn't supports pausing single track. Even specs doesn't have such features.

So, RecordRTC isn't supporting this feature.

What you can do is, disable or mute the audio track(s):

```javascript
audioVideoStream.getAudioTracks().forEach(function(track) {
    track.enabled = false;
});
```

Blank (audio) buffers will be still appended to the resulting blob.

**Comment by changbenny** [comment]
@muaz-khan Thanks for supporting.
