### ISSUE TITLE
Record video using Webrtc and save directly to Youtube or vimeo

### ISSUE THREAD

**Issue by nairmahesh** [muaz-khan/RecordRTC#74]
How do we record directly from browser and save it to youtube or vimeo account

**Comment by bkuehhnle** [comment]
That would be pretty awesome for my customer's needs.

**Comment by abureviewer3** [comment]
Is it any possible to upload the recording to the youtube? Kindly help me.

**Comment by muaz-khan** [comment]
`index.html` demo file now supports uploading to YouTube.
