### ISSUE TITLE
incorrect field in wav-file header

### ISSUE THREAD

**Issue by jpmarten** [muaz-khan/RecordRTC#76]
Dear Muaz

I am using your recordRTC module under Chrome to record and to upload monophonic wav-files to a server. Starting from your demo it was easy to  construct a working system. I constructed recordRTC with leftChannel = true, and I got wav-files with one channel audio as desired. I could also read these files in Matlab, but on the other hand, Windows Media Player did not want to play them. I started a small investigation and I noticed that one of the fields of the RIFF header was incorrect. The following is a hex dump of this header:

52 49 46 46 2C E0 01 00 57 41 56 45 66 6D 74 20  RIFF,...WAVEfmt 
10 00 00 00 01 00 01 00 80 BB 00 00 00 EE 02 00  ................
02 00 10 00 64 61 74 61 00 E0 01 00 00 00 00 00  ....data........

What you see is that bytes 29-32 = 00 EE 02 00 = sampleRate * 16 * 2 / 8 which implies that there are 2 channels recorded and present in the file. The bytes should be 00 77 01 00, which is equal to 2 times the sampleRate (bits 25-28). The problem is solved (I tested it) by replacing line 1877 in recordRTC, which was  "view.setUint32(28, sampleRate * 4, true);"  by  "view.setUint32(28, sampleRate * 2 * numberOfAudioChannels, true);"

I hope this correction will find its way to the official version of the module.

Best
Jean-Pierre Martens (Ghent University)

**Comment by jpmarten** [comment]
Dear Muaz

 

Thanks for fixing this! For the rest your recordRTC does a great job!

 

Jean-Pierre

**Comment by rajengla** [comment]
@muaz-khan @jpmarten had suggested setting byte rate (block align) based on the number of channels used. According to this http://wavefilegem.com/how_wave_files_work.html 

- **block align** (in bytes) = (bit_rate * number_of_channels)/8, and
- **byte rate** = block_align * sample_rate
