### ISSUE TITLE
WebRTC too large data size

### ISSUE THREAD

**Issue by Amarjit1234** [muaz-khan/RecordRTC#81]
Hello Muaz,
Can you please help me.
Is there any way to reduce the size of audio and video recording size. Because it take too much time to upload in the server.

**Comment by muaz-khan** [comment]
For Chrome Canary, you can enable a flag for MediaRecorder API; and then, it will be no file sizing or quality issues there. RecordRTC will finally switch to this method, as soon as it gets out of flag.

For current Chrome stable, to record audio, you can pass `numberOfAudioChannels:1`:

* https://github.com/muaz-khan/RecordRTC#numberofaudiochannels

You can even set low-buffferSize value to reduce number of buffers to be encoded, to get smaller WAV:

* https://github.com/muaz-khan/RecordRTC#buffersize

MacOSX/Linux (not-Windows) allows you specify sampleRate as well:

* https://github.com/muaz-khan/RecordRTC#samplerate

To record video in Chrome, you can pass `frameInterval:200`:

* https://github.com/muaz-khan/RecordRTC#frameinterval

Video size depends upon following factors:

1. Frames per second i.e. `frameInterval`
2. Canvas and video [width/height](https://github.com/muaz-khan/RecordRTC#how-to-set-video-widthheight)
3. Whether mediastream is full-HD (1080p) or SD (360p).

**Comment by Amarjit1234** [comment]
Thank you so much Mauz
