### ISSUE TITLE
Recording camera gives empty blob on Firefox Linux, Unknown error is the only log given

### ISSUE THREAD

**Issue by Chosenundead15** [muaz-khan/RecordRTC#828]
Currently I am working on fixing a recording functionality for a webpage and I have found a lot of strange behavior in the library,
![imagen](https://user-images.githubusercontent.com/29759684/204589436-71cd56f9-d234-4252-82b4-92fa5be52949.png)
That error on the screenshot is called, over and over again during the recording which ends with once I stop the recording and no video is made as the blob is empty. To make matters worst, is the same error I get from running the live demo.

**Comment by LetMeDream** [comment]
Excuse me, sir. Could I ask what was your problem here?

**Comment by LetMeDream** [comment]
Hey man, could I ask how did you solve this issue?
