### ISSUE TITLE
Black screen at first 2 seconds of recorded video

### ISSUE THREAD

**Issue by vbaranov** [muaz-khan/RecordRTC#83]
I use Firefox 43.0.4.
I see black screen during first ~2 seconds of recorded video at RecordRTC demo (https://www.webrtc-experiment.com/RecordRTC/).
And I reproduced this with latest version of api.
How to avoid this?

**Comment by zang** [comment]
It works fine on my Mac and win10. Can you share console log and ffprobe info ?
