### ISSUE TITLE
How to make recorded videos smaller while retaining clarity

### ISSUE THREAD

**Issue by hktalent** [muaz-khan/RecordRTC#847]
How to make recorded videos smaller while retaining clarity

I tested on Safari and found that after adjusting the parameters several times, I still get files with a size of>70M per minute. Can you help me see where the problem is?

```
var recorder = RecordRTC(local_media, {
		'type': 'video'
		, 'mimeType': 'video/webm;codecs=h264'
		,disableLogs: true
		,audioBitsPerSecond:100
		,videoBitsPerSecond: 5000
		,canvas: {
			width: n002,
			height: n003
		}				
		
	});
```

**Comment by niletynay** [comment]
How to solve these issue? Please explain your solution. 
I have the same issue.

**Comment by hktalent** [comment]
video/webm;codecs=vp9
@niletynay 
<img width="900" alt="image" src="https://github.com/muaz-khan/RecordRTC/assets/18223385/a690996b-3a7c-49b3-9c1e-7593ff493dea">

more example:
https://chat.51pwn.com:2083/?cnId=xxx&atRd=true&showme=true&startChat=1?cnId=xxx&atRd=true&showme=true&saveMeVD=true&eSvl=true&eAi=true&startChat=1
