### ISSUE TITLE
Recorded Video Does Not Play in HTML5 Video Player in Firefox Browser

### ISSUE THREAD

**Issue by syedgalib** [muaz-khan/RecordRTC#861]
I have following configuration in my RecordRTC. But when I record a video and place the temp URL generated by from the blob file in the HTML video tag, the video player can not play the video. 

Video player shows "No video with supported format and MIME type found" message.

This problem only occurs in the Firefox Browser.

This issue also exists in your [demo page](https://www.webrtc-experiment.com/RecordRTC/) too.

### My Config

```js
{
  "recordRTCConfig": {
    "disableLogs": false,
    "numberOfAudioChannels": 1,
    "recorderType": RecordRTC.MediaStreamRecorder,
    "type": "video",
    "mimeType": "video/webm;codecs=vp9",
  }
}
```

**Comment by LetMeDream** [comment]
Did you find the solution problem? I think I might be facing the same issue.

Receiving a blob from a p2p connection and trying to use it in the HTML video/source tag. 
It works on Chrome but throws the same  "No video with supported format and MIME type found" message alongside some console warnings:
![consoleWarnings](https://github.com/muaz-khan/RecordRTC/assets/17774989/b9779e2c-6a06-4e88-a9e7-b0b008281010)

**Comment by praine** [comment]
If the video was recorded in one browser and played in another, it might not work. Esp. if the video was recorded in Safari, which does not support the same codecs as the other mainstream browsers. This is not an issue with the WebRTC library, but rather a limitation relating to which codecs are supported by which browsers. For more info, see here: https://stackoverflow.com/questions/66430372/mediarecorder-what-mime-type-to-use-to-make-it-run-on-safari-chrome-and-firef
