### ISSUE TITLE
Shyncronization issue by using recordRTC audio and video record.

### ISSUE THREAD

**Issue by Amarjit1234** [muaz-khan/RecordRTC#87]
Hello Muaz,

Please help me, when I tried to record long audio and video. then there will synchronisation issue happen. I think its cache issue,can you please help me how to clear the browser cache related to this blob, I am loading this script  $.getScript('js/RecordRTC.js'); every time when I start record(audio/Video).

Thanks,
Amarjit

**Comment by zang** [comment]
Suggest you have a look at MRecordRTC to see if works better
