### ISSUE TITLE
timeSlice support like in MultiStreamRecorder

### ISSUE THREAD

**Issue by ryr** [muaz-khan/RecordRTC#89]
any plans on adding timeSlice support for MediaRecorder?

**Comment by muaz-khan** [comment]
There is a separate extracted (a little modified) repository:

* https://github.com/streamproc/MediaStreamRecorder

My plan is to keep main-developments in RecordRTC repo however MediaStreamRecorder should run top over RecordRTC to make sure it uses latest codes/fixes.

**Comment by ryr** [comment]
as i understand to run MediaStreamRecorder top over RecordRTC there should be timeSlice param in recorder .start() function
