### ISSUE TITLE
SampleRate mismatch leads to distorted/slow audio

### ISSUE THREAD

**Issue by wanderr** [muaz-khan/RecordRTC#90]
Example:
https://www.webrtc-experiment.com/RecordRTC/PHP/?bufferSize=16384&sampleRate=44100

If you record here while system microphone is set to 48000, when played back the audio is slowed down and sounds distorted. Overriding sampleRate in the GET to 48000 resolves the issue.

The problem is we don't know what setting our users system has. Is there a way to detect the correct sample rate for the user's device?

**Comment by muaz-khan** [comment]
https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L406

```javascript
var sampleRate = typeof config.sampleRate !== 'undefined' ? config.sampleRate : context.sampleRate || 44100;
```

To clarify above code:

```javascript
var sampleRate = context.sampleRate; // use system's default sample rates

// if user forced custom sample-rates
if (!!config.sampleRate) {
    sampleRate = config.sampleRate;
}
```

You can see that RecordRTC initially tries to take sample-rate value from `AudioContext` however if user forced custom sample-rates then it uses that value instead.

In your case you seems forcing 44100. Try to remove `&sampleRate=44100` from the URL and you should see different result in the console.

**Comment by wanderr** [comment]
Ah, I think I see the problem on that example page, it's doing this instead:
`                            sampleRate: typeof params.sampleRate == 'undefined' ? 44100 : parseInt(params.sampleRate),`
so it does not have a chance to fall back to context.sampleRate

**Comment by muaz-khan** [comment]
Fixed LIVE demo:

* https://www.webrtc-experiment.com/RecordRTC/
