### ISSUE TITLE
File size too big

### ISSUE THREAD

**Issue by indranilatwork** [muaz-khan/RecordRTC#91]
I'm recording audio from the browser and I'm using the plugins

RecordRTC.js
gumadapter.js

After recording the audio I'm seeing 7 secs audio size is 1.31 MB which is too big when I'm recording the audio in google chrome. But if I record the audio in Firefox, the 7 secs audio size is less than 100 KB. 

So why there is so big difference between these two files from two browsers. And actually I need to upload the audio to the server. So the bigger file will take a huge time to upload.
How I can compress the file?

I was checking http://audior.ec/blog/recording-mp3-using-only-html5-and-javascript-recordmp3-js/

But not understanding how it'll be implemented with this plugin.
@muaz-khan What do you suggest?

**Comment by JumpSoar** [comment]
The demo returns .wav audio even when .ogg is requested in chrome.  It works as expected in Firefox.  If this is what your finding do let me know :) (Also want to use the .ogg)

**Comment by rajmjadhav** [comment]
I have also same problem....How we can minimizes records voice size in chrome???

**Comment by indranilatwork** [comment]
Actually I tried with ogg and wav in chrome but in both case the file size is big.

Finally I made one change. In the recorder option I set number of channel to 1.

    var options = {
                          mimeType: 'audio/wav', 
                          bitsPerSecond: 128000,
                          bufferSize: 512,
                          numberOfAudioChannels: 1,
                          recorderType: StereoAudioRecorder
                        };
                        htmlRecordObj.recordRTC = RecordRTC(mediaStream, options);

It reduced the chrome file size atleast 45%. But still it's 650kb for 7 sec audio when it's less than 200kb in firefox.

**Comment by JumpSoar** [comment]
I'm assuming the issue is related to issue https://github.com/muaz-khan/RecordRTC/issues/64 and what we're getting in Chrome is wave (uncompressed audio) even when we request .ogg (compressed audio) as the ability to encode .ogg is a flag to be turned on in chrome beta.

**Comment by elijahkooshad** [comment]
this is still a problem. @muaz-khan was the assumption in the last message still the cause presently [8 years later]?

**Comment by omkarg01** [comment]
@elijahkooshad I am still looking for how to reduce the file size, you got any solution?
