### ISSUE TITLE
MRecordRTC Firefox encoding error

### ISSUE THREAD

**Issue by zang** [muaz-khan/RecordRTC#93]
On Firefox, the recorded audio+video single webm plays fine in browser, but audio stream is broken and doesn't work if you transcode the file to any format. In another word, audio would break if you try to create MP4 from the recorded file. 

Proposed solution: introduce an option in MRecordRTC to record video and audio separately on Firefox. @muaz-khan , what do you think? Let me know if you can think of a better solution so that we can have both webm and MP4 files to satisfy major browsers. (We use MRecordRTC in our project)

Thanks in advanced.

**Comment by thijstriemstra** [comment]
Besides an option to record separately I would also like a setting allowing you to change the audio/video recorder backend.

**Comment by muaz-khan** [comment]
@thijstriemstra is this makes sense?

```javascript
recorder.mediaType = {
   audio: StereoAudioRecorder,
   video: WhammyRecorder,
   gif: true // or GifRecorder
};
```

So we can pass recorder-type as well.

**Comment by thijstriemstra** [comment]
Yes thanks @muaz-khan!

**Comment by thijstriemstra** [comment]
@muaz-khan but this doesn't fix the issue reported here, we'd like to be able to have separate audio/video blobs when recording with mrecordrtc.

**Comment by muaz-khan** [comment]
Now you can try this:

```javascript
recorder.mediaType = {
   audio: StereoAudioRecorder,  // it will return audio/wav
   video: MediaStreamRecorder   // it will return video/webm
};
```

`WhammyRecorder` is NOT compatible in Firefox out of WebP encoder support. So you either need to use `MediaStreamRecorder` or `GifRecorder` in Firefox.
