### ISSUE TITLE
Firefox default recorder

### ISSUE THREAD

**Issue by zzarcon** [muaz-khan/RecordRTC#95]
First of all big thanks for the lib!

I'm wondering why is `MediaStreamRecorder` the default audio recorder for Firefox instead of the `StereoAudioRecorder` one?

The problem for me was that I was initializing the `RecordRTC` as:

``` javascript
let recorder = new RecordRTC(stream, {type: 'audio'});
```

And worked perfectly for Chrome (because was using the `MediaStreamRecorder`) but in Firefox I was getting as a result from the `getBlob` function a Blob with **audio/ogg** mimeType. Casing my recorder to crash later on. 

So I ended specifying the **recorderType** as:

``` javascript
let recorder = new RecordRTC(stream, {recorderType: StereoAudioRecorder});
```

And works perfectly in both browsers :+1: 

So, my question is why Firefox has a different behaviour for the same options? Thanks!

**Comment by DevJhns** [comment]
> 
> 
> First of all big thanks for the lib!
> 
> I'm wondering why is `MediaStreamRecorder` the default audio recorder for Firefox instead of the `StereoAudioRecorder` one?
> 
> The problem for me was that I was initializing the `RecordRTC` as:
> 
> ```js
> let recorder = new RecordRTC(stream, {type: 'audio'});
> ```
> 
> And worked perfectly for Chrome (because was using the `MediaStreamRecorder`) but in Firefox I was getting as a result from the `getBlob` function a Blob with **audio/ogg** mimeType. Casing my recorder to crash later on.
> 
> So I ended specifying the **recorderType** as:
> 
> ```js
> let recorder = new RecordRTC(stream, {recorderType: StereoAudioRecorder});
> ```
> 
> And works perfectly in both browsers +1
> 
> So, my question is why Firefox has a different behaviour for the same options? Thanks!

Hello from 2020, have u solved this? Even setting mimeType audio/webm doesn't help with firefox
