### ISSUE TITLE
how to connect my own stream using recordrtc

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RecordRTC#98]
Hi,nice muaz-khan
you are appreciated for your beautiful recordrtc.it is a great job.
i have a question ,i have a application named mywebrtc and i could get local stream by
mywebrtc.getLocalStream(); or get peer client stream by mywebrtc.getPeerConnectionByUserId(customerid).getRemoteStreams();now i would like to use recordrtc to save video and audio.i read your sample.but i am not sure how to do it.so i would like ask you how to connect my own stream using recordrtc.
you code
function captureUserMedia00(callback) {
        	
           captureUserMedia({
                audio: true,
                video: true
            }, function(stream) {
                videoElement.src = URL.createObjectURL(stream);
                videoElement.muted = true;
                videoElement.controls = true;
                videoElement.play();

                callback(stream);
            }, function(error) {
                alert(JSON.stringify(error));
            });
        }
is open local cam and audio device .but now i want to connect my stream.
how to do it
thanks

**Comment by muaz-khan** [comment]
You can record both local/remote streams using RecordRTC.

```javascript
var recorderType = MediaStreamRecorder;
if(!!navigator.mozGetUserMedia) {
    recorderType = StereoAudioRecorder;
}

var recorder = RecordRTC(localOrRemoteStream, {
    type: 'video',
    recorderType: recorderType
});

recorder.startRecording();

localOrRemoteStream.onended = function() {
    recorder.stopRecording(function(videoLocalURL) {
         var blob = recorder.blob;
         UploadToServer(blob);

        recorder.getDataURL(function(dataURL) {
             UploadToServer(dataURL);
        });

        videoPreview.src = videoLocalURL;
        videoPreview.play();
    });
};
```

**Comment by Jackie2016** [comment]
hi,thanks

**Comment by Jackie2016** [comment]
hi,thanks for your kind reply.but i met some trouble as below
chrome: {"video":{"mandatory":{},"optional":[]},"audio":true}
chat_room.js:563 Successfully connected
RecordRTC.js:47 started recording video stream.
RecordRTC.js:763 Using recorderType: MediaStreamRecorder
RecordRTC.js:1495 Passing following config over MediaRecorder API. Object {type: "video", mimeType: "video/webm"}
RecordRTC.js:83 Initialized recorderType: MediaStreamRecorder for output-type: video
RecordRTC.js:96 Stopped recording video stream.
chat_roomcom1.html?comid=c28:124 Uncaught ReferenceError: UploadToServer is not defined

where is UploadToServer
