### ISSUE TITLE
 how to get video file from localbuffer in RecortRTC

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RecordRTC#99]
hi, muaz-khan,kind experts,
i have test your code post in https://github.com/muaz-khan/RecordRTC/issues/98.i get error say Uncaught ReferenceError: UploadToServer is not defined.i think UploadToServer code is need to save local buffer to files.could you give me UploadToServer function in detail.or could you tell me how to get video file from localbuffer in RecortRTC.thanks a lot.

the error show as below
chrome: {"video":{"mandatory":{},"optional":[]},"audio":true}
chat_room.js:563 Successfully connected
RecordRTC.js:47 started recording video stream.
RecordRTC.js:763 Using recorderType: MediaStreamRecorder
RecordRTC.js:1495 Passing following config over MediaRecorder API. Object {type: "video", mimeType: "video/webm"}
RecordRTC.js:83 Initialized recorderType: MediaStreamRecorder for output-type: video
RecordRTC.js:96 Stopped recording video stream.
chat_roomcom1.html?comid=c28:124 Uncaught ReferenceError: UploadToServer is not defined

hope for your reply.you are appreciated.

**Comment by muaz-khan** [comment]
```javascript
function UploadToServer(blob) {
    var fileType = 'video'; // or "audio"
    var fileName = 'ABCDEF.webm'; // or "wav"

    var formData = new FormData();
    formData.append(fileType + '-filename', fileName);
    formData.append(fileType + '-blob', blob);

    xhr('save.php', formData, function(fName) {
        window.open(location.href + fName);
    });
}

function xhr(url, data, callback) {
    var request = new XMLHttpRequest();
    request.onreadystatechange = function() {
        if (request.readyState == 4 && request.status == 200) {
            callback(location.href + request.responseText);
        }
    };
    request.open('POST', url);
    request.send(data);
}
```

Code/Demo ref: [RecordRTC-to-PHP/index.html#L696](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-PHP/index.html#L696)
